### PR TITLE
[blockly] Fix timer remove regression

### LINKED ISSUE #2002: [blockly] bug in "after" block (count script)
## The problem

A script that should count up from 0 to 10 every second aborts after the second run with ECMAScript 262 edition 11:.

image

```
var count;

console.info('SCRIPT count');
count = 0;
if (cache.private.exists('MyTimer') === false || cache.private.get('MyTimer').hasTerminated()) {
  cache.private.put('MyTimer', actions.ScriptExecution.createTimer('MyTimer', time.ZonedDateTime.now().plusSeconds(1), function () {
    if (count <= 10) {
      count = (typeof count === 'number' ? count : 0) + 1;
      console.info(count);
      if (cache.private.exists('MyTimer')) { cache.private.get('MyTimer').reschedule(time.ZonedDateTime.now().plusSeconds(1)); };
    }
    cache.private.remove('MyTimer');
  }));
};
```

## Expected behavior
The output ends after the 2nd pass but should count to 10:

```
==> /var/log/openhab/openhab.log <==
2023-07-31 13:08:01.617 [INFO ] [nhab.automation.script.ui.a08104671c] - SCRIPT count
2023-07-31 13:08:02.619 [INFO ] [nhab.automation.script.ui.a08104671c] - 1
2023-07-31 13:08:03.620 [INFO ] [nhab.automation.script.ui.a08104671c] - 2
```

## Steps to reproduce
See Screenshot and code above.

## Your environment
runtimeInfo:
  version: 4.0.0
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.7
  javaVendor: Raspbian
  osName: Linux
  osVersion: 6.1.21-v8+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 273486896
  totalMemory: 766193664
  startLevel: 100
bindings: null
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1.100000023841858
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 16
    language: de
    languages:
      - de
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/115.0.0.0 Safari/537.36
timestamp: 2023-08-02T18:36:14.830Z

### PR DESCRIPTION
**Pull request by stefan-hoehn**
Fixes #2002.

### CODE REVIEW

**Review by florian-h05 — APPROVED** [review]
LGTM, thanks!
I’ve just had a look a the Nashorn code, there it also does not remove the timer from `this`.

**Comment by florian-h05** [comment]
@kaikreuzer Can you please cherry pick this to 4.0.x before the release is done? I’ve mentioned it in the release thread, seems like you didn’t see it.

**Comment by kaikreuzer** [comment]
I indeed didn't see the message and so this unfortunately hasn't yet been backported before the 4.0.3 build. I did so now, so that it will end up in 4.0.4.
Please best always consider backporting directly when merging a PR; otherwise it also becomes very tricky with the compilation of the release notes.

**Comment by florian-h05** [comment]
I usually backport when merging, but I was away (on vacation) and only had my phone with me, I merged with GitHub web but I cannot backport from my phone. Thanks for doing it anyway.

**Pull request merged**
