### PR TITLE
Analyzer: Fix analyzer not initially visible on iOS 17.4

### PR DESCRIPTION
**Pull request by florian-h05**
When the analyzer was opened on iOS/iPadOS 17.4 devices, the screen stayed blank until the controls were opened.

ECharts logged the following warning to the console:

```
[ECharts] Can't get DOM width or height.Please check dom.clientWidth and dom.clientHeight.
They should not be 0.For example, you may need to call this in the callback of window.onload.
```

This is more or less a workaround, since I cannot really debug on iOS as I have no Mac and BrowserStack does not provide iOS 17.4 devices at the moment. I have checked that this workaround does not affect other devices.

Reported on the community: https://community.openhab.org/t/openhab-4-1-release-discussion/152252/188?u=florian-h05.

### CODE REVIEW

**Comment by scheuerer** [comment]
As said before, the usse is not gone with the current 4.2 build.
I have several view with worked in past normal.
Now when open then tehy are empty, like this
IMG_0015

So I need to press an other graph, eg the humity, that the new graph is shown correct, like this:
IMG_0017

If the clicking for the old temperature graph, which was first empty, now it is also filled right.
See here:
IMG_0016

Everthing is about that when open the graph the first time it is empty....

**Comment by florian-h05** [comment]
Context? From your screenshots I assume iPad, but which iOS version? Which browser and which browser version?
And this here is a PR to fix problems with the analyzer, not with chart pages as shown in your screenshots.
Apart from that, I can neither reproduce your issue on iPad OS 17.5.1 with Safari nor on iOS 17.5.1 with Safari.

Have you tried reload app & clear cache and reload app from Help & About?

**Comment by scheuerer** [comment]
Some more information. iOS 17.5.1 on an iPad 12, with Safari and Firefox. No different in the issue which browser I use. 
Here is video which I hope to help

https://www.dropbox.com/scl/fi/qj3vtnivimvssjv6lwm1f/20240716_223436.mp4?rlkey=domypwdhdy8n9d7nf1y8fg98z&dl=0

**Comment by florian-h05** [comment]
> Have you tried reload app & clear cache and reload app from Help & About?

??

Can you please share the YAML Code of these chart pages?

**Comment by florian-h05** [comment]
Another thing to try: Do the charts on the demo server work for you?

https://demo.openhab.org/page/chart_tabs

**Comment by Beluk** [comment]
I have the same issue with charts. They only work after the second time. 

My config is...

config:
  chartType: day
  label: Stromverbrauch pro Stunde
  order: "1"
  sidebar: true
  visibleTo:
    - role:administrator
    - role:user
slots:
  grid:
    - component: oh-chart-grid
      config: {}
  series:
    - component: oh-aggregate-series
      config:
        aggregationFunction: average
        dimension1: hour
        gridIndex: 0
        item: SmartmeterLeistung
        name: Energie
        type: bar
        xAxisIndex: 0
        yAxisIndex: 0
  xAxis:
    - component: oh-category-axis
      config:
        categoryType: day
        gridIndex: 0
        monthFormat: default
        weekdayFormat: default
    - component: oh-time-axis
      config:
        gridIndex: 0
  yAxis:
    - component: oh-value-axis
      config:

**Comment by florian-h05** [comment]
Can you please create a new issue and provide the full context as requested by the template there?
A merged PR especially one that is about a different issue is no place to further discuss bugs. Feel free to ping me on the new issue, thanks.

**Comment by florian-h05** [comment]
Although I haven't seen anyone open an issue for the issues report in this PR, I took a second look and @Beluk 's chart code allowed me to finally reproduce the issue. I have created a fix #2677 with which I cannot reproduce the issue anymore.

**Pull request merged**
