### PR TITLE
Fix height description in grid layout properties

### PR DESCRIPTION
**Pull request by eikowagenknecht**
Just a quick fix of a copy/paste error.

Signed-off-by: Eiko Wagenknecht <eiko.wagenknecht@web.de>

### CODE REVIEW

**Comment by ghys** [comment]
Thanks, could you run `node generate.js` in `doc/components/src` as well to update the documentation page? (commit only the `doc/components/oh-grid-layout.md` file. If it doesn't work you may update it manually as the change is small.

**Comment by eikowagenknecht** [comment]
Sure, it's done. I noticed there are some differences in oh-cell, oh-label-card and oh-label-cell as well after generating the docs, maybe those were forgotten somewhere else?

image

**Comment by ghys** [comment]
This is a result of #993 not being complete as it changed the fix for the oh-trend component but not those which includes an trend line and therefore inherit its parameters.
If you still have those around, I'd be grateful if you could commit these as well as part of this PR.

**Comment by eikowagenknecht** [comment]
Sure, I made it a second commit in this PR because it's another issue, hope that's allright.

**Review by ghys — APPROVED** [review]
Thanks, much appreciated!
The Jenkins build failure is not related to this PR.

**Pull request merged**
