### PR TITLE
Semantic tags: Fix missing translations in case of missing label

### LINKED ISSUE #1976: SoundVolume property category shown as "undefined" in main UI
When viewing the Properties page in Main UI, the SoundVolume property group is labeled "undefined". This is a new issue noticed post OH3.4 -> OH4 upgrade.

image

Property page should be labeled "Sound Volume" per model

Click on Properties page and look at SoundVolume property page.

1. 

## Your environment

```yaml

runtimeInfo:
  version: 4.0.0
  buildString: "Build #3545"
locale: en-US
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.7
  javaVendor: Private Build
  osName: Linux
  osVersion: 6.1.11-meson64
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 60074320
  totalMemory: 458227712
  startLevel: 100
bindings: null
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 16
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 2560
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/114.0.0.0 Safari/537.36
timestamp: 2023-07-21T18:01:32.050Z


## Browser console

<!--
Open the developer tools in your browser, go to the Console tab and paste errors and other messages that might be relevant to this issue.
You may also paste a screenshot if you prefer.
-->

```txt

```

### PR DESCRIPTION
**Pull request by florian-h05**
Fixes #1976.
Follow-up for #1882.

### CODE REVIEW

**Comment by florian-h05** [comment]
@ghys This should be backported to 4.0.x as well.

**Review by ghys — APPROVED** [review]
Agree with the backport, this seems pretty annoying bug to have in a major release.

**Comment by lolodomo** [comment]
Just to understand, it was when the label of a semantic tag was not translated? 
Which language are we talking about for SoundVolume?

**Comment by florian-h05** [comment]
So when translations were missing, REST returns no label for a tag. In this case, no translation was stored in UI, and therefore UI failed to display any and instead undefined was shown.

**Comment by lolodomo** [comment]
But I just opened all translation files and one entry is there for SoundVolume for all languages. 
I do not understand how the API could have returned an empty label... except if there is a bug somewhere.

**Comment by florian-h05** [comment]
That’s interesting. However, as long as none of us can reproduce this, no one will able to debug and check if there is an actual bug.

**Comment by bkpsu** [comment]
> That’s interesting. However, as long as none of us can reproduce this, no one will able to debug and check if there is an actual bug.

I'm still able to reproduce the issue with 4.1.0.3568 - screenshot attached. Let me know what I can do to help debug.

image

**Comment by lolodomo** [comment]
Please open the API explorer in Main UI, run the GET API from tags endpoint and show the result, only the part related to SoundVolume tag

**Comment by bkpsu** [comment]
Here is my result from API Explorer for the SoundVolume tag:

  {
    "uid": "Property_SoundVolume",
    "name": "SoundVolume",
    "label": "Sound Volume",
    "description": "",
    "synonyms": [],
    "editable": false
  },

**Comment by lolodomo** [comment]
What language is setup in your browser settings ?

**Comment by bkpsu** [comment]
en-US

**Comment by lolodomo** [comment]
And if you call the REST API with language parameter set to "en-US", you get the same result as before ?
That is the case when I try myself.
That looks clearly like a bug in Main UI if the API is returning the expected result.

**Comment by bkpsu** [comment]
Yes, even with the "en-US" language setting in REST-API, I get the same result.

 For completeness, I'm showing my Main UI Properties settings when hitting Edit:

image

Even there, the property shows undefined

**Comment by florian-h05** [comment]
@bkpsu Can you please open the browsers developer tools, right-click on the reload button to "reset cache and reload all" and then post both the headers and the response of the `tags` request.

**Comment by bkpsu** [comment]
Did full cache clear and reload, then re-ran the API:

Headers:
cache-control: private,no-transform,must-revalidate 
 content-encoding: gzip 
 content-type: application/json 
 date: Sat,29 Jul 2023 16:44:08 GMT 
 last-modified: Fri,28 Jul 2023 16:51:38 GMT 
 server: Jetty(9.4.50.v20221201) 
 vary: Accept-Encoding,User-Agent 

Tag:
  {
    "uid": "Property_SoundVolume",
    "name": "SoundVolume",
    "label": "Sound Volume",
    "description": "",
    "synonyms": [],
    "editable": false
  },

**Comment by florian-h05** [comment]
The API response looks good, I honestly have no idea where the problem is.

**Pull request merged**
