### PR TITLE
[Main UI] Add Setup Wizard

### PR DESCRIPTION
**Pull request by ghys**
This launches a setup wizard when openHAB is started for the
first time. It allows to:

- set some regional settings (language, region, timezone)
- set the location, optionally with the help of the browser Location API
- install an initial set of add-ons

It is also possible to skip any of these steps, or the setup wizard
altogether. Regardless, the "overview" layout page will be created
so that it can act as a detection mechanism to determine whether the
setup wizard has already run or not, and prevent it from being shown
a second time. Therefore, deleting the overview page has been made
impossible in the UI's pages list.

Here's how a completely fresh openHAB instance looks like with this PR
when accessing the UI for the first time (note how the user is immediately
asked to sign in i.e. create their account, and that the HABot text box/astro
inbox entries immediately appear in the chosen language):

openhab-setup-wizard

When we localize the UI properly we'll try to make the language change
as soon as the setting is selected on the first screen.

I encourage everyone to do exploratory testing of this one, and comment on
the design/wording of messages, as it's the first time experience new users
will have and therefore I think it's important that we get it right IMO.

Signed-off-by: Yannick Schaus <github@schaus.net>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Wow, that looks awesome! Great stuff and a huge step forward in first-time setup UX. 👍 

A first question I'd have: Would it be possible to derive the language/region/timezone from the browser, so that those fields are prefilled? It feels a bit tedious for the user to fill in all 3 values from long selection lists, although it is very often just a fixed triplet (many countries simply have just one language and one timezone).

**Comment by ghys** [comment]
> A first question I'd have: Would it be possible to derive the language/region/timezone from the browser, so that those fields are prefilled? It feels a bit tedious for the user to fill in all 3 values from long selection lists, although it is very often just a fixed triplet (many countries simply have just one language and one timezone).

Modern browsers have `Intl.DateTimeFormat().resolvedOptions()`, this is what I get on 2 different browsers:

image
image
So I believe we could parse the language & region from the locale, if we're careful, and also the timezone if we make sure there's a match in the parameter options.

**Comment by yveshanoulle** [comment]
I think it's a huge improvement for real first users. Much appreciated.
The better a community support it's first time users, the faster and better it grows.

Please don't forget that a lot of people do set up a new instance, that are not first time users.
I have my openhab hardware double. When I want to install a new version: I start with a new installation of the new version. (From scratch, like I am a person new to the software)
I do an initial launch, just to see of openhab launches. 
And then I download my configuration from my source control system. 
When that works, I turn the other instance of openhab (they both have a different IP adres)

From that moment on, 
I do all my changes from my own computer
upload it them to the sourcecontrol system
download them on the hardware (preferable by clicking a button in  the openhab app) 

This is not a first user experience, so I don't want you to do anything for my experience, yet I hope you also don't break that.

**Comment by ghys** [comment]
> This is not a first user experience, so I don't want you to do anything for my experience, yet I hope you also don't break that.

Don't worry, I'm rather on the careful side when it comes to breaking stuff, I tend to avoid it when possible. 😎 

The setup wizard will not get in your way in the scenario you describe, because if the "marker" indicating that it has already run (the overview page has been created - btw happy to discuss something else but it was the best I could come up with), it will _not_ run again; and in a restore-from-backup scenario it's likely you include the JSON DB - including the overview page stored from a previous run.

If it does run, for instance you migrate from OH2 which doesn't have this overview page concept, all it does for now is help you (re)configure some regional settings and install the add-ons you specify, so it's hardly destructive, and as described above you can skip it entirely or any step of it.

> I believe we could parse the language & region from the locale, if we're careful, and also the timezone if we make sure there's a match in the parameter options.

Implemented in https://github.com/openhab/openhab-webui/pull/306/commits/cdf0cd70c4b0dde1e9240f81a6fa5d2d30d18552

**Comment by yveshanoulle** [comment]
>The setup wizard will not get in your way in the scenario you describe, because if the "marker" indicating that it has already run
Well before I download the configuration, I do go to openhab page, just to see if it runs.
At that moment I haven't downloaded anything, so I assume your wizard comes up
then I go to a terminal to download the code from sourcecontrol

I'm not using  the "restore-from-backup scenario", hence also not backup restore teh json.
I'm using the configuration files (not sure that is the right name) 
where I have defined services, items, things, servicemap

**Comment by ghys** [comment]
Nothing to add for now, so I consider this PR ready 🚀

**Comment by hmerk** [comment]
Again, excellent work Yannick !!!!!

**Comment by wborn** [comment]
It looks super nice and helpful! :+1: :1st_place_medal: 

What would be nice additions:
* case insensitive sorting for add-ons
* dark mode :sunglasses:

**Comment by gersilex** [comment]
What about asking for the location first and then derive the time zone, region and language from that?

Also the call to action at the end [Finish] is too subtile in my opinion and might be in the primary color and also say something more enthusiastic like [Get Started] or something. It is true that the initial configuration has finished, but that' where I as a user get started and have fun in openHAB. 

In any case, amazing work once again!

**Comment by ghys** [comment]
> say something more enthusiastic like [Get Started] or something. It is true that the initial configuration has finished, but that' where I as a user get started and have fun in openHAB.

had the same thoughts exactly, the screenshot in the OP is outdated 😄 (see https://github.com/openhab/openhab-webui/pull/306/commits/a272427c728c7720c7da25b1d86230da8ef3a251)

> case insensitive sorting for add-ons

that's the order of the API, so not sure where it should be fixed in the client or the backend 🤔 

> dark mode

already there if your OS tells your browser to use dark mode - I'd tend to think it's enough, no need for a switch, it's per device anyway.

**Comment by ghys** [comment]
Please deal with me as I self-merge my own PR again, but with a bit of an explanation/disclaimer this time about why I'm giving myself that right:

- I feel those are not going to be properly tested/reviewed anyway, since there might be a reluctance from other active maintainers to get involved in frontend technologies they are not familiar with (if there's people reading this who are, please step up, we need you!);
- Maybe the best way to figure out whether there are problems with these additions is to let Jenkins build distributions including them, and let interested parties test them - this is IMHO probably acceptable while openHAB 3 snapshots are still not deemed ready for prime time yet, so there's leeway in what's included in them without proper review - experiments and beta features might be considered valuable to include for the sake of having more people test them; of course when there's an established userbase of those snapshots, potentially breaking changes are not going to be acceptable, so this policy will have to be revisited;
- People testing OH3 snapshots at this time cannot be guaranteed there isn't going to be a critical bug in them; however, those which are properly reported are probably going to be fixed in a timely fashion in a subsequent snapshot as we keep the momentum going, because that's where the focus is;
- We are still in a period where adjustments can easily be made to these features after some testing, i.e. the feature set doesn't have to be final for PRs like these to be merged, it could be done in an "organic" fashion: merge early, test, and figure out what's missing.

If there's any disagreement with the above, please let me know and I will stop the self-merging. 😊

**Comment by gersilex** [comment]
Thank you for the details about why this has been merged by yourself. Although I'm no active/regular maintainer, I understand the code I found in the diff and don't see any problems with that.

If you are looking for someone that is deeply in the vue and f7 space, I can not help you, but if you are looking for someone to challenge your changes I am really open to that in a productive and friendly manner.

If interested, what about testing. I see some interesting and important steps for first-time users. Are there any plans for automated end-to-end testing so we can ensure that it won't break when this or other parts of the openHAB codes change?

**Comment by ghys** [comment]
> If interested, what about testing. I see some interesting and important steps for first-time users. Are there any plans for automated end-to-end testing so we can ensure that it won't break when this or other parts of the openHAB codes change?

Yes, good remark; I put the infrastructure in place early on to do both unit tests with Jest and e2e tests with Cypress, but writing them takes a lot of time, so it didn't get a lot of love... the main focus being adding features to make the whole thing usable.

That being said I believe feature-wise the UI is in good shape, and slowly getting there, so there will probably be fewer of these big feature additions and more PRs focused on stablization/behind-the-scenes improvements; there's a lot to be done in that area, but a lot of feedback will likely come when there's a formal go-ahead to the community to start trying out OH3.

**Comment by gersilex** [comment]
Sounds good. I already worked with Cypress and feel like I can support you there with a couple of realistic test cases. I also work closely with quality engineers that can help us do the end-to-end tests in an efficient and correct (quality-wise) manner.

You sound like you have a strong vision in mind for the cypress structure or it already is done and I could not find it. Feel free to ping me as soon as you need someone develop and write e2e test cases. I'm happy to help with that.

**Comment by ghys** [comment]
> You sound like you have a strong vision in mind for the cypress structure or it already is done and I could not find it. Feel free to ping me as soon as you need someone develop and write e2e test cases. I'm happy to help with that.

Excellent! To be honest there's no grand plan on these tests, I just made sure we _could_ have some at some point,
How they work is briefly mentioned in [CONTRIBUTING.md](https://github.com/openhab/openhab-webui/blob/master/bundles/org.openhab.ui/CONTRIBUTING.md#npm-scripts) - you should be able to run them with `npm run test:e2e` or `npm run test:e2e:gui`. As stated below in this file you should also launch `npm start` in parallel beforehand and make sure it runs on http://localhost:8081 (or adjust [`cypress.json`](https://github.com/openhab/openhab-webui/blob/master/bundles/org.openhab.ui/web/cypress.json) as necessary).

The Cypress structure is in `www/test/cypress` ([here](https://github.com/openhab/openhab-webui/tree/master/bundles/org.openhab.ui/web/test/cypress)) and there's a first basic test [here](https://github.com/openhab/openhab-webui/blob/master/bundles/org.openhab.ui/web/test/cypress/integration/home.js), but there's not much else.

**Comment by gersilex** [comment]
Awesome, this should be enough to get me started. I'll think about useful, realistic and correct test-cases and will create a new Issue for those before working on them to keep everyone who wants to contribute involved and informed.

Thanks for all the information!

**Pull request merged**
