### PR TITLE
[BasicUI] Switch between several Button elements at a place in the grid

### PR DESCRIPTION
**Pull request by lolodomo**
Several Button elements are accepted at the same place in the grid only when they all have visibility conditions.
In this case, the user must define proper conditions so that only one button is visible at any time.

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
Here is an example with two buttons switching depending on the item state:
```
            Button item=DemoSwitch row=1 column=1 stateless click=ON staticIcon=switch-off visibility=[==OFF]
            Button item=DemoSwitch row=1 column=1 stateless click=OFF staticIcon=switch-on visibility=[==ON]
```

**Comment by kaikreuzer** [comment]
@lolodomo Do you wish this to be included into the next milestone?

**Comment by lolodomo** [comment]
Yes Kai, please, it finishes the feature.

**Review by kaikreuzer — APPROVED** [review]
Thanks!

**Pull request merged**
