### PR TITLE
Initial Italian translation

### PR DESCRIPTION
**Pull request by llegovich**
please review and merge if everything is ok.

Signed-off-by: Luciano Legovich <llegovich@yahoo.it>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks, that was quick!
Could you please make sure that your commits are signed-off (see https://www.openhab.org/docs/developer/contributing/contributing.html#sign-your-work and https://github.com/openhab/openhab-webui/pull/55/checks?check_run_id=99765733).

**Comment by llegovich** [comment]
Hi @kaikreuzer sorry to bother, I cannot sing this off via command line, I did use the web ui to build the fork and pull requests.
I'm not sure I understand how to sign this off via web ui. Should I create a new pull request? thx

**Comment by kaikreuzer** [comment]
When using the Github web ui, you can add the "Signed-off-by" line in the comment field and it will end up in the commits. But don't worry, no need for a new PR - just add the "Signed-off-by" to the description of the PR itself and we can take care to add it to the squashed commit when merging.

**Comment by kaikreuzer** [comment]
@ghys Could you check if format etc. is ok?

**Comment by ghys** [comment]
Doesn't look too bad, thanks @llegovich!
However, it would be great if you could try and add a test class similar to the ones in https://github.com/openhab/openhab-webui/tree/master/bundles/org.openhab.ui.habot/src/test/java/org/openhab/ui/habot/test ideally using assertions (you can take the NL or FR one as an example), and make sure some basic sentences are correctly interpreted with assertions - both the intent and the extracted entities. Natural language processing sometimes does not perform equally well in every language given the same training data so the tests ensure the basics work, to give the best experience to users. Crafting a good training for a given language is normally a process involving tests and adaptations until a good accuracy is reached - not merely a matter of translation.
Thanks again.

**Comment by llegovich** [comment]
Hi @ghys, I will do that, but I'm new to github: once I have the new files ready should I crate a new pull request for the new files or are you going to reject this PR and I create a new PR with the whole italian translation?
Thx

**Comment by ghys** [comment]
Hi @llegovich - sorry for the delay.
The development environment and build process are still evolving for openHAB in general and this repo in particular, so I understand if you're confused. The developer documentation is also being worked on, so it should become clearer in the near future.
I still think some basic tests are necessary to ensure a decent accuracy for the Italian language though. When the above are stabilized, if you add some tests to your branch and they will appear here.
If you're not feeling up to this task, we'll find another solution for those.

A bit of advice however: your PR is based on your "master" branch, which is bad practice in general - you should have created a new named branch (e.g. "italian"), added the commits on that branch and used it as the base branch. That way your "master" branch in your fork is tracking the "master" branch here, this avoids some headaches if you're not used to Git. It might actually be simpler to close this PR and open a new one.
Here's some more reading material:
https://help.github.com/en/articles/creating-a-pull-request#changing-the-branch-range-and-destination-repository
https://www.openhab.org/docs/developer/contributing/contributing.html#contribution-guidelines

**Comment by llegovich** [comment]
ok thank you. please reject this PR, I will raise a new one.

**Comment by llegovich** [comment]
Hi @ghys,
I have:
1. deleted my forked repository.
2. forked a new repository
3. created a branch named "italian" on my repo
4. uploaded the Italian translation of .properties and "train" folder
5. added a few lines of code to the TokenizerTest.java to include Italian and created a TrainerItTest.java
Everything committed with #55 in the subject and signed off.
I have not merged the branch in my repo's master and not yet created a PR.

Is everything ok now to create a new PR? Or did I mess up all the files again :-)? Thanks.

**Comment by ghys** [comment]
@llegovich many thanks!
This looks really good now!
You can open a new pull request from here:
https://github.com/openhab/openhab-webui/compare/master...llegovich:italian?expand=1
I will close this one.

**Pull request closed without merging**
