### PR TITLE
Page edit: Add editing of tags

### LINKED ISSUE #2077: [MainUI] Editing of Tags for MainUI Pages
## The problem
As of now it is not possible to edit Tags for Pages via MainUI similar to what is possible for Items and Rule. Tags are supported for Pages and they can be added/changed via REST API. However, UI is to prepared for it.

## Your suggestion
Extend MainUI to support editing of Tags in Page designer.

## Your environment
runtimeInfo:
version: 4.0.3
buildString: Release Build
locale: cs-CZ
systemInfo:
configFolder: /etc/openhab
userdataFolder: /var/lib/openhab
logFolder: /var/log/openhab
javaVersion: 17.0.8.1
javaVendor: Azul Systems, Inc.
javaVendorVersion: Zulu17.44+53-CA
osName: Linux
osVersion: 5.4.0-162-generic
osArchitecture: amd64
startLevel: 100
clientInfo:
device:
ios: false
android: false
androidChrome: false
desktop: true
iphone: false
ipod: false
ipad: false
edge: false
ie: false
firefox: false
macos: false
windows: true
cordova: false
phonegap: false
electron: false
nwjs: false
webView: false
webview: false
standalone: false
os: windows
pixelRatio: 1
prefersColorScheme: light
isSecureContext: true
locationbarVisible: true
menubarVisible: true
navigator:
cookieEnabled: true
deviceMemory: 8
hardwareConcurrency: 8
language: cs-CZ
languages:
- cs-CZ
- cs
- en
- sk
onLine: true
platform: Win32
screen:
width: 1920
height: 1080
colorDepth: 24
support:
touch: false
pointerEvents: true
observer: true
passiveListener: true
gestures: false
intersectionObserver: true
themeOptions:
dark: light
filled: true
pageTransitionAnimation: default
bars: filled
homeNavbar: default
homeBackground: default
expandableCardAnimation: default
userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
like Gecko) Chrome/116.0.0.0 Safari/537.36
timestamp: 2023-09-14T22:09:26.488Z

### PR DESCRIPTION
**Pull request by Davek145**
Closes #2077.

This PR adds ability to add / change / remove Tags to Pages via MainUI.
It is using existing tag-input.vue component similar as UI for Items and Rules.

### CODE REVIEW

**Review by florian-h05 — COMMENTED** [review]
Funny how small the world is 😂

I’ve just read your community post about your fork of my multiuser proxy (I will have a to take a closer look at it, I’m curious) — BTW I am really happy to have it forked by someone — and started to read the README and read something about a PR. 

After abandoning this project (mostly because I did not really need it) I slowly started contributing to openHAB, and so I’m here now as a UI maintainer and I can review your PR:

For consistency I would prefer to have the tag input separate from the name, label etc. — the same as for rules etc.
Implementation:

https://github.com/openhab/openhab-webui/blob/cf3b21857187fb288b2db521652d5d7b778bbfd7/bundles/org.openhab.ui/web/src/pages/settings/rules/rule-edit.vue#L153-L157

Next, the tags should be shown on the https://github.com/openhab/openhab-webui/blob/cf3b21857187fb288b2db521652d5d7b778bbfd7/bundles/org.openhab.ui/web/src/pages/settings/pages/pages-list.vue, for implementation see:

https://github.com/openhab/openhab-webui/blob/cf3b21857187fb288b2db521652d5d7b778bbfd7/bundles/org.openhab.ui/web/src/pages/settings/rules/rules-list.vue#L104-L108

**Comment by Davek145** [comment]
Hi Florian. Yes, I have noticed you being now UI maintainer. And you are right, this PR is there because I realized the need when adjusting the multi-user proxy.

> For consistency I would prefer to have the tag input separate from the name, label etc. — the same as for rules etc.

Yes, I understand. Actually, this is what I have started with. But actually it did not look good in the Page designer given the dynamic part below this template. That is why in the end I have choosen the accordion. But no problem to make ti separate again. I will just welcome your help in adjusting the vue template, so it works and looks good.
I will make separate branch with my prior version that had the tag edit separated from name / label and ask you to take a look.

> Next, the tags should be shown on the https://github.com/openhab/openhab-webui/blob/cf3b21857187fb288b2db521652d5d7b778bbfd7/bundles/org.openhab.ui/web/src/pages/settings/pages/pages-list.vue

This is actually already there. All tags are showing in Pages list already now. Including those added by API or via my PR.

**Comment by florian-h05** [comment]
> I will make separate branch with my prior version that had the tag edit separated from name / label and ask you to take a look.

Well, let’s see what looks better then.
I will be back home this evening, so I should be able to have a look today or tomorrow 

> This is actually already there. All tags are showing in Pages list already now. Including those added by API or via my PR.

Yeah, I did not expect that, but I’ve checked the code and it is indeed there.

**Review by florian-h05 — APPROVED** [review]
LGTM, thanks!
The accordion tag input looks way better than the separate one.

I think we can omit the "Non-Semantic", I have removed this.

**Comment by florian-h05** [comment]
@Davek145 I just wanted to merge this, however I have noted that you made your commits using a GitHub no-reply mail address. This is no problem in general, however does DCO (se https://www.openhab.org/docs/developer/contributing.html#contributing-to-the-development-of-openhab) require a mail address under which you are actually reachable.

Can you please comment a sign-off line that is valid according to https://www.openhab.org/docs/developer/contributing.html#contributing-to-the-development-of-openhab?

**Comment by Davek145** [comment]
> @Davek145 I just wanted to merge this, however I have noted that you made your commits using a GitHub no-reply mail address. This is no problem in general, however does DCO require a mail address under which you are actually reachable.

@florian-h05, this commit is having Sign-off using valid email address as well. You are right that there is also the no-reply address next to it. I have fixed my github settings, so it will not be adding this no-reply sign-off when I make these small commits from webedit. What exactly do you mean by "Can you please comment a sign-off line"? As you made the change in the code I do not want to edit the original commit. Sorry, I have not used Github for more than a decade, so getting back into using it.

**Comment by florian-h05** [comment]
Sorry, I have just checked your commit message and the first Sign Off from the first commit is fine. GitHub however selects the last sign off line when proposing a message for the merge, so I did not see that sign off.

Everything is fine, thank you for the hint!

**Comment by lolodomo** [comment]
Just to be clear, does this PR adds the ability to manage tags by adding custom tags?

**Comment by Davek145** [comment]
Yes, what ever Tags you want to put in. Same as for Rules, Items ...
PR is just adding UI. The functionality is the one available by REST API.

**Comment by lolodomo** [comment]
Cool, I will test that during the weekend.

**Comment by lolodomo** [comment]
Is it possible to have a screenshot showing how it looks like?

**Comment by lolodomo** [comment]
I just installed the very last version but I do not find any new page to manage tags.
image

**Comment by florian-h05** [comment]
This PR is not about having a page to edit the semantic model, it adds the ability to add and remove tags for pages.

**Comment by Davek145** [comment]
Sorry @lolodomo, I did not understand your question correctly. As said by @florian-h05, my PR is about non-semantic tags and ability to add / remove them for pages via UI. Similar to what is already possible for Rules and Items.
If you are looking for the ability to change custom semantic tags, than it is possible now with OH4. I like it very much and have already expanded my semantic model given the fact I have quite sizable OH instance. But as of now, my understanding is it is still possible only via /rest/tags .
If nobody is working on UI for this yet, which I understood from forum discussions may be the case, I can take a look at it later. But it will take some time. I'm now finishing some other UI enhancements for non-semantic tags.

**Pull request merged**
