### PR TITLE
Thing add page: Add support for optional scan input

### PR DESCRIPTION
**Pull request by florian-h05**
Refs https://github.com/openhab/openhab-core/pull/4389.

image

### CODE REVIEW

**Comment by lolodomo** [comment]
Tested and it works exactly as we expected. Top. @digitaldan you can now rely on this new feature and remove pairing code as thing configuration and as thing channel.

@florian-h05 I just saw a little bug in rendering with a text almost hidden:
image

**Comment by florian-h05** [comment]
@lolodomo Thanks for noticing … this is cause by a „quick-and-dirty“ style fix I used, I should probably do it the clean way now.

**Comment by lolodomo** [comment]
@florian-h05 : final step would be to also propose to scan a QR code. Is there something like that in "HTML"?

**Comment by florian-h05** [comment]
I have already played around with QR code scanners in the browser in a little side project … so it is possible. These pairing code QR codes only contain the pairing code itself or additional data?

**Comment by florian-h05** [comment]
I have already played around with QR code scanners in the browser in a little side project … so it is possible. These pairing code QR codes only contain the pairing code itself or additional data?

**Pull request merged**
