### PR TITLE
Configuration of axis with support for expressions.

### PR DESCRIPTION
**Pull request by splatch**
Proposal to address #1418.

### CODE REVIEW

**Comment by ghys** [comment]
Nice. I see that evaluating expressions was already supported for some types of series (oh-data-series & oh-time-series) since #855 - I had forgotten about this - and you use the same trick.

Now I wonder why it can't be generalized to other types of series (aggregate & calendar & markArea) and also the rest of the components (grid, tooltip, visualMap...), most if not all have the same code or similar to initialize the options object from the config:

https://github.com/openhab/openhab-webui/blob/dd47c79b1ed18a07327f352e0710383c5df9ddce/bundles/org.openhab.ui/web/src/components/widgets/chart/misc/oh-chart-tooltip.js#L8

is to be replaced by (after adding `chartWidget`):

https://github.com/openhab/openhab-webui/blob/a525f16165d53cae57fe71ae7cab5759c3ece782/bundles/org.openhab.ui/web/src/components/widgets/chart/axis/oh-category-axis.js#L22

It would then be more logical as the user could assume every subcomponent of the chart can accept expressions instead of knowing in advance which ones have support and which ones don't.
Would you be willing to add these in this PR?

**Comment by splatch** [comment]
> Would you be willing to add these in this PR?

@ghys If it can rely on `chartWidget` method call then sure, I can update PR to cover also remaining chart elements.

**Comment by ghys** [comment]
@splatch bump - would accept this PR but also prefer to cover all chart components so it's complete.
Can provide help if needed.

**Comment by crnjan** [comment]
What is the status of this PR? IMHO it would be a nice addition ... anything I can help with?

**Comment by splatch** [comment]
@crnjan, @ghys I've rebased PR, but I am not entirely up-to-date with what charting can in 3.4/4.0.

**Comment by crnjan** [comment]
@splatch - updated your PR with some fixes and adjustments and opened a new [WIP PR](https://github.com/openhab/openhab-webui/pull/1638) ... hope it's OK with you? I can also do a PR into your repo first if you would prefer it that way? And thx for preparing your PR in the first place ...

**Comment by splatch** [comment]
@crnjan Its fine, if you have strength moving it forward, go for it!

**Comment by splatch** [comment]
Superseded by #1638.

**Pull request closed without merging**
