### PR TITLE
Enable dynamic icons only for some icon types in default list widget

### PR DESCRIPTION
**Pull request by florian-h05**
Follow-up for #1849.

### CODE REVIEW

**Comment by florian-h05** [comment]
@ghys This sets the iconUseState to true only for Item types that have a "predictable" state. For groups, the group type is checked.

**Comment by florian-h05** [comment]
@ghys 
So this is the only PR left for now that I can’t review myself, but I’ll try keeping you busy with more PRs 😉

**Review by ghys — APPROVED** [review]
Thanks! It's far better than enabling it in all cases IMO.
The added inline documentation is also very valuable so we know when these are enabled or disabled by default, and the user can make their own choice.

**Comment by lolodomo** [comment]
For everyone, it is now enabled by default only for Contact', Dimmer, Rollershutter and Switch item types.

**Pull request merged**
