### PR TITLE
[basicUI] Fix handling of buttons when only 1 button

### LINKED ISSUE #1131: [basicUI] Mappings with only one entry not correctly rendered
## Which UI are you reporting an issue for?

- [x] Basic UI
- [ ] HABPanel
- [ ] HABot
- [ ] CometVisu

## The problem

Mappings with only one entry are not correctly rendered.

My item:
```
Switch MuteAutoNoUpdate "mute (no autoupdate)" <mute> {channel="xxx"}
```
My  sitempa:
```
    Frame label="Mappings - autoupdate" {
        Switch item=MuteAutoNoUpdate
        Switch item=MuteAutoNoUpdate mappings=[ON="Muet"] 
        Switch item=MuteAutoNoUpdate mappings=[ON="Mute", OFF="Listen"] 
    }
```

The sound is muted so the item state is OFF.
Here is how it looks when I open the page:
image

The second widget (at right) is not as expected, it should be shown as "ppushed". It should be rendered similar as with the third widget.

## Expected behavior

It shoud like this when I open the page while the device is muted:
image

And like this when the device is unmuted:
image

The problem is clearly in `SwitchRenderer` where "mdl-button--accent" is not set when there is only one button !

### PR DESCRIPTION
**Pull request by lolodomo**
Fix #1131

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@kaikreuzer : could you please review this one ? It has no link with the autoupdate stuff.

**Comment by kaikreuzer** [comment]
The code that you are changing suggests that the current behavior was a very deliberate decision and not an accidental bug.
Can you make any sense out of it, why it was done this way and what its intention might have been?

**Comment by lolodomo** [comment]
> The code that you are changing suggests that the current behavior was a very deliberate decision and not an accidental bug.

I was expecting you will find that ;) I agree with you, this seems to be implemented deliberately like that.

> Can you make any sense out of it, why it was done this way and what its intention might have been?

I have strictly no idea why it was decided to not show the state of the button ! And no idea why to implement something different for 1 button versus n buttons.

**Review by kaikreuzer — APPROVED** [review]
Ok, thanks for your answer! Let's just hope that we don't overlook anything that might now break by this change...

**Pull request merged**
