### PR TITLE
added webaudio feature to HABPanel

### PR DESCRIPTION
**Pull request by kaikreuzer**
Related https://github.com/openhab/openhab-core/issues/821

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by ghys** [comment]
FYI the HABot app doesn't play audio sent to the webaudio sink.

**Comment by kaikreuzer** [comment]
Not or not yet? ;-) If it does not make sense for it, I can remove that line again.

**Comment by ghys** [comment]
Simply completely forgot about it, but it's feasible and can make sense, cannot be ported over straight from HABPanel or Paper UI though.

**Comment by kaikreuzer** [comment]
Ok, I have removed it from HABot again then.

**Pull request merged**
