### PR TITLE
Widgets: context variables, add oh-input

### PR DESCRIPTION
**Pull request by ghys**
This introduces a way to set page-local or widget-local
variables to allow more complex scenarios in pages & custom
widget development.

Variables can be used using several methods:

- the "variable" config parameter of oh-gauge (read-only),
  oh-input (new), oh-knob, oh-slider, oh-stepper, oh-toggle
  will accept a variable name and control it instead of
  sending commands to items if set. The "item" parameter can
  still be set to set the widget to the item's state, when
  the variable has no value.
- the "vars" object available in expressions (for example
  `=vars.var1` will evaluate to the value of the variable `var1`.
- the "variable" action allows to set a fixed or computed
  (using an expression) value to a variable.

Variables set directly by widgets on a page will propagate
to all components of the page, including personal widgets.
However, variables set within a personal widget will be scoped
to that personal widget only - except when there's already an
inherited variable with the same name.

oh-button & oh-link have a special parameter "clearVariable"
which allows to unset a version when clicked, after performing
the action. This is useful when "validating" a variable e.g.
send a command to an item with the variable value then reset it.

Allow oh-image to perform an action when clicked directly.

Signed-off-by: Yannick Schaus <github@schaus.net>

### CODE REVIEW

**Comment by ghys** [comment]
Some illustration on the propagation mechanism because it's not that trivial:

### YAML

```yaml
  - component: oh-block
    config:
      title: These widgets are directly in the page code and control page-level variables
    slots:
      default:
        - component: oh-grid-row
          config: {}
          slots:
            default:
              - component: oh-grid-col
                config: {}
                slots:
                  default:
                    - component: f7-block
                      config:
                        strong: true
                      slots:
                        default:
                          - component: oh-input
                            config:
                              type: time
                              item: TestString
                              color: blue
                              outline: true
                              validate: true
                              variable: alarm
                          - component: oh-button
                            config:
                              text: Set Alarm
                              color: blue
                              fill: true
                              large: true
                              class:
                                - margin-top
                              disabled: =!vars.alarm
                              action: command
                              actionItem: TestString
                              actionCommand: =vars.alarm
                              actionFeedback:
                                text: Command sent to TestString
                                icon: <i class="f7-icons">star</i>
                                position: center
                              clearVariable: alarm
                          ...
                          - component: oh-toggle
                            config:
                              variable: boolean
                          - component: Label
                            config:
                              text: =vars
  - component: oh-block
    config:
      title: These are instances of personal widgets which may have variables scoped to them
    slots:
      default:
        - component: oh-grid-row
          config: {}
          slots:
            default:
              - component: oh-grid-col
                slots:
                  default:
                    - component: widget:inputTest
              - component: oh-grid-col
                slots:
                  default:
                    - component: widget:inputTest
```

### Result


In the animation above you can see (in the JSON representations of the `vars` object) that the variables `alarm` and `number` controlled by components added directly on the page on the first block propagated to the 2 personal widgets `widget:inputTest` on the second block. However, the variables `inputText` set by the input box on the `widget:inputTest` widgets do _not_ propagate back to the page's variables.
This prevents identical widgets from interfering with each other, but still inherit the variables from the parent components. If there were an `inputText` variable defined at the page level, it will be share among the page and both `widget:inputTest` widgets.

Interesting as well is how the Set Alarm button stays disabled when the variable has not been set, and how it becomes disabled again after it's been clicked (because of the `clearVariable: alarm` parameter).

**Comment by ghys** [comment]
Example of how variables can help building a tab-like UI:

### YAML

```yaml
uid: tabs
tags: []
props: {}
component: f7-card
config:
  title: Tabs controlled by variable example
slots:
  default:
    - component: f7-card-content
      slots:
        default:
          - component: f7-segmented
            config:
              strong: true
            slots:
              default:
                - component: oh-button
                  config:
                    text: Tab 1
                    active: =!vars.tab || vars.tab === 'tab1'
                    action: variable
                    actionVariable: tab
                    actionVariableValue: tab1
                - component: oh-button
                  config:
                    text: Tab 2
                    active: =vars.tab === 'tab2'
                    action: variable
                    actionVariable: tab
                    actionVariableValue: tab2
                - component: oh-button
                  config:
                    text: Tab 3
                    active: =vars.tab === 'tab3'
                    action: variable
                    actionVariable: tab
                    actionVariableValue: tab3
          - component: oh-label-card
            config:
              label: This is tab 1
              visible: =!vars.tab || vars.tab === 'tab1'
          - component: oh-label-card
            config:
              label: This is tab 2
              visible: =vars.tab === 'tab2'
              icon: oh:lightbulb
              vertical: true
          - component: oh-label-cell
            config:
              title: This is tab 3
              item: FlowerCare_Temperature
              visible: =vars.tab === 'tab3'
              expandable: false
```

### Result

**Comment by ghys** [comment]
Complete example of a functioning keypad:

### YAML

```yaml
uid: keypad
tags: []
props:
  parameters:
    - context: item
      description: Item to send the pincode to
      label: Item
      name: item
      required: false
      type: TEXT
    - description: Replace pincode characters with this string, leave blank to show it as-is
      label: Mask character
      name: mask
      required: false
      type: TEXT
  parameterGroups: []
timestamp: Sep 26, 2020, 6:53:37 PM
component: f7-block
config:
  style:
    --f7-button-text-color: var(--f7-text-color)
    --f7-button-bg-color: var(--f7-card-bg-color)
    --f7-theme-color-rgb: var(--f7-color-blue-rgb)
  class:
    - padding
slots:
  default:
    - component: oh-label-card
      config:
        outline: true
        class:
          - margin-bottom
        label: "=(props.mask && vars.pincode) ? props.mask.repeat(vars.pincode.length || 0) : vars.pincode"
    - component: f7-row
      config:
        class:
          - margin
      slots:
        default:
          - component: f7-col
            slots:
              default:
                - component: oh-button
                  config:
                    text: "1"
                    raised: true
                    large: true
                    action: variable
                    actionVariable: pincode
                    actionVariableValue: '=(vars.pincode) ? vars.pincode + "1" : "1"'
          - component: f7-col
            slots:
              default:
                - component: oh-button
                  config:
                    text: "2"
                    raised: true
                    large: true
                    action: variable
                    actionVariable: pincode
                    actionVariableValue: '=(vars.pincode) ? vars.pincode + "2" : "2"'
          - component: f7-col
            slots:
              default:
                - component: oh-button
                  config:
                    text: "3"
                    raised: true
                    large: true
                    action: variable
                    actionVariable: pincode
                    actionVariableValue: '=(vars.pincode) ? vars.pincode + "3" : "3"'
    - component: f7-row
      config:
        class:
          - margin
      slots:
        default:
          - component: f7-col
            slots:
              default:
                - component: oh-button
                  config:
                    text: "4"
                    raised: true
                    large: true
                    action: variable
                    actionVariable: pincode
                    actionVariableValue: '=(vars.pincode) ? vars.pincode + "4" : "4"'
          - component: f7-col
            slots:
              default:
                - component: oh-button
                  config:
                    text: "5"
                    raised: true
                    large: true
                    action: variable
                    actionVariable: pincode
                    actionVariableValue: '=(vars.pincode) ? vars.pincode + "5" : "5"'
          - component: f7-col
            slots:
              default:
                - component: oh-button
                  config:
                    text: "6"
                    raised: true
                    large: true
                    action: variable
                    actionVariable: pincode
                    actionVariableValue: '=(vars.pincode) ? vars.pincode + "6" : "6"'
    - component: f7-row
      config:
        class:
          - margin
      slots:
        default:
          - component: f7-col
            slots:
              default:
                - component: oh-button
                  config:
                    text: "7"
                    raised: true
                    large: true
                    action: variable
                    actionVariable: pincode
                    actionVariableValue: '=(vars.pincode) ? vars.pincode + "7" : "7"'
          - component: f7-col
            slots:
              default:
                - component: oh-button
                  config:
                    text: "8"
                    raised: true
                    large: true
                    action: variable
                    actionVariable: pincode
                    actionVariableValue: '=(vars.pincode) ? vars.pincode + "8" : "8"'
          - component: f7-col
            slots:
              default:
                - component: oh-button
                  config:
                    text: "9"
                    raised: true
                    large: true
                    action: variable
                    actionVariable: pincode
                    actionVariableValue: '=(vars.pincode) ? vars.pincode + "9" : "9"'
    - component: f7-row
      config:
        class:
          - margin
      slots:
        default:
          - component: f7-col
            slots:
              default:
                - component: oh-button
                  config:
                    text: "*"
                    raised: true
                    large: true
                    action: variable
                    actionVariable: pincode
                    actionVariableValue: '=(vars.pincode) ? vars.pincode + "*" : "*"'
          - component: f7-col
            slots:
              default:
                - component: oh-button
                  config:
                    text: "0"
                    raised: true
                    large: true
                    action: variable
                    actionVariable: pincode
                    actionVariableValue: '=(vars.pincode) ? vars.pincode + "0" : "0"'
          - component: f7-col
            slots:
              default:
                - component: oh-button
                  config:
                    text: "#"
                    raised: true
                    large: true
                    action: variable
                    actionVariable: pincode
                    actionVariableValue: '=(vars.pincode) ? vars.pincode + "#" : "#"'
    - component: f7-row
      config:
        style:
          --f7-theme-color: var(--f7-color-blue)
          --f7-button-bg-color: transparent
        class:
          - margin
      slots:
        default:
          - component: f7-col
            slots:
              default:
                - component: oh-button
                  config:
                    text: Clear
                    large: true
                    action: variable
                    actionVariable: pincode
                    actionVariableValue: ""
          - component: f7-col
            slots:
              default:
                - component: oh-button
                  config:
                    text: Send
                    fill: true
                    large: true
                    action: command
                    disabled: =!vars.pincode
                    actionItem: =(props.item) || 'TestString'
                    actionCommand: =vars.pincode
                    clearVariable: pincode
          - component: f7-col
            slots:
              default:
                - component: oh-button
                  config:
                    text: Back
                    large: true
                    action: variable
                    actionVariable: pincode
                    actionVariableValue: '=(vars.pincode) ? vars.pincode.substring(0, vars.pincode.length - 1) : ""'
```

### Result

chrome_2020-09-26_19-33-33

Works best in a target modal of a `popup` action:

**Comment by digitaldan** [comment]
Hi @ghys this looks super awesome, are there plans on creating official text entry and tab cards?  or this expected to be used in community contributed widgets?

**Comment by digitaldan** [comment]
and btw, i'm totally coping and pasting that keypad for my alarm panel interface !

**Comment by ghys** [comment]
> are there plans on creating official text entry and tab cards? or this expected to be used in community contributed widgets?

For now I think I'll keep a "let's provide all the tools and see what comes up" approach, as well as providing examples of what you can do by yourself with some YAML; if there's a clear need that some designs could benefit from easier built-in support it's never out of the question.

**Comment by hmerk** [comment]
@ghys Is there a way to automatically close the keypad after/with pressing send?

**Comment by hmerk** [comment]
@ghys Forget about my last question, found it myself.
simply adding a 
`popup-close: true`
after 
`clearVariable: pincode`
at Enter key definition solved it.
Like @digitaldan , I will use it to secure my alarm panel...
👍

**Comment by ghys** [comment]
Glad you found it yourself! As you likely have figured out, `oh-button` is based on `f7-button` and its config is passed to the underlying `f7-button`. I'll try to come with a way to specify that in the widget descriptions so that parameters are inherited and that fact is taken into account for instance during autocompletion - right now it isn't.

image
image


You can also use the `popupClose: true` notation, it's equivalent.
A third way would have been to add the [`popup-close` CSS class](https://framework7.io/docs/popup.html#control-popup-with-links) to the button, you can do that too (but it's better to use props when they exist).
```
config:
  ...
  class:
    - popup-close
```

**Comment by rgrollfitz** [comment]
Thanks again for your work @ghys 

I tried to test the new input and variable mechanics with an SMS-widget - it works in general but there are 2 things I can't get solved which would make it even more usable in real-life.

image

I created 2 exec items (one for executing the script and the other one for the variable inputs [phone number & message text] I need)

By clicking the "Send" button, the exec item-switch receives the `actionCommand: ON` and tries to use the variables (stored in the input item) to send out the given message to the respective recipient.

As you see, I had to implement another "dummy button" to send the variables I grabbed from the input fields to the input item itself. There seems to be no option, to set these values with the "Send" button, as there is already another actionItem and actionCommand assigned.

**1. Is it possible to assign multiple actionItems and actionCommands to a single component (e.g. a button)? Or maybe theres a way to send the vars directly to an item without clicking anything? (oh-input at least seems to not support actionCommands as far as I can see)**

**2. Another handy feature would be to use "clearVariable" for multiple input-components. Expressions does not seem to work here?!**

Here is a part of the YAML structure - maybe it helps, to illustrate my challenge a bit better:
```
          - component: oh-button
            config:
              fill: true
              large: true
              color: orange
              class:
                - margin-top
              disabled: =!vars.message || !vars.number
              action: command
              actionItem: sendSMS
              actionCommand: ON
              actionFeedback:
                text: ='SMS was sent to ' + vars.number
                icon: <i class="f7-icons">envelope</i>
                position: center
              text: Send
              clearVariable: message
              popupClose: true
          - component: oh-input
            config:
              type: text
              value: '="\"" + vars.number + "\" \"" + vars.message + "\""'
          - component: oh-button
            config:
              text: "Set!"
              action: command
              actionItem: varSMS
              actionCommand: '="\"" + vars.number + "\" \"" + vars.message + "\""'

```

Thank you!

**Pull request merged**
