### PR TITLE
[BasicUI] Fix character encoding of returned page

### LINKED ISSUE #2681: [BasicUI] Wrong encoding of translated strings
Which UI are you reporting an issue for?

- [x] Basic UI
- [ ] HABPanel
- [ ] HABot
- [ ] CometVisu

## The problem

My Phone, and thus Firefox, is configured to prefer Bulgarian language in content. As can been from the screnshot of BasicUI’s 4.2 settings, the translated sentences are not displayed properly.

Screenshot_20240721_093320_org mozilla firefox

### PR DESCRIPTION
**Pull request by lolodomo**
Fix #2681

Concerns only the settings page and the page listing all sitemaps

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Review by wborn — COMMENTED** [review]
Nice to see it fixed. :+1: +1:
Maybe also update the `ManifestServlet` similarly?

**Comment by lolodomo** [comment]
> Maybe also update the `ManifestServlet` similarly?

Oh yes

**Comment by lolodomo** [comment]
Done

**Review by wborn — APPROVED** [review]
LGTM! Might also be an idea to check other add-ons for similar issues.

**Comment by lolodomo** [comment]
For the full explanation, `res.setContentType` with `text/html;charset=UTF-8` as parameter is also setting the character encoding which is then considered when calling `res.getWriter()`.
When`res.setContentType` was not first called, `res.getWriter()` was considering the default charset "iso-8859-1".

**Comment by dilyanpalauzov** [comment]
Where does charset=ISO-8959-1/Latin-1 come from?  Can that place be enforced to send UTF-8 instead?  Then there will be no need to set explicitly UTF-8 on many places.

**Comment by lolodomo** [comment]
After the merge, I will cherry-pick this fix in 4.2.x.

**Comment by lolodomo** [comment]
> Where does charset=ISO-8959-1/Latin-1 come from? Can that place be enforced to send UTF-8 instead? Then there will be no need to set explicitly UTF-8 on many places.

I just explained it in my previous message.
It is the behaviour defined by javax.servlet.ServletResponse

**Comment by dilyanpalauzov** [comment]
> After the merge, I will cherry-pick this fix in 4.2.x.

I do not know where is discussed what to backport, but I propose also https://github.com/openhab/openhab-core/pull/4312 for including in 4.2.x.

**Comment by florian-h05** [comment]
> I do not know where is discussed what to backport, but I propose also https://github.com/openhab/openhab-core/pull/4312 for including in 4.2.x.

This is usually discussed inside the PR, and in case of your linked PR it seems it is already backported.

**Comment by lolodomo** [comment]
> but I propose also https://github.com/openhab/openhab-core/pull/4312 for including in 4.2.x.

It was back-ported and should be available in 4.2.1.

**Comment by dilyanpalauzov** [comment]
> > but I propose also [openhab/openhab-core#4312](https://github.com/openhab/openhab-core/pull/4312) for including in 4.2.x.
> 
> It was back-ported and should be available in 4.2.1.

Ah, it is in https://github.com/kaikreuzer/openhab-core/commits/4.2.x/ .  I have not found it at https://github.com/openhab/openhab-core/commits/4.2.x/ .

**Comment by lolodomo** [comment]
You just have it included in the release notes of 4.2.1:
https://github.com/openhab/openhab-distro/releases/tag/4.2.1

**Comment by lolodomo** [comment]
> LGTM! Might also be an idea to check other add-ons for similar issues.

I have done a quick check in addons repository (30 files) and most of the time a character encoding is set before calling `response.getWriter()`. It can happen it is not set before but maybe the developer knows in that case that iso-8859-1 is an appropriate default character encoding ? I see it not set especially in the cases of XML or JSON responses.

**Comment by wborn** [comment]
> Ah, it is in https://github.com/kaikreuzer/openhab-core/commits/4.2.x/ . I have not found it at https://github.com/openhab/openhab-core/commits/4.2.x/ .

Thanks for noticing!
Looks like several others were missing too so I've cherry-picked those as well and removed them from the release notes.

**Review by kaikreuzer — APPROVED** [review]
Sure thing - thanks!

**Comment by lsiepel** [comment]
> After the merge, I will cherry-pick this fix in 4.2.x.

^^

**Comment by lolodomo** [comment]
Backported to branch 4.2.x.

**Pull request merged**
