### PR TITLE
Update oh-repeater.md

### PR DESCRIPTION
**Pull request by jossuar**
Corrected display issue due to nested double quotes

Signed-off-by: Georgios Moutsos <georgios.moutsos@gmail.com>

### CODE REVIEW

**Comment by jossuar** [comment]
Please ignore the DCO check.
I have this repo probably not correctly setup.

**Comment by ghys** [comment]
Thanks, but it needs to be changed at the source or it will be overwritten when the generate script runs again.
(or the script should take these into account and escape/replace the quotes properly).

**Comment by jossuar** [comment]
Can you point me to the generation script? (and i will close this pull request)

**Comment by ghys** [comment]
> Can you point me to the generation script? (and i will close this pull request)

Yes, sorry - the generation script is here: https://github.com/openhab/openhab-webui/blob/main/bundles/org.openhab.ui/doc/components/src/generate.js

This is the problematic line:
https://github.com/openhab/openhab-webui/blob/dd0472f0a509de61a750282603ff09cbd3bdc549/bundles/org.openhab.ui/doc/components/src/generate.js#L64

but there might be some others as well. Double quotes should be escaped in any case when there's concanated like this.

Another alternative is to simply get rid of the double quotes in the oh-repeater case at the source which is here:
https://github.com/openhab/openhab-webui/blob/dd0472f0a509de61a750282603ff09cbd3bdc549/bundles/org.openhab.ui/web/src/assets/definitions/widgets/system/repeater.js#L7-L14

If you match the docs Markdown file with these config parameters, even if you don't run the generator script, I believe this could be merged alright.

**Pull request closed without merging**
