### PR TITLE
Setup wizard: Add separate step for persistence

### PR DESCRIPTION
**Pull request by mherwege**
There has been quite a bit of discussion lately on improving the first installation experience.

This has been reflected in https://github.com/openhab/openhab-core/issues/4103 and https://community.openhab.org/t/ideas-for-new-openhab-installation-experience/154042/43?u=mherwege

This PR addresses two of the topics discussed:
- Include Mapdb as a proposal for a persistence service to install
- Include Astro in the recommended addons at initial install
It starts from the premise that the list of recommended addons is maintained (as before) in the webui repository (and not in a 'always suggest' suggestion finder).

The PR creates the groundwork to implement more fine grained suggestions in the setup wizard. It allows having separate steps for types of addons or specific addons. It also makes it possible to have extra text for identified addons as part of the setup wizard.
At the moment, only persistence is split out in a separate step (and no persistence will be offered in the main wizard addon selection window anymore).
This could be enhance to other types or recommendations in the future, but I want to start this small.

Addon selection now also allows unselecting addons on the shown list, without branching out to a separate window. That is still possible to add addons not in the original lists.

@florian-h05 I use the addon logo component as implemented in https://github.com/openhab/openhab-webui/pull/2402 in this PR, but none of the logos load. Can you help me understand why?

Here are some screenshots to show how it looks like with this PR:

image

image

image

image

@andrewfg @jimtng I would appreciate your feedback on this.

### CODE REVIEW

**Comment by andrewfg** [comment]
> @andrewfg .. I would appreciate your feedback on this.

@mherwege this is an excellent idea. I haven’t tested it on a real system, and I haven’t proofed your code. But conceptually it is a big improvement over prior. And certainly better than an always install addon finder. Thanks for this. .. Just one question though: you did want to do something about country specific addons, so I wonder how that would fit in this concept?

**Comment by mherwege** [comment]
> you did want to do something about country specific addons

I am not sure about the best approach for that just yet.

I see 3 classifications for addons:
1. recommended: fixed list, only presented in setup wizard (list maintained in webui code)
2. suggested: comes from core, mainly based on environment scans, but could be other - presented in setup wizard and addon store
3. featured: fixed list, only presented in addon store and on website (separate list for addon store and website maintained in addon store and webui respectively)

1 and 3 are maintained in code in the webui. 2 is maintained by the binding developer.

Region and country could fit in 1 or 2, but at the moment I am tempted to go 2 for it. It shouldn't be a list maintained by the maintainers, but should be suggested from the binding metadata.

**Comment by jimtng** [comment]
image 

It would be great if the addon description can be displayed here

**Comment by mherwege** [comment]
> It would be great if the addon description can be displayed here

Fully agree, but I am afraid there is none. The description on the persistence selection page is hand crafted in the webui code. And if that is available, it will default to it. What it is showing here is what was shown before.
From the addon info, I only have a label, no longer description.

**Comment by mherwege** [comment]
> The `description` field does exist in the addon REST response, but is not populated. I will see if I can find what the issue is.

The `description` field is only populated after installation. This was introduced to solve an issue with localisation of the label and description before installation in https://github.com/openhab/openhab-core/pull/3908

**Comment by florian-h05** [comment]
I’ll have a look at the add-on logos soon. 👍

Probably the setup wizard should open the quick start guide after finishing?

**Comment by mherwege** [comment]
> Probably the setup wizard should open the quick start guide after finishing?

Done and fine on wider screens. I am unhappy about the link for smaller screens, but that is a documentation issue.

**Comment by mherwege** [comment]
DCO fails because of revert commit.

**Comment by florian-h05** [comment]
@mherwege I guess you have seen my PR to the add-on logo component? 
Please refrain from changing this PR, as I am currently reviewing it and also improving styling here and there a bit.

**Comment by florian-h05** [comment]
@mherwege Can you please put the primary IP address config into a follow-up PR?

**Comment by florian-h05** [comment]
@mherwege I have created https://github.com/mherwege/openhab-webui/pull/3 to your branch, please merge it using rebase merge.

My add-on logo component was not working because it only supported lazy loading, I have updated the component to make lazy loading optional. Theoretically you need to rebase this PR, however please don't do, I don't want to re-apply the changes from my PR. Once I merge this PR here, the icons will work properly in the main branch.

**Comment by mherwege** [comment]
> @mherwege Can you please put the primary IP address config into a follow-up PR?

Sorry, I missed this and pushed something. I will revert abnd put it in a separate PR.

**Comment by florian-h05** [comment]
Thanks.
In case it is based on this PR, just wait with the new PR until I merge this one. Once you have a look at my PR (linked above) and merge into this branch here, I will merge.

**Comment by mherwege** [comment]
OK, I hope I have done things right. I merged your PR from the github web UI.

**Review by florian-h05 — APPROVED** [review]
LGTM, thanks!
Looks really nice with the add-on logos now.

FYI some change from my PR got lost somehow, I just re-applied it :+1:

**Pull request merged**
