### PR TITLE
Add null annotations to REST resources

### PR DESCRIPTION
**Pull request by wborn**
Depends on https://github.com/openhab/openhab-core/pull/1475.

There were still missing whiteboard annotations on `HABPanelResource` which are also added.

### CODE REVIEW

**Comment by wborn** [comment]
I've removed required from PathParams because they are always required:

```
    /**
     * Specifies if the parameter is required or not.
     * <p>
     * Path parameters will always be set as required, whether you set this property or not.
     */
    boolean required() default false;
```

**Comment by wborn** [comment]
I also have a question for you @ghys:

The language HeaderParams in HABotResource seem to be currently ignored.

https://github.com/openhab/openhab-webui/blob/586cea4444684c5c1e1f78a9c9e8c5bb9ad899b8/bundles/org.openhab.ui.habot/src/main/java/org/openhab/ui/habot/rest/internal/HABotResource.java#L125-L127

Is that because it still has to be implemented in the UI before it can be used?

**Comment by ghys** [comment]
> The language HeaderParams in HABotResource seem to be currently ignored.

Yes I intended to use it at first, the browser's configuration would define the language, but it was impractical - some browsers would be set up in a unsupported language, or some would be in English and other in another language, forcing a retraining on each change... In the end it was more logical to use the locale defined in openHAB's i18n service, so this parameter can be removed.

**Comment by wborn** [comment]
I already thought so and will then remove it before someone will create an issue that it doesn't work. :wink:

**Comment by ghys** [comment]
Great, be my guest ;)

**Comment by ghys** [comment]
Thanks!

**Pull request merged**
