### PR TITLE
make webui work with non-root context path (#1290)

### PR DESCRIPTION
**Pull request by altaroca**
See explanation in in the issue openhab/openhab-webui#1290

things to consider:
- testing for this will be difficult as it changes some logic at the heart of the ui. 
- testing needed for different browsers, uis, mobile apps. I have only used the main ui in chrome.
- rest oauth will not work at non-root url. disable using `console> bundle:stop org.openhab.core.io.rest.auth`
- this does not fix all absolute urls in the uis. Apache2 reverse proxy as in openhab/openhab-core#150 can take care of many of those
- in time it would probably be good to fix all urls

### CODE REVIEW

**Comment by hubsif** [comment]
Hi @altaroca,
FYI: I started looking into this and thank's to your work I really think this is doable (wouldn't have thought so a short while ago)! I refined and simplified a few things regarding the UI and will continue trying to solve open issues.

**Comment by ghys** [comment]
@altaroca - thanks for this effort!
I have yet to test this properly, give me a few days, but it's looking good already.
However please note the contributing rules regarding signing off of your commits: https://github.com/openhab/openhab-core/blob/main/CONTRIBUTING.md#sign-your-work
If you add the requested sign-off line as a comment in this discussion (`Signed-off-by: ...`) I will merge the PR with this line included.

**Comment by altaroca** [comment]
Great! I am happy if you think this works. As for merging I leave it up to you @ghys if you want to merge it as is or wait for a more complete solution by @hubsif. In any case I sign over any copyright I may own on this PR to you. You don't have to mention me. Too much paperwork 😃

**Comment by florian-h05** [comment]
Closing as this went stale.

**Pull request closed without merging**
