### PR TITLE
[blockly] Add renderer switching

### PR DESCRIPTION
**Pull request by jimtng**
This adds a little button on the bottom of blockly workspace to allow switching the renderer on the fly. The choice is saved in `localStorage`.

This depends on #2310 

image
image

### CODE REVIEW

**Review by stefan-hoehn — COMMENTED** [review]
I think I found a new Blockly Contributor ;-)
Great that we can chose the renderer now. Is "geras" still the default one?

Are these breaking changes for 9.2 > 10.3:
.forBlock
.icons.MutatorIcon
.utils.xml

Did you check all of these here?
https://github.com/google/blockly/releases/tag/blockly-v10.0.0 

Otherwise the PR looks straight forward. The only downside is that I have QA each and every block which probably need some time. 

@florian-h05 Do you mind having a look at the code as well. 
...I will do the QA for all the blocks eventually.

**Comment by jimtng** [comment]
> I think I found a new Blockly Contributor ;-)

It's just a spurt. I don't use blockly or the UI much, but I think these are nice improvements.

> Great that we can chose the renderer now. Is "geras" still the default one?
> 

The default is not giving any instructions for the renderer, just like it was before, and therefore the default is the same as before. In this case, Geras, but that's not defined by this pr or at least I hope not.

> Are these breaking changes for 9.2 > 10.3:
> .forBlock
> .icons.MutatorIcon
> .utils.xml
> 

Those are what's needed to make the project to compile. It seems to work fine

 
> Did you check all of these here?
> https://github.com/google/blockly/releases/tag/blockly-v10.0.0 
> 

No, I haven't 

> Otherwise the PR looks straight forward. 

See the separate pr for blockly upgrade. Once that's merged, I'll rebase this one to contain only the renderer switching changes/commit.

> The only downside is that I have QA each and every block which probably need some time. 

Is there currently no automated tests?

**Comment by stefan-hoehn** [comment]
No, automated tests have not been done. I never had the time to work on this and even haven't checked how it can be done, in particular with openHAB blocks.

**Comment by jimtng** [comment]
> No, automated tests have not been done.

Could you tell me how the tests are currently done?

**Comment by stefan-hoehn** [comment]
Sure, there is a folder 
image

which I created when I originally converted all blocks from Nashorn to GraalJS. You can copy the XML to the code area of a new Blockly rule and there is an image that depicts how the rule is supposed to look like. But surely you then also need some "virtual" or real items on your installation.

To my own regret, I haven't taken the time to update it regularly. I have it installed on my test system and would probably go through it and update it as needed.

**Comment by jimtng** [comment]
Rebased against main.

**Comment by jimtng** [comment]
rebased against the current v10.4.1 branch

**Comment by stefan-hoehn** [comment]
@jimtng Do you know why this PR has conflicts. Can you do me a favor and check that on your side because I intend to start testing it now.

**Comment by stefan-hoehn** [comment]
@jimtng Please rebase so I can start testing this.

**Comment by jimtng** [comment]
rebased

**Comment by stefan-hoehn** [comment]
First tests look promising... I keep you posted.

**Comment by stefan-hoehn** [comment]
### Samples

Note to myself that the documentation needs to be updated:
image


**geras**
is the standard renderer for openHAB
image

**thrasos**
is a bit more tighter and the labels are more centered (see the "if" compared to _geras_). It is supposed to be a more modern take on the legacy _geras_ renderer.

image

**zelos**
 emulates Scratch-style and MakeCode-style rendering.
image

### For reference:

- The _minimalist_ renderer has been taken out as [it will deleted in blockly 11](https://developers.google.com/blockly/reference/js/blockly.minimalist_namespace.renderer_class.md)

**Review by stefan-hoehn — APPROVED** [review]
Thanks for the contribution, Jim. From all what I can see it works fine.
@florian-h05 you can merge it

**Review by florian-h05 — CHANGES_REQUESTED** [review]
Looks good, apart from a one thing:

57b6c3fd-5a0e-4ad1-bfe6-2439c797cc52

The bottom bar looks very crowded now.
Can you please update the Blockly editor to only show the shortcut keys when on desktop (like for rule editor, etc)?

Code looks something like:

`Save<span v-if="$device.desktop">&nbsp;(Ctrl-S)`

**Comment by jimtng** [comment]
> Can you please update the Blockly editor to only show the shortcut keys when on desktop (like for rule editor, etc)?
> 
> Code looks something like:
> 
> `Save<span v-if="$device.desktop">&nbsp;(Ctrl-S)`

This was already implemented before this PR. You need to refresh the browser with the mobile setting in order for it to detect it as such.

image

image

**Review by florian-h05 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
