### PR TITLE
Allow building most bundles on Apple Silicon processors and upgrade tooling.

### PR DESCRIPTION
**Pull request by J-N-K**
Follow-Up to #1215 (can't be re-opened for unknown reasons).

### CODE REVIEW

**Comment by J-N-K** [comment]
Trying to figure out if it's HaBOT related

**Comment by J-N-K** [comment]
@ghys How so we proceed here? Shall I remove the upgrade for habot? As I said before, unfortunately I don‘t have enough knowledge to upgrade the dependencies that block the beide upgrade.

**Comment by ghys** [comment]
Right, let's abandon the harmonization of versions and let's keep the HABot build on node v12 then, at least for now.

**Comment by ghys** [comment]
Thanks! LGTM.
One last thing (if you don't mind!), @wborn made 2 pertinent remarks https://github.com/openhab/openhab-webui/pull/1352#pullrequestreview-941885004 & https://github.com/openhab/openhab-webui/pull/1352#pullrequestreview-941923637. Could you address them?

**Comment by J-N-K** [comment]
Sure.

**Pull request merged**
