### PR TITLE
Update bnd to 5.2.0

### PR DESCRIPTION
**Pull request by wborn**
See: https://github.com/bndtools/bnd/wiki/Changes-in-5.2.0

---

Related to https://github.com/openhab/openhab-core/pull/2105

### CODE REVIEW

**Review by ghys — APPROVED** [review]
Since it was approved in core, I'll go ahead :)

**Comment by ghys** [comment]
@wborn @kaikreuzer should this be cherry-picked for 3.0.x?

**Comment by wborn** [comment]
It doesn't immediately fix end user issues, so I don't think it is useful to be cherry picked.

**Comment by kaikreuzer** [comment]
I agree with @wborn.

**Comment by ghys** [comment]
Ok - though in case a dependency upgrade aims at fixing a vulnerability and has low risk of breaking, like #761, I'd tend to include it in patch releases.

**Pull request merged**
