### PR TITLE
[BasicUI] Show buttons on several lines when not enough place

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
With this change:

image


Before this change:

image

**Comment by jimtng** [comment]
The android app solved this more elegantly

**Comment by lolodomo** [comment]
Question of taste. I prefer to have all buttons (and variable button width) and only one click for user.
I don't say Android app choice is wrong. By the way, I don't think I can implement it that way easily and responsively with HTML/CSS.

**Comment by lolodomo** [comment]
I propose to merge my solution as a fast fix of one of the most annoying issues in Basic UI.

Later if someone proposes a PR with a better solution, it can be of course reviewed.

**Comment by jimtng** [comment]
> I propose to merge my solution as a fast fix of one of the most annoying issues in Basic UI.
> 
> Later if someone proposes a PR with a more elegant solution, it can be of course reviewed.

That sounds like a plan

**Review by kaikreuzer — APPROVED** [review]
Fine for me, thanks.

**Pull request merged**
