### PR TITLE
[WIP/RfC] Developer Sidebar

### PR DESCRIPTION
**Pull request by ghys**
This is a proposal of a "developer sidebar" to provide a collection of handy,
always-available tools while heavily working on the configuration.
I'm opening the PR early to gauge interest and allow suggestions on
the features this tool should have.

The developer sidebar is displayed on the right side of the view, outside
the standard page navigation, and available from the developer tools
menu or at any time with the <code>Shift+Alt+D</code> keyboard shortcut, __only__ if
all of these conditions are met:

1. the user has an administrator role;
2. the device is a desktop (or laptop, that is, not a phone or tablet);
3. the width of the screen is >= 1280px.

Example:

Only the "Item Monitor" and "Events Monitor" tools are (barely) functional
for now, the rest are mockups.
Ideas of tools to include in the sidebar are:
- Search bar to perform a global search among items, things, pages, rules and
quickly navigate to its page (suggested in #224)
- Item monitor: select the items you currently are working on, and show their
states in real time, eventually update their states or send commands, using a
raw input or the standard list control, quickly go edit them;
- Rules monitor: add rules you're currently working on or those you need at
the moment, check their status, disable/enable them, run them, or quickly
go edit them:
- Things monitor: add things you're currently working on or those you need at
the moment, check their status, disable/enable them, or quickly go edit them:
- Events monitor: Stream the events from the event bus, eventually apply
filters;
- Pages (& widgets): add pages or widgets you're currently working on or
those you need at the moment, view them in a popup or navigate, or quickly
go edit them:
- Widget expression tester: Quickly type an expression like in a config parameter
of a widget and check the result;
- ...Other tools (add items etc.?), maybe offer additional tools depending on
the add-ons installed - for example a basic MQTT or HTTP client...

Note: the developer sidebar is resizable! (unlike the menu on the left)

Signed-off-by: Yannick Schaus <github@schaus.net>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Awesome idea, I like it! I guess your list of ideas for its features is already long, I don't have anything else right now, I'd want to add. Item/Thing/Event monitor are probably the most important ones for binding developers.

**Comment by ghys** [comment]
Another tool idea:

A "Script Scratchpad" button that lets choose a script language (Rule DSL, JS, Groovy...) from the automation rule engines installed ("language" config parameter option of the ScriptAction module type), then opens an editor.

You can run the script as often as you like, with a Run button in the popup or the Ctrl+R keyboard shortcut, like in the regular rule editing page. It saves the script to the temporary rule and runs it. The first time you run the script it creates a temporary rule with a ScriptAction, afterwards it simply updates that rule, then runs it.

When you exit the scratchpad it offers to save the temporary rule, otherwise it removes it.

It's a nice way of quickly running some code (it's a "developer" sidebar after all) without going through the hassle of creating a rule, adding the script action module, and editing the script.

**Comment by ghys** [comment]
Enjoy - to recap:
Shift+Alt+D on the keyboard or in the developer tools menu
Works only for admins, and screens large enough, 1280 pixels or wider.
Closes #224.

**Comment by fxpde** [comment]
The new developer sidebar is great. Unfortunately, it does not show when using Safari on macOS. The user agent shows as "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15". When using Chrome on the same machine, it works just fine.

**Pull request merged**
