### PR TITLE
Update descriptions in the settings menu

### PR DESCRIPTION
**Pull request by ghys**
I thought these labels could be improved and those describe the relevant sections better IMO, getting more to the point. Native English speakers, please confirm and review!

### CODE REVIEW

**Comment by ghys** [comment]
Btw, we have to check why the bundle metrics are like:

  | CurrentJob #1349 | BaselineJob #1158
-- | -- | --
Initial JS | 1.9MiB(+13.82%) | 1.67MiB

I think the baseline hasn't changed since #2063.
@vio could you confirm and tell us how to update it with every PR?

In any case 300kB more initial JS is a lot in 4 months; we'll have to investigate why it happened.

**Comment by vio** [comment]
@ghys the baseline is the latest job in the default branch at the time of the build. Looks like your latest job in the default branch (`main`) was processed on `16/09/2023 16:28:44`: https://app.relative-ci.com/projects/ZNG5hy4VeSJQVQcq1Kvu/tree/main.  

The `Main UI` workflow runs only on `pull-request` and on `workflow_dispatch`, so the push to `main` is ignored atm. To run the workflow and send the latest from `main`, you need to trigger the workflow manually or update the workflow to build and send the data on `push` for the `main` branch

```suggestion
+  push:
+    branches: [ main ]
+    paths: bundles/org.openhab.ui/web/**
+
   pull_request:
-    branches: [ main ]
     paths: bundles/org.openhab.ui/web/**

  workflow_dispatch:
```

**Comment by florian-h05** [comment]
@vio Thx for pointing out what to do.
I have now triggered a manual run, then triggered a re-run of the Main UI action on this PR and the bundle stats look fine again. I will update the workflow file in #2278.

@ghys I have tried to find out what caused the initial CS bundle-size increase, and it is not easy to find out the cause from checking the RelativeCI history, but it seems that #2088 at least lead to some increase. #2253 will help with that.

**Review by florian-h05 — APPROVED** [review]
LGTM, thanks!
But I am no native English speaker, so let's ping one @rkoshak.

**Comment by JustinGeorgi** [comment]
The english all looks just fine.

**Pull request merged**
