### PR TITLE
Activation of additional ESLint rules

### PR DESCRIPTION
**Pull request by philippwaller**
This PR activates the following ESLint rules and provides the necessary code changes:
- indent
- no-trailing-spaces
- quotes
- vue/html-indent
- vue/html-quotes
- vue/no-multi-spaces

### CODE REVIEW

**Review by ghys — APPROVED** [review]
Awesome, thanks!

**Comment by philippwaller** [comment]
@ghys: Thanks for the review. The next batch is on its way. I guess we need to rebuild the pending PR's to identify ESLint errors.

**Comment by ghys** [comment]
You're right. In the end I think it would be a good thing to make Prettier run as well (possibly on save in dev mode too).

**Comment by philippwaller** [comment]
> I think it would be a good thing to make Prettier run as well (possibly on save in dev mode too).

Sounds good. I will take care of it after the next ESLint PR is merged.

**Pull request merged**
