### PR TITLE
[BasicUI] Fix image element being link to a sub page

### LINKED ISSUE #2233: [BasicUI] Problem with image element being root of another page => no access to the sub page
Updated yesterday to last version openhab (4.1.0-1) from earlier Version 4.0.x i believe.

I have a Subpage could be entered with an Image item worked before, now breaking the sitemap.

Here an example (be aware, you need an imageitem, an item called Empty (String in my case) and a group for testing:
```
sitemap Home2 label="Home Sweet Home" {
    Frame label="Unser Zuhause" {
        Text label="Subpage ok" 			item=Empty {
            Frame label="Sub 1 Frame ok" {
                Default label="Item ok" 			item=Empty 
            }
        }
        Group label="Group ok"				item=gList
        Text label="Grafik (Work around)"						item=owmCurrentConditionIcon {
            Frame label="Sub 2 Frame ok" {
                Default label="Item ok" 			item=Empty 
            }
        }
        Image label="Grafik"								item=owmCurrentConditionIcon {
            Frame label="Sub 3 Frame Broken" {
                Default label="Item never seen" 			item=Empty 
            }
        }
        Text label="Subpage Click not working because of ealier image" 			item=Empty {
            Frame label="Sub 4 Frame never seen" {
                Default label="Item never seen" 			item=Empty 
            }
        }
    }
}
```

### PR DESCRIPTION
**Pull request by lolodomo**
Fix #2233

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
This fix should also be back-ported to 4.1.x.

**Comment by lolodomo** [comment]
@kaikreuzer : gentile ping, this is something to provide in a 4.1 patch relatively soon.

**Review by kaikreuzer — APPROVED** [review]
Thanks!

**Comment by kaikreuzer** [comment]
Cherry-picked to `4.1.x`

**Pull request merged**
