### PR TITLE
Remember checkbox settings in model picker popup

### PR DESCRIPTION
**Pull request by jimtng**
Remember these checkboxes so they don't need to be re-checked every time

image

### CODE REVIEW

**Review by florian-h05 — APPROVED** [review]
Better to use `$f7.data` instead - I've already commited this.

Thanks!

**Comment by florian-h05** [comment]
@jimtng Do you think this is useful for the model page as well?

**Comment by jimtng** [comment]
For "Show name" and "Show tags", yes. 

For "Show non-semantic", I'm not so sure. The "Model" page is supposed to show the semantic stuff. Having it show non-semantic by default (because of the stored option) would feel weird, but perhaps if that's what the user wants, then so be it?

**Comment by florian-h05** [comment]
Clearly agreed on show name and show tags. 

"Show non-semantic" tags is difficult, and the argument that it is supposed to show semantic stuff is a good point.
But ff the two other settings remember their state, "Show non-semantic" not doing that might be considered as bug by most users.

**Comment by florian-h05** [comment]
Not sure if you've seen #2355. 
I will partly revert changes from #2355 and #2349 to make the "show non-semantic" checkbox non-persistent.

**Comment by jimtng** [comment]
IMO the item pickers show non semantics and the other check boxes should be persistent. I wish such things can be done in such a way that it can be made persistent for those who want it so and not persistent for the rest if that's what they prefer.

I don't understand why one would want it to be non persistent.

I agree that show non semantics in the model view stays off by default. In fact it probably shouldn't even be there.

**Comment by florian-h05** [comment]
FYI when using the item picker, the button on the left wirh the menu items icon opens the model picker and a click on the rest of the item picker opens the normal, non-model item picker.
IMO we don’t need to store the non-semantic option if the model picker, as for non-semantic items you should simply use the normal item picker.

**Comment by jimtng** [comment]
> FYI when using the item picker, the button on the left wirh the menu items icon opens the model picker and a click on the rest of the item picker opens the normal, non-model item picker. 

I am aware of this, but the model picker is what pops up when you're adding a new rule module. The choice of the normal item picker is only available after that.

**Comment by jimtng** [comment]
Also, blockly only uses the model picker to select items.

**Comment by florian-h05** [comment]
True, but it is not really consistent to have different behavious between the model picker and the model page.

@ghys WDYT? Do you have an idea how to solve that?

**Pull request merged**
