### PR TITLE
Skip Paper UI Karma tests

### PR DESCRIPTION
**Pull request by ghys**
Attempt to make the 2.x build work again.

Signed-off-by: Yannick Schaus <github@schaus.net>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Seems to work, thanks!

**Comment by kaikreuzer** [comment]
@ghys Any further idea what to do about https://ci.openhab.org/view/Sandbox/job/sandbox-openhab2-release/1770/console?

**Comment by wborn** [comment]
It could have a point because /var/jenkins is used for 98%:

```
[ERROR] npm ERR! nospc ENOSPC: no space left on device, write
[ERROR] npm ERR! nospc There appears to be insufficient space on your system to finish.
[ERROR] npm ERR! nospc Clear up some disk space and try again.
```

**Comment by ghys** [comment]
> @ghys Any further idea what to do about https://ci.openhab.org/view/Sandbox/job/sandbox-openhab2-release/1770/console?

Freeing up some space maybe? :) It's not the same error as before.

**Comment by kaikreuzer** [comment]
Hm, good point, it seems I didn't look close enough:
```
/dev/vdc        95597404 88437420   2260788  98% /var/jenkins
```
This indeed does not look too good. Will have a look what can be cleaned...

**Pull request merged**
