### PR TITLE
[BasicUI] Upgrade node/npm/gulp/node-sass tools

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@florian-h05 for information. This PR replaces #2606.

**Comment by lolodomo** [comment]
I removed the package-lock.json and it was recreated. Maybe a wrong idea.

**Comment by lolodomo** [comment]
Ok, done again without removing package-lock.json.

**Comment by lolodomo** [comment]
We have 3 PRs updating package-lock.json so we have to take care, merge one by one and update the file between each merge.

**Comment by florian-h05** [comment]
@lolodomo Can you please rebase and fix the conflicts?

**Comment by lolodomo** [comment]
> @lolodomo Can you please rebase and fix the conflicts?

Done

**Comment by lolodomo** [comment]
@florian-h05 : can you merge please ?

**Comment by florian-h05** [comment]
I will take a look today and merge afterwards 👍

**Review by florian-h05 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
