### PR TITLE
Support configuring Input element for sitemap model

### PR DESCRIPTION
**Pull request by mherwege**
https://github.com/openhab/openhab-core/pull/3398 added an Input element to sitemaps.
A PR for BasicUI to support input elements is in progress (https://github.com/openhab/openhab-webui/pull/1729).

### CODE REVIEW

**Review by florian-h05 — APPROVED** [review]
LGTM, thanks!

Should I merge now or do you prefer waiting for #1729 to get merged?

**Comment by mherwege** [comment]
Configuring it is already supported in text files, although no UI can use it yet. So I don’t think we have to wait for merging this. I am hopeful BasicUI will support it soon.

**Comment by ghys** [comment]
I'm late here but it might "unbalance" this popup here:
image

Maybe we can remove "List", what do those even do?

**Comment by florian-h05** [comment]
> I'm late to this party but it might "unbalance" this popup here:

It indeed does, but I don't see a problem in this fact.

> Maybe we can remove "List", what do those even do?

Seems like they display a list by splitting the Item state using a user-configured separator.

**Pull request merged**
