### PR TITLE
Remove all dependencies to the dashboard UI

### PR DESCRIPTION
**Pull request by ghys**
Migrate all dashboard tiles to the core tile functionality
(https://github.com/openhab/openhab-core/pull/1329)

Signed-off-by: Yannick Schaus <github@schaus.net>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
FYI: I've just launched a build of the core bundles, so that we can validate that this PR compiles against it.

**Comment by kaikreuzer** [comment]
Build compiles against the new core, but fails with:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project org.openhab.ui.cometvisu: Compilation failure: Compilation failure: 
[ERROR] /home/travis/build/openhab/openhab-webui/bundles/org.openhab.ui.cometvisu/src/main/java/org/openhab/ui/cometvisu/internal/util/ClientInstaller.java:[32,895] The import org.openhab.core.io.net cannot be resolved
[ERROR] /home/travis/build/openhab/openhab-webui/bundles/org.openhab.ui.cometvisu/src/main/java/org/openhab/ui/cometvisu/internal/util/ClientInstaller.java:[223,8491] HttpUtil cannot be resolved
```
Has anything changed in this regard...?

**Comment by ghys** [comment]
Not sure, the only thing I did to the cometvisu pom file is to remove org.openhab.ui.dashboard from it...?

**Comment by ghys** [comment]
I think I figured it out, there were some implicit dependencies to org.openhab.core.boot through the dashboard which had to be added explicitely. Let's see.

**Comment by kaikreuzer** [comment]
Seems to have worked 👍 .

**Pull request merged**
