### PR TITLE
Fix add-ons missing from About Details

### PR DESCRIPTION
**Pull request by wborn**
It is still using /bindings to get the data resulting in a 404 Not Found. The other pages were updated in #1468.

### CODE REVIEW

**Review by florian-h05 — APPROVED** [review]
LGTM, thanks!

**Comment by wborn** [comment]
A backport would also be nice. Then the addons will also be there when this info is copy/pasted into an issue.

**Comment by florian-h05** [comment]
I am currently heading towards vacation and the Wi-Fi on the ICE is currently really slow, but once it gets better I will try to do the backport from my phone (Working Copy is a great Git client for iOS).

**Comment by florian-h05** [comment]
I am currently heading towards vacation and the Wi-Fi on the ICE is currently really slow, but once it gets better I will try to do the backport from my phone (Working Copy is a great Git client for iOS).

**Comment by florian-h05** [comment]
I’ve just cherry picked it, however GitHub says https://github.com/openhab/openhab-webui/commit/a7b436f06fdbafadcb473eabf93eb7c244df1365 „florian-h05 committed“ and not „wborn authored and florian-h05 authored“ as usual. Seems that Working Copy is doing something different here.

**Pull request merged**
