### PR TITLE
Developer sidebar: Add clipboard icons

### PR DESCRIPTION
**Pull request by jimtng**
image
image

### CODE REVIEW

**Review by florian-h05 — APPROVED** [review]
Nice, thanks!

FYI I have added some padding to the icons in the search results, they were IMO too close together.

**Comment by ghys** [comment]
image

Hmm, this is clearly a regression as we don't get the statuses anymore? Or the play/pause buttons?

**Comment by jimtng** [comment]
Both those screenshots are post-pr. Nothing has been removed. Only new icon added.

**Comment by florian-h05** [comment]
> Hmm, this is clearly a regression as we don't get the statuses anymore? Or the play/pause buttons?

IIRC they have never been shown for the search results, only for the pinned stuff.

**Pull request merged**
