### PR TITLE
[BasicUI] Handle the new parameter "staticIcon"

### PR DESCRIPTION
**Pull request by lolodomo**
When set on a sitemap element, Basic UI ignores the item state when initially requesting the OH icon and do not request it again when the item state is updated.

Depends on openhab/openhab-core#3735

Related to openhab/openhab-android#3404

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@kaikreuzer : this PR is only 21 new lines. Could you review it please?

**Comment by kaikreuzer** [comment]
@lolodomo Could you please rebase this PR?

**Comment by lolodomo** [comment]
> @lolodomo Could you please rebase this PR?

Kai, it is done.

**Review by kaikreuzer — APPROVED** [review]
Thanks!

**Pull request merged**
