### PR TITLE
Add UI for health checks (broken links)

### PR DESCRIPTION
**Pull request by seime**
Starting point for a UI that shows issues with the users installation.

First out is broken links.

Depends on https://github.com/openhab/openhab-core/pull/4115

### CODE REVIEW

**Comment by ghys** [comment]
Thanks @seime - I had the same thoughts a few years ago.
My conclusion was that as most issues can be identified on the server, they should then be collected and processed on the server, not the client.

In practice you'd have perhaps a `/rest/issues/scan` API call which will run code on the server that will identify issues like:
- orphan links (missing item or channel)
- items with invalid parent group names
- expressions in Pages or config props referencing unknown items
- etc.

then you could get some details about the issue (`/rest/issues/1234`), its resolution options ('Remove Group1 from Item1 definition', 'Dismiss this issue for now', 'Ignore/delete this issue') and execute a resolution (`/rest/issues/1234/resolve`).

It would be up to server code in a Java class to detect, report, store (in a registry), prevent duplicates, and eventually resolve a particular kind of issue. That is, every kind of issue would have its own class able to detect it, report it, offer options to solve it, and exercise one of these options.

And with OSGi we would be able to introduce and inject new types of issues - ie. an OH binding could run its own diagnostics and insert its own issues.

**Comment by seime** [comment]
Yes, there is plenty to do in this space, and I was thinking a bit of the same. Actually started on a separate rest endpoint, but then reverted it. 

WDYT about starting small and improve and refactor over time - opposed to crafting a whole new set of backend features just to get started?

**Comment by seime** [comment]
@ghys ☝️

**Comment by florian-h05** [comment]
@ghys Can you please comment on

> WDYT about starting small and improve and refactor over time - opposed to crafting a whole new set of backend features just to get started?

and let me know if you are fine with this in general, so I can review it?

**Comment by florian-h05** [comment]
Gentle ping @ghys

**Comment by ghys** [comment]
Yes I'm sorry for the delay, I still would like an UI for "general problem solving" (like I described above) but let's do this organically. You have my support!

**Review by florian-h05 — APPROVED** [review]
Thanks, nice addition!

I have fixed a number of styling and functional issues, but it is now ready for merging - just in time for 4.2.0.

**Pull request merged**
