### PR TITLE
Use commons-lang3 instead of commons-lang

### PR DESCRIPTION
**Pull request by wborn**
This allows for removing the old commons-lang dependency.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Just for my understanding: Wasn't https://github.com/openhab/openhab-addons/issues/7722 about completely removing dependencies to Apache Commons Lang and not just about upgrading to version 3 of it?

**Comment by wborn** [comment]
Yes it is, but we can easily get rid of commons-lang today by just changing the packages in the imports. commons-lang:2.6 is more than 10 years old. :-)

**Comment by kaikreuzer** [comment]
Ok, so it's a first step on the way then...

**Review by kaikreuzer — APPROVED** [review]
Thanks!

**Pull request merged**
