### PR TITLE
Adapt movecontrol icon to bright and dark themes

### PR DESCRIPTION
**Pull request by lolodomo**
Related to #1769

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
With this change:
image
image

Before this change in dark mode:
image

**Comment by lolodomo** [comment]
This change depends on #2084 as only the SVG icon is updated.

**Comment by lolodomo** [comment]
One advantage of this change is that users can now control the color of the icon.

```
sitemap test15 label="Test movecontrol icon"
{
	Frame {
		Default item=TestString icon="movecontrol"
		Default item=TestString icon="movecontrol" iconcolor=["yellow"]
	}
}
```

image

**Comment by lolodomo** [comment]
As Main UI does not adjust icon color depending on theme when "currentColor" is used in the SVG, I will update my change to not use "currentColor" and choose a "hardcoded" color that is fine in bright and dark themes.

**Comment by lolodomo** [comment]
@openhab/webui-maintainers : ready for review.

With this change:
image
image

Before this change:
image
image

**Review by florian-h05 — APPROVED** [review]
LGTM, thanks!
However I‘m not sure if I am allowed to merge …

**Comment by lolodomo** [comment]
@kaikreuzer : another similar one to merge

**Pull request merged**
