### PR TITLE
Add-on store: Title and searchbar focus tweaks

### PR DESCRIPTION
**Pull request by jimtng**
- Display specific title for each tab, but avoid becoming too long on smaller screens
- Don't autofocus on the search bar on mobile because it opens up the on-screen keyboard and covers up half the screen
~~- Add tooltip to the bottom tabbar on narrow screens~~

### CODE REVIEW

**Comment by florian-h05** [comment]
> Add tooltip to the bottom tabbar on narrow screens

I don't think this is a good idea, as having tooltips on clickable links is usually not working very well with touch devices.

**Comment by jimtng** [comment]
> > Add tooltip to the bottom tabbar on narrow screens
> 
> I don't think this is a good idea, as having tooltips on clickable links is usually not working very well with touch devices.

BTW, the little buttons on the bottom of the blockly editor screen also have tooltips.

**Comment by florian-h05** [comment]
> BTW, the little buttons on the bottom of the blockly editor screen also have tooltips.

Yes, but these buttons are also displayed on desktop, where the tooltip is usable. The toolbar of the store is only displayed on mobile, where it is not really usable.

**Review by florian-h05 — APPROVED** [review]
Thanks for the PR, however I think we can achieve the same without adding more data to addon-store.js. I will push a commit for that.

**Pull request merged**
