### PR TITLE
Widget editor: Add note that properties are not evaluated in the editor

### PR DESCRIPTION
**Pull request by florian-h05**

### CODE REVIEW

**Review by ghys — APPROVED** [review]
Thanks!
I think it's a "cop out" though. I'm sure there could be a way to support expressions for the preview in the widget editor - though I haven't looked into it yet.

**Comment by florian-h05** [comment]
> I think it's a "cop out" though. I'm sure there could be a way to support expressions for the preview in the widget editor

Yes, I had a look into it but I haven’t found a quick and simple solution — didn’t want to spend too much time.

**Comment by ghys** [comment]
Thinking back about my comment above, I don't want you to think you yourself "copped out"... it was a general remark about the problem and the ideal solution that should ultimately be provided, not about your contribution that you know I value.

**Comment by florian-h05** [comment]
Everything fine on my side, no worries!

I'm not really satisfied myself either, that was the best thing to do quickly.

**Pull request merged**
