### PR TITLE
[WIP] Migrate Blockly & dependencies to v9

### PR DESCRIPTION
**Pull request by ghys**
Also used the migration script to migrate the block definitions (see https://github.com/google/blockly/releases/tag/blockly-v9.0.0):

```
~/dev/openhab-webui/bundles/org.openhab.ui/web$ npx @blockly/migrate fix-imports --from 6 src/assets/definitions/blockly/* -i
Migrated renamings in src/assets/definitions/blockly/blocks-audio.js
Migrated renamings in src/assets/definitions/blockly/blocks-color.js
Migrated renamings in src/assets/definitions/blockly/blocks-dateoffsets.js
Migrated renamings in src/assets/definitions/blockly/blocks-dicts.js
Migrated renamings in src/assets/definitions/blockly/blocks-ephemeris.js
Migrated renamings in src/assets/definitions/blockly/blocks-eventbus.js
Migrated renamings in src/assets/definitions/blockly/blocks-items.js
Migrated renamings in src/assets/definitions/blockly/blocks-list.js
Migrated renamings in src/assets/definitions/blockly/blocks-logging.js
Migrated renamings in src/assets/definitions/blockly/blocks-notifications.js
Migrated renamings in src/assets/definitions/blockly/blocks-persistence.js
Migrated renamings in src/assets/definitions/blockly/blocks-scripts.js
Migrated renamings in src/assets/definitions/blockly/blocks-text.js
Migrated renamings in src/assets/definitions/blockly/blocks-things.js
Migrated renamings in src/assets/definitions/blockly/blocks-timers.js
Migrated renamings in src/assets/definitions/blockly/blocks-valuestorage.js
Migrated renamings in src/assets/definitions/blockly/index.js
Migrated renamings in src/assets/definitions/blockly/libraries-components.js
Migrated renamings in src/assets/definitions/blockly/libraries.js
Migrated renamings in src/assets/definitions/blockly/utils.js
~/dev/openhab-webui/bundles/org.openhab.ui/web$ npx @blockly/migrate rename --from 6 src/assets/definitions/blockly/* -i
Migrated renamings in src/assets/definitions/blockly/blocks-audio.js
Migrated renamings in src/assets/definitions/blockly/blocks-color.js
Migrated renamings in src/assets/definitions/blockly/blocks-dateoffsets.js
Migrated renamings in src/assets/definitions/blockly/blocks-dicts.js
Migrated renamings in src/assets/definitions/blockly/blocks-ephemeris.js
Migrated renamings in src/assets/definitions/blockly/blocks-eventbus.js
Migrated renamings in src/assets/definitions/blockly/blocks-items.js
Migrated renamings in src/assets/definitions/blockly/blocks-list.js
Migrated renamings in src/assets/definitions/blockly/blocks-logging.js
Migrated renamings in src/assets/definitions/blockly/blocks-notifications.js
Migrated renamings in src/assets/definitions/blockly/blocks-persistence.js
Migrated renamings in src/assets/definitions/blockly/blocks-scripts.js
Migrated renamings in src/assets/definitions/blockly/blocks-text.js
Migrated renamings in src/assets/definitions/blockly/blocks-things.js
Migrated renamings in src/assets/definitions/blockly/blocks-timers.js
Migrated renamings in src/assets/definitions/blockly/blocks-valuestorage.js
Migrated renamings in src/assets/definitions/blockly/index.js
Migrated renamings in src/assets/definitions/blockly/libraries-components.js
Migrated renamings in src/assets/definitions/blockly/libraries.js
Migrated renamings in src/assets/definitions/blockly/utils.js
~/dev/openhab-webui/bundles/org.openhab.ui/web$ npx @blockly/migrate fix-imports --from 6 src/assets/definitions/blockly/_tmp/* -i
Migrated renamings in src/assets/definitions/blockly/_tmp/blocks-exec.js
Migrated renamings in src/assets/definitions/blockly/_tmp/blocks-http.js
~/dev/openhab-webui/bundles/org.openhab.ui/web$ npx @blockly/migrate rename --from 6 src/assets/definitions/blockly/_tmp/* -i
Migrated renamings in src/assets/definitions/blockly/_tmp/blocks-exec.js
Migrated renamings in src/assets/definitions/blockly/_tmp/blocks-http.js
```

blockly-editor.vue was migrated manually. Seems to work okay so far.

TODO: the dark theme doesn't seem to be applied anymore.

Signed-off-by: Yannick Schaus <github@schaus.net>

### CODE REVIEW

**Comment by florian-h05** [comment]
@ghys 
I would prefer if that gets merged after @stefan-hoehn contributed our Blockly JS Scripting portation because I guess adjusting this here is much easier than resolving merge conflicts in our upcoming PR.

**Comment by ghys** [comment]
From #1608 

> Can you try this again and try to increase blockly to 9.2.x. This is actually a good time as we currently incorporating graalvm and I need to to test all blocks anyway.

So you and @stefan-hoehn should make up your mind ;)

**Comment by florian-h05** [comment]
If we’d make the upgrade in our branch (our create a new branch out of our current branch to be safe), it would work, I just don’t want to run into merge conflicts.

**Comment by florian-h05** [comment]
@ghys Have you had a look at #1601?

**Comment by stefan-hoehn** [comment]
First of all, @ghys , this really was my Christmas wish 🥇 

I will check with Florian in the background how we want to proceed with that.

**Comment by florian-h05** [comment]
@ghys 
You can close your PR, I‘ve added the Blockly upgrade (thanks for the tip with the update script) to our branch so @stefan-hoehn can test everything.

**Comment by stefan-hoehn** [comment]
And I am really happy now to be on blockly 9.2 <3

**Comment by ghys** [comment]
> You can close your PR, I‘ve added the Blockly upgrade (thanks for the tip with the update script) to our branch so @stefan-hoehn can test everything

Excellent, glad to hear it!

**Comment by ghys** [comment]
> @ghys Have you had a look at https://github.com/openhab/openhab-webui/pull/1601?

Not yet I'm not at home but definitely will in the near future, just want to test it and not merging blindly (even though the description is extensive and it looks great at first sight).

**Pull request closed without merging**
