### PR TITLE
[cometvisu] Security fixes  & cleanup for cometvisu backend

### PR DESCRIPTION
**Pull request by peuter**
add required authentication for some rest endpoints, add some sanity checks to improve security.

Remove code that has been marked as deprecated.

### CODE REVIEW

**Review by kaikreuzer — APPROVED** [review]
Thanks @peuter for the fixes and the clean up!

**Comment by florian-h05** [comment]
Thanks for the security fixed @peuter - do you mind taking a look at the code scanning results for CometVisu?
https://github.com/openhab/openhab-webui/security/code-scanning?query=is%3Aopen+branch%3Amain+language%3Ajava (you need to check what's for CometVisu, I haven't found a way to filter that list).

**Comment by peuter** [comment]
I will take a look at the code scanning results, will take some time because there are quite a lot of them. I just randomly looked into some of them and they looked like false positives (or negatives regarding the topic ;-) to me. All the "uncontrolled data used in path expression" do not seem to recognize that there is a path check in MountedFile.

But I will check that with a little bit more time than I have right now. Maybe I am missing something.

**Comment by florian-h05** [comment]
Code scanning results for Vue/JS also had some false positives, but overall it caught a few things really well.

**Comment by kaikreuzer** [comment]
@peuter Just in case you again didn't receive any notification - could you please have a look at the feedback at https://github.com/openhab/openhab-webui/security/advisories/GHSA-v7gr-mqpj-wwh3#advisory-comment-106507 and respond to it? As soon as everything is clarified, I would like to backport the fix(es) to 4.1.x and publish the advisories. Thanks!

**Comment by peuter** [comment]
No I haven't been noticed, I dont know why I do not get noticed when I am mentioned in the advisories, I checked all settings I could find in github. Anyways I will check them soon.

**Comment by kaikreuzer** [comment]
Cherry-picked to `4.2.x`.

**Comment by kaikreuzer** [comment]
@peuter Did you find the time to look into the remaining file separator issue?

**Pull request merged**
