### PR TITLE
Upgrade SAT to 0.12.0

### PR DESCRIPTION
**Pull request by wborn**
See the [0.12.0 milestone](https://github.com/openhab/static-code-analysis/milestone/18?closed=1) for all changes in this release.

Depends on https://github.com/openhab/openhab-webui/pull/1190

### CODE REVIEW

**Comment by ghys** [comment]
@wborn could you perhaps rebase and trigger a new build to check that #1190 fixes it?

**Comment by wborn** [comment]
I already pushed a button in Jenkins, see:

https://ci.openhab.org/job/PR-openHAB-WebUI/984/

**Review by ghys — APPROVED** [review]
> I already pushed a button in Jenkins, see:
https://ci.openhab.org/job/PR-openHAB-WebUI/984/

Ah, right - thanks!

**Comment by wborn** [comment]
Thanks you too! :+1:

**Pull request merged**
