### PR TITLE
[cometvisu] fix path check regressions

### PR DESCRIPTION
**Pull request by peuter**
1. Fix serving the index.html when "/" (or empty) path is requested
2. Fix allowing files beeing served from special cometvisu config folder

### CODE REVIEW

**Review by kaikreuzer — APPROVED** [review]
Thanks!

**Comment by kaikreuzer** [comment]
@peuter Is this something critical that should be backported to 4.2.x or is it fine to only fix it on main?

**Comment by peuter** [comment]
A Backport to 4.2 would be great. For one of the problems this PR fixes we do not have a workaround and it breaks a quite common and useful use case.

**Comment by kaikreuzer** [comment]
Done!

**Pull request merged**
