### PR TITLE
[BasicUI] Fix closing h4 tag in sitemap list page

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@kaikreuzer : funny that no one saw this before. I guess it could be there since the very initial version of Basic UI ;)

**Review by florian-h05 — APPROVED** [review]
LGTM, thanks!

**Comment by lolodomo** [comment]
Would be good to also apply this fix to 4.1.x branch.

**Comment by florian-h05** [comment]
Feel free to cherry pick yourself, I’m away from keyboard.

**Comment by kaikreuzer** [comment]
> Would be good to also apply this fix to 4.1.x branch.

What bug does it fix (besides clearly being wrong html)?

**Comment by lolodomo** [comment]
> What bug does it fix (besides clearly being wrong html)?

None, it looks like browsers are able to handle these errors.

**Comment by kaikreuzer** [comment]
Then I don't think we need to backport it to 4.1.x.

**Pull request merged**
