### PR TITLE
Sitemap editor: Add Buttongrid Button support

### PR DESCRIPTION
**Pull request by mherwege**
Refs https://github.com/openhab/openhab-core/pull/4377.

The most recent addition to the sitemap syntax allows defining buttons nested as components inside the Buttongrid component.

### CODE REVIEW

**Comment by mherwege** [comment]
Probably better to first finish https://github.com/openhab/openhab-webui/pull/2720 first and then rebase on that. The impact starts to be pretty big.

**Comment by mherwege** [comment]
Dependency https://github.com/openhab/openhab-core/pull/4377 Is now merged.

**Comment by lolodomo** [comment]
> Dependency [openhab/openhab-core#4377](https://github.com/openhab/openhab-core/pull/4377) Is now merged.

I just triggered a rebuild of your PR.

**Review by florian-h05 — CHANGES_REQUESTED** [review]
I wanted to give this a try by creating a new (hence empty) sitemap, but I cannot save that empty sitemap. 
If I add a widget to it, I can save it.

@mherwege Can you please have a look?

**Comment by mherwege** [comment]
> I wanted to give this a try by creating a new (hence empty) sitemap, but I cannot save that empty sitemap.

It looks like that bug was there before this PR. It should be fixed now.

**Comment by florian-h05** [comment]
I though it was a regression from this PR, anyway thanks for the fix!
And please do NOT force push during review!!

**Comment by mherwege** [comment]
> And please do NOT force push during review!! It normally does not matter if a PR is not in sync with main.

Sorry for that. I normally don’t, but I made the mistake a few weeks ago to merge main into the branch from the web, and I couldn’t get it to push anymore without a rebase and force push.

**Pull request merged**
