### PR TITLE
No quotes around chart period parameter in generated sitemap DSL

### PR DESCRIPTION
**Pull request by mherwege**

### CODE REVIEW

**Review by florian-h05 — CHANGES_REQUESTED** [review]
It generates sitemap code without quotes, but the lexer is complaining:

```
sitemap page_eee951ba09 label="New Sitemap" {
    Chart period=8h item=Aussentemperatur
}
```

gives this error:

```
Error: Syntax error at line 2 col 19:

      Chart period=8h
                    ^
Unexpected identifier token: "h". Instead, I was expecting to see one of the following:

A WS token based on:
    _ → _ ● %WS
    WidgetAttrs → WidgetAttrs ● _ WidgetAttr
    Widget$ebnf$1 → Widget$ebnf$1 ● WidgetAttrs
    Widget → %nlwidget _ ● Widget$ebnf$1
    Widgets →  ● Widget
    Sitemap → %sitemap _ SitemapName __ SitemapLabel __ %lbrace _ ● Widgets _ %rbrace
    Main → _ ● Sitemap _
A NL token based on:
    _ → _ ● %NL
    WidgetAttrs → WidgetAttrs ● _ WidgetAttr
    Widget$ebnf$1 → Widget$ebnf$1 ● WidgetAttrs
    Widget → %nlwidget _ ● Widget$ebnf$1
    Widgets →  ● Widget
    Sitemap → %sitemap _ SitemapName __ SitemapLabel __ %lbrace _ ● Widgets _ %rbrace
    Main → _ ● Sitemap _
A widgetswitchattr token based on:
    WidgetAttr →  ● %widgetswitchattr
    WidgetAttrs → WidgetAttrs _ ● WidgetAttr
    Widget$ebnf$1 → Widget$ebnf$1 ● WidgetAttrs
    Widget → %nlwidget _ ● Widget$ebnf$1
    Widgets →  ● Widget
    Sitemap → %sitemap _ SitemapName __ SitemapLabel __ %lbrace _ ● Widgets _ %rbrace
    Main → _ ● Sitemap _
A widgetfreqattr token based on:
    WidgetAttr →  ● %widgetfreqattr
    WidgetAttrs → WidgetAttrs _ ● WidgetAttr
    Widget$ebnf$1 → Widget$ebnf$1 ● WidgetAttrs
    Widget → %nlwidget _ ● Widget$ebnf$1
    Widgets →  ● Widget
    Sitemap → %sitemap _ SitemapName __ SitemapLabel __ %lbrace _ ● Widgets _ %rbrace
    Main → _ ● Sitemap _
A widgetfrcitmattr token based on:
    WidgetAttr →  ● %widgetfrcitmattr
    WidgetAttrs → WidgetAttrs _ ● WidgetAttr
    Widget$ebnf$1 → Widget$ebnf$1 ● WidgetAttrs
    Widget → %nlwidget _ ● Widget$ebnf$1
    Widgets →  ● Widget
    Sitemap → %sitemap _ SitemapName __ SitemapLabel __ %lbrace _ ● Widgets _ %rbrace
    Main → _ ● Sitemap _
A item token based on:
    WidgetAttrName →  ● %item
    WidgetAttr →  ● WidgetAttrName WidgetAttrValue
    WidgetAttrs → WidgetAttrs _ ● WidgetAttr
    Widget$ebnf$1 → Widget$ebnf$1 ● WidgetAttrs
    Widget → %nlwidget _ ● Widget$ebnf$1
    Widgets →  ● Widget
    Sitemap → %sitemap _ SitemapName __ SitemapLabel __ %lbrace _ ● Widgets _ %rbrace
    Main → _ ● Sitemap _
A label token based on:
    WidgetAttrName →  ● %label
    WidgetAttr →  ● WidgetAttrName WidgetAttrValue
    WidgetAttrs → WidgetAttrs _ ● WidgetAttr
    Widget$ebnf$1 → Widget$ebnf$1 ● WidgetAttrs
    Widget → %nlwidget _ ● Widget$ebnf$1
    Widgets →  ● Widget
    Sitemap → %sitemap _ SitemapName __ SitemapLabel __ %lbrace _ ● Widgets _ %rbrace
    Main → _ ● Sitemap _
A icon token based on:
    WidgetAttrName →  ● %icon
    WidgetAttr →  ● WidgetAttrName WidgetAttrValue
    WidgetAttrs → WidgetAttrs _ ● WidgetAttr
    Widget$ebnf$1 → Widget$ebnf$1 ● WidgetAttrs
    Widget → %nlwidget _ ● Widget$ebnf$1
    Widgets →  ● Widget
    Sitemap → %sitemap _ SitemapName __ SitemapLabel __ %lbrace _ ● Widgets _ %rbrace
    Main → _ ● Sitemap _
A widgetattr token based on:
    WidgetAttrName →  ● %widgetattr
    WidgetAttr →  ● WidgetAttrName WidgetAttrValue
    WidgetAttrs → WidgetAttrs _ ● WidgetAttr
    Widget$ebnf$1 → Widget$ebnf$1 ● WidgetAttrs
    Widget → %nlwidget _ ● Widget$ebnf$1
    Widgets →  ● Widget
    Sitemap → %sitemap _ SitemapName __ SitemapLabel __ %lbrace _ ● Widgets _ %rbrace
    Main → _ ● Sitemap _
A widgetvisiattr token based on:
    WidgetVisibilityAttrName →  ● %widgetvisiattr
    WidgetAttr →  ● WidgetVisibilityAttrName WidgetVisibilityAttrValue
    WidgetAttrs → WidgetAttrs _ ● WidgetAttr
    Widget$ebnf$1 → Widget$ebnf$1 ● WidgetAttrs
    Widget → %nlwidget _ ● Widget$ebnf$1
    Widgets →  ● Widget
    Sitemap → %sitemap _ SitemapName __ SitemapLabel __ %lbrace _ ● Widgets _ %rbrace
    Main → _ ● Sitemap _
A widgetcolorattr token based on:
    WidgetColorAttrName →  ● %widgetcolorattr
    WidgetAttr →  ● WidgetColorAttrName WidgetColorAttrValue
    WidgetAttrs → WidgetAttrs _ ● WidgetAttr
    Widget$ebnf$1 → Widget$ebnf$1 ● WidgetAttrs
    Widget → %nlwidget _ ● Widget$ebnf$1
    Widgets →  ● Widget
    Sitemap → %sitemap _ SitemapName __ SitemapLabel __ %lbrace _ ● Widgets _ %rbrace
    Main → _ ● Sitemap _
```

Unfortunately I have no experience with https://nearley.js.org/, so we need to ask @ghys for help.

**Comment by mherwege** [comment]
@florian-h05 The parser should work again.

**Review by florian-h05 — APPROVED** [review]
LGTM now, thanks!

**Comment by florian-h05** [comment]
@mherwege What I noticed while testing this:

`forceasitem` is not accepted:

```
sitemap MySitemap label="Test Sitemap" {
    Switch item=Hallway_Light
    Chart period=8h item=test_temperature forceasitem=true
}
```

leads to:

```
Error: Syntax error at line 3 col 55:

      Chart period=8h item=test_temperature forceasitem=true
                                                        ^
Unexpected identifier token: "true". Instead, I was expecting to see one of the following:
...
```

**Comment by florian-h05** [comment]
@openhab/webui-maintainers 
Should we cherry-pick this to the 3.4.x branch?

**Comment by mherwege** [comment]
> @openhab/webui-maintainers
> Should we cherry-pick this to the 3.4.x branch?

Of course, up to the maintainers. But the simple workaround is to put quotes around the period when working with the sitemap code in the UI. So I don’t think it is critical.

**Comment by mherwege** [comment]
> `forceasitem` is not accepted

It should be according to the code. I will have a look at what is wrong there.

**Comment by florian-h05** [comment]
Sorry, I was not exact enough.
`forceasitem` is accepted, but the Boolean value of it is not.

**Comment by mherwege** [comment]
> > @openhab/webui-maintainers
> > Should we cherry-pick this to the 3.4.x branch?
> 
> Of course, up to the maintainers. But the simple workaround is to put quotes around the period when working with the sitemap code in the UI. So I don’t think it is critical.

The more important one to cherry pick for 3.4 would be https://github.com/openhab/openhab-webui/pull/1781. This fixes real issues with a few parameters without easy workaround. If that can be reviewed and merged, it makes sense to both include this one and the new one in 3.4.

**Pull request merged**
