### PR TITLE
[BasicUI] Fix build after a method renaming in core framework

### PR DESCRIPTION
**Pull request by lolodomo**
Related to openhab/openhab-core#3652 that renamed method setPageId into updateSubscriptionLocation

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@openhab/webui-maintainers : please consider a fast merge, the build is currently failing

**Comment by lolodomo** [comment]
@florian-h05 : I don't think it has any link but today in my dev environment, Main UI is fully unstable, I have SSE errors.
image

**Comment by florian-h05** [comment]
I don't have that issue on my dev system (localhost).

What is your network setup?

**Comment by lolodomo** [comment]
It just appeared today. Will see if it persists tomorrow.

**Comment by florian-h05** [comment]
Hmm I extra checked with the latest snapshot and did not have any problem. Let's wait :+1:

**Pull request merged**
