### PR TITLE
add doc link to state/commandDescription edit form

### PR DESCRIPTION
**Pull request by stefan-hoehn**
Signed-off-by: Stefan Höhn <mail@stefanhoehn.com>

Add documentation url link to stateDescription and commandDescription edit form. 

requires https://github.com/openhab/website/pull/392

### CODE REVIEW

**Review by ghys — APPROVED** [review]
Thanks!
Just for the record this would suppose there's a command-description/state-description anchor in the doc - which could change if the docs are modified.

**Comment by ghys** [comment]
I just realized https://github.com/openhab/website/pull/392 was not merged yet. So if the link changes just open another PR.

**Comment by stefan-hoehn** [comment]
> Thanks! Just for the record this would suppose there's a command-description/state-description anchor in the doc - which could change if the docs are modified.

Thanks, yes there is atm.

**Comment by stefan-hoehn** [comment]
Got it, I saw some other areas where an anchor was used and it thought it would be better not to have to many references... Anyway, I may change that eventually.

**Pull request merged**
