### PR TITLE
Modelview deletekey functionality

### PR DESCRIPTION
**Pull request by bigbasec**
As I was testing my OH setup I found myself always winding up with orphan items in the model view, and clicking to remove them was a bit of a hassle, so I came up with this.   

Might be a better way to do this, just really copied the code from the detail view and refactored for the main page.

### CODE REVIEW

**Comment by ghys** [comment]
Since the delete logic is already in `item-details.vue` maybe it would be better to add the handler there instead of in model.vue?

**Comment by bigbasec** [comment]
100% first time ever doing anything w/ F7 or Vue, so little bit of a learning curve here, appologies.   I'll take a look at that though and see what I can come up with.   And yes, this was literally a copy/paste from there and changing it to match the vue.

**Comment by bigbasec** [comment]
@ghys Should be all set now.  Thanks

**Review by ghys — APPROVED** [review]
LGTM now!

**Pull request merged**
