### PR TITLE
Add panel for voiceSystem metadata

### PR DESCRIPTION
**Pull request by GiviMAD**
Hello, I would like to add these panel for editing the item voiceSystem namespace.

It needs to wait for the review of these core PR https://github.com/openhab/openhab-core/pull/3925 , hope it's fine to open the PR anyway.

Screenshots:

Screenshot 2023-12-15 at 22 23 46

Screenshot 2023-12-15 at 20 16 22

Screenshot 2023-12-15 at 22 20 30

### CODE REVIEW

**Comment by ghys** [comment]
Thanks @GiviMAD - I've been following your work and having a generic voice system is great.
Regarding this PR I have a couple early cosmetic change requests:

- could you put it above the vendor-specific namespaces (i.e. just above 'Amazon Alexa'); I'd like to keep those last
- for the 3 flags I think the long description on the right won't work well on narrow screens, maybe you could change that to a `<config-sheet>` component with a hard-coded parameter description structure (the 'BOOLEAN' type will render as switches), the same way it's done here:
https://github.com/openhab/openhab-webui/blob/main/bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-itemdescription.vue

**Comment by GiviMAD** [comment]
Thank you for the review and the comments! I've updated the PR.

**Comment by GiviMAD** [comment]
The required core PR has been merged.

**Comment by GiviMAD** [comment]
@florian-h05 @ghys would you be able to review the PR so it can get into the last milestone? Thank you in advance.

**Review by florian-h05 — APPROVED** [review]
LGTM, thanks!

Just some minor thing: We ususally spell `Item` uppercase as it is a openHAB term. I will fix that myself to get this merged soon.

**Comment by florian-h05** [comment]
BTW: I am looking forward to see some docs for this new feature so I could try this out at some point in time.

**Comment by GiviMAD** [comment]
Thank you for the review!

Yes, I have a brief of the functionality written in one of the PRs. I think with some changes it could be an entendible documentation page. I'll look at it, I've never updated the documentation before.

**Pull request merged**
