### PR TITLE
[BasicUI] Use forceAsItem-option from sitemaps

### PR DESCRIPTION
**Pull request by Flole998**
Part of implementing  openhab/openhab-core#2185

Depends-on: openhab/openhab-core#2657

### CODE REVIEW

**Comment by Flole998** [comment]
@lolodomo The PR this depends on has been merged. So this can be rebuilt and then reviewed and merged now.

**Comment by Flole998** [comment]
Sorry, seems like I was too fast there. OH-core wasn't rebuild yet apparently, I guess we need to check back tomorrow.

**Review by lolodomo — APPROVED** [review]
LGTM

**Comment by lolodomo** [comment]
Build is failing... in HABot.

**Comment by lolodomo** [comment]
@ghys : is there any risk to merge?

**Comment by ghys** [comment]
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project org.openhab.ui.habot: Compilation failure
[ERROR] /home/jenkins/jenkins-agent1/workspace/PR-openHAB-WebUI/bundles/org.openhab.ui.habot/src/main/java/org/openhab/ui/habot/nlp/internal/OpenNLPInterpreter.java:[103,20] Null type mismatch: required 'java.lang.@NonNull String' but the provided value is null
```
I guess not, it seems unrelated. The PR was probably opened when there an inconsistency in null checks between core and the implementations here. AFAIR it was finally fixed in #1318.

**Pull request merged**
