### PR TITLE
Allow setting gradientDirection for oh-trend component

### PR DESCRIPTION
**Pull request by petero-dk**
Allow the option for setting the gradientDirection for the oh-trend. Personally I use this so I can use the gradients to visualize the time of day for changes. i.e. yellow for day time, and blue for night time. That requires the gradient to be horizontal. 

image

### CODE REVIEW

**Review by ghys — APPROVED** [review]
> Personally I use this so I can use the gradients to visualize the time of day for changes. i.e. yellow for day time, and blue for night time. That requires the gradient to be horizontal. 
> image

This is quite clever, I like it :)
LGTM but would you please sign off this change (https://github.com/openhab/openhab-core/blob/main/CONTRIBUTING.md#sign-your-work), no need to amend the commit message, just comment with your sign-off line.

**Comment by florian-h05** [comment]
The new parameter is missing in the widget definition.

**Comment by ghys** [comment]
Indeed!

**Comment by petero-dk** [comment]
The definition has been updated.

Signed-off-by: Peter Obel <peter@ecomerc.com> (github: petero-dk)

**Pull request merged**
