### PR TITLE
Remove CometVisu UI

### PR DESCRIPTION
**Pull request by kaikreuzer**
Due the fact that it is no longer maintained and newer versions of CometVisu can use openHAB's REST API directly, we can remove this UI from the repo.

### CODE REVIEW

**Comment by peuter** [comment]
Why do you think it is no longer maintained? Did I miss something? There is just no requirement for changes here, that's why there aren't any. This is still needed by users who are using the cometvisu with openhabs built-in webserver. It adds a backend for cometvisus built-in maintenance features. Although we recommend using the official docker container to serve the cometvisu there are still users who do not do this. So please do not remove this.

**Comment by kaikreuzer** [comment]
Sounds as if you had missed some notifications in the past months. Please have a look at
https://github.com/openhab/openhab-webui/security/advisories/GHSA-v7gr-mqpj-wwh3
https://github.com/openhab/openhab-webui/security/advisories/GHSA-3g4c-hjhr-73rj
https://github.com/openhab/openhab-webui/security/advisories/GHSA-f729-58x4-gqgf
https://github.com/openhab/openhab-webui/security/advisories/GHSA-pcwp-26pw-j98w

**Comment by kaikreuzer** [comment]
@rkoshak You are right, these advisories are in draft mode and thus only visible to repo maintainers so far.
They are all about the REST endpoints of the CometVisu, mainly typical weaknesses as listed by OWASP.

**Comment by peuter** [comment]
I haven't got any notification about those security problems, so I missed them all. 
I will have at look at them ASAP.

**Comment by peuter** [comment]
I created https://github.com/openhab/openhab-webui/pull/2671 that addresses the 4 listed security advisories (and some cleanup and minor stuff). Do I have to do anything with those security advisories, like add a comment how I tried to solve them, or anything else?

**Comment by kaikreuzer** [comment]
> add a comment how I tried to solve them, or anything else?

Yes, that would be great!
I'll close this PR as I've just merged https://github.com/openhab/openhab-webui/pull/2671 - thanks for that!

**Pull request closed without merging**
