### PR TITLE
REST docs: use the redirect URI as client ID

### PR DESCRIPTION
**Pull request by ghys**
Depends on https://github.com/openhab/openhab-core/pull/1496

Signed-off-by: Yannick Schaus <github@schaus.net>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
> Depends on openhab/openhab-core#1483

Which is closed now. Do you plan to do a new PR with a rewrite of the class in question? Or will you first do a change in the upstream project?

**Comment by ghys** [comment]
May catch some heat with that, but while experimenting I ended removing the library completely 🤷‍♂️. See https://github.com/openhab/openhab-core/pull/1496.

**Comment by kaikreuzer** [comment]
Wow, excellent, sounds like an even better solution 😄.

**Comment by ghys** [comment]
No harm in merging this early I guess, it'll sit there until the server-side comes.

**Pull request merged**
