### PR TITLE
Use cacheable lists when possible

### LINKED ISSUE #1650: [MainUI] /settings/things/<thing uid> requests entire things JSON from API
## The problem

I have a lot of things. With an even more ridiculous amount of channels. My /rest/things endpoint returns over 2.5MB of JSON. When I'm local, this takes nearly a second just to transfer. If I'm remote, it would take _much_ longer. Right now, when I click on an individual thing to configure it, I notice that it's using /rest/things to load the data. I'm sure this takes a long time for the javascript to parse, as well.

## Your suggestion

Instead, it should use `/rest/things/<thing UID>` to _only_ load the relevant information for the current page.

## Your environment

```yaml
runtimeInfo:
  version: 3.4.1
  buildString: Release Build
locale: en-Latn-US
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.5
  javaVendor: Private Build
  osName: Linux
  osVersion: 5.15.0-57-generic
  osArchitecture: amd64
  availableProcessors: 8
  freeMemory: 169239392
  totalMemory: 2147483648
  startLevel: 100
bindings:
  - amazonechocontrol
  - astro
  - bondhome
  - dscalarm
  - lgwebos
  - mqtt
  - myq
  - onkyo
  - pioneeravr
  - tuya
  - unifi
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: en-US
    languages:
      - en-US
    onLine: true
    platform: MacIntel
  screen:
    width: 3008
    height: 1692
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15
    (KHTML, like Gecko) Version/16.2 Safari/605.1.15
timestamp: 2023-01-17T23:36:18.688Z
```

### PR DESCRIPTION
**Pull request by ghys**
Depends on https://github.com/openhab/openhab-core/pull/3335.

Will fetch items, things and rules with the `cacheable` parameter set
when appropriate.

Closes #1650.

Signed-off-by: Yannick Schaus <github@schaus.net>

### CODE REVIEW

**Comment by florian-h05** [comment]
@ghys 
Does this fix https://github.com/openhab/openhab-webui/issues/1630?

**Comment by florian-h05** [comment]
@ghys Would this solve issue https://github.com/openhab/openhab-webui/issues/673?

**Comment by ghys** [comment]
I don't think so - the problem was likely mitigated by the added `?summary=true` parameter and by #675. Some people have a lot of status changes (multiple times a second in some cases) and there's not much more to do to address that.

**Comment by florian-h05** [comment]
@ghys Can you please Update is PR and resolve merge conflicts?

**Comment by ghys** [comment]
done, should be good now!

**Review by florian-h05 — APPROVED** [review]
LGTM, thanks!
This should really improve load times on any network!

You had a typo somewhere, I corrected it and also extended usage of staticDataOnly to a few other requests you forgot.

**Comment by ghys** [comment]
> You had a typo somewhere

Of course I had, much appreciated! :sweat: 

> extended usage of staticDataOnly

About those on the developer sidebar search, I didn't change them because maybe the non-static data from those requests are actually useful (it shows the state of items and status of things & rules etc.). We'll see if it breaks something.

**Comment by florian-h05** [comment]
> About those on the developer sidebar search, I didn't change them because maybe the non-static data from those requests are actually useful.

I have checked, the search does not use anything from the non-static data.
Regarding status, I think those come from SSE, so I'd don't expect any problems but we'll see.

**Comment by florian-h05** [comment]
I just noticed that we forgot the UI endpoints, which also support `staticDataOnly`.

**Pull request merged**
