### PR TITLE
improve Maven + Bnd layout and settings

### PR DESCRIPTION
**Pull request by maggu2810**
https://github.com/openhab/openhab-webui/issues/38

The BOM will be provided by another PR.

### CODE REVIEW

**Comment by wborn** [comment]
Looks like SAT is no longer active on this repo with these changes @maggu2810.

**Comment by maggu2810** [comment]
Ah sorry, I was not aware that it has been necessary for the WebUIs, too.

Will add it again.

**Comment by maggu2810** [comment]
I also need to add another fix for cometvisu.php that depends on cometvisu, that GAV has been changed.
But I am on it.

**Comment by wborn** [comment]
The CODEOWNERS file also needs an update for these changes.

**Pull request merged**
