### PR TITLE
Improve network-interface context support

### PR DESCRIPTION
**Pull request by wborn**
This allows for selecting multiple network interface names in configuration parameters.

Related to:

* https://github.com/openhab/openhab-core/pull/3981
* https://github.com/openhab/openhab-addons/pull/16145

### CODE REVIEW

**Comment by wborn** [comment]
Both PRs got merged now.

**Review by kaikreuzer — APPROVED** [review]
lgtm, thanks!

**Comment by kaikreuzer** [comment]
Cherry-picked to `4.1.x`.

**Review by florian-h05 — COMMENTED** [review]
LGTM, thanks!

@kaikreuzer Thanks for already merging and backporting this PR.

**Pull request merged**
