### PR TITLE
Update HomeKit metadata definitions

### PR DESCRIPTION
**Pull request by ccutrer**
Add missing accessories, configuration parameters, enums, etc.

### CODE REVIEW

**Comment by ccutrer** [comment]
You may want to look at the commits individually, since one of them sorts them all.

cc @yfre

**Review by florian-h05 — APPROVED** [review]
LGTM, thanks for the updates!

**Comment by florian-h05** [comment]
Let‘s wait a few days for @yfre so he can have a look if he wants to.

**Comment by florian-h05** [comment]
Let's merge this now.

**Pull request merged**
