### PR TITLE
[BasicUI] Create header row only when needed

### PR DESCRIPTION
**Pull request by lolodomo**
For buttongrid/mapview/video/webview elements, avoids generating HTML code for header row when it is hidden.

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
This optimization also avoids an unnecessary request for icon when there is no header row.

**Comment by lolodomo** [comment]
Related to this discussion:
https://github.com/openhab/openhab-webui/issues/2259#issuecomment-1890541621

**Comment by lolodomo** [comment]
Merge conflict is fixed.

**Review by kaikreuzer — APPROVED** [review]
Thanks!

**Pull request merged**
