### PR TITLE
Thing actions: Sort by label, Show description, Hide unsupported actions

### PR DESCRIPTION
**Pull request by florian-h05**
Follow-up for #2818.

### CODE REVIEW

**Comment by lolodomo** [comment]
@florian-h05 : I started to test the new snapshot and check what actions are shown on my different things. I discovered a very minor "issue": For my hue things, I see the title "Actions" but there is no action displayed. I will check the hue actions to confirm that they are not supported bu UI but I believe you should not show the "Actions" if there is no supported thing actions. WDYT ?

image

**Comment by florian-h05** [comment]
True.
I already check the length of the actions array, but I need to filter it for UI support first before doing that. Will create a PR for that.

**Comment by lolodomo** [comment]
Regarding the hue action, I can confirm it is not supported by UI because one of its input parameters is of type org.openhab.core.types.Command. What a strange choice...

**Comment by florian-h05** [comment]
My plan is that once war are finished with all core and UI changes around Thing actions that I write to the docs how to design a action for „good“ UI support.

**Pull request merged**
