### PR TITLE
[BasicUI] Prefer icon over text in buttons (switch element)

### PR DESCRIPTION
**Pull request by lolodomo**
Related to openhab/openhab-core#3441

Depends on openhab/openhab-core#3809

Icons will not be used if icons are nbot enabled (app setting).

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
Here is an example with this element defined like that:
```
		Switch item=TestCommand mappings=[0=NULL,1=UNDEF,2="Set 1",3="Set 2"]
		Switch item=TestCommand mappings=[0=NULL=f7:house,1=UNDEF="material:favorite",2="Set 1"=if:lucide:activity-square,3="Set 2"=chart]
```
The first element shows that nothing is changed if no icon is provided.
The second element shows how it looks when an icon is provided and also that it work whatever the icon source.
image

**Comment by lolodomo** [comment]
Just waiting for a new build of the core framework to rebuild this PR.

**Comment by wborn** [comment]
I have triggered a build. :rocket:

**Comment by lolodomo** [comment]
> I have triggered a build. 🚀

Thank you.

A rebase of my branch was also required.
Build is now OK.

**Review by kaikreuzer — APPROVED** [review]
Thank you!

**Pull request merged**
