### PR TITLE
Fix thing UID generation

### LINKED ISSUE #380: [Main UI] Manually created Things related to a Bridge should be created with proper ThingUID
When creating a `Thing` manually via UI and assign it to a `Bridge` the resulting `ThingUID` does not contain the bridge id.

Create a Thing:

grafik

Assign it to a Bridge - Identifier changes properly:

grafik

Use "Create Thing" and sniff POST request - UID does not contain the bridge id anymore and thus it will be created wrongly:

grafik

Related to https://github.com/openhab/openhab-core/pull/1704
See also https://github.com/openhab/openhab-addons/pull/7496#discussion_r425425821

### PR DESCRIPTION
**Pull request by ghys**
Fixes #380.

Signed-off-by: Yannick Schaus <github@schaus.net>

### CODE REVIEW

**Review by cweitkamp — APPROVED** [review]
LGTM. Thanks.

**Comment by ghys** [comment]
Why is this not merged yet 😆

**Comment by Hilbrand** [comment]
Can this branch also be deleted? (Just picking a random branch to complain :wink:) This repo is getting polluted with dead branches. There are already 9(!) branches that are merged but not deleted. When someone makes a fork they will get these branches and when I checkout I get all these branches locally and unless I'll do an explicit purge these branches live on forever.
Maybe we should not create branches directly on the main repos?

**Comment by ghys** [comment]
That's usually when I open a PR with the "edit file" feature here on GitHub, when you have admin rights on the target repo it creates a branch there instead of your own fork. But you're right, I'll clean up the branches.

**Pull request merged**
