### PR TITLE
[BasicUI] Adjust slider unit handling

### PR DESCRIPTION
**Pull request by mherwege**
Adjust BasicUI slider unit handling.
So far, the unit was not passed on to the slider. With proposed changes in core https://github.com/openhab/openhab-core/pull/3644, unit would be passed and needs to stripped for the slider to work properly.

### CODE REVIEW

**Comment by mherwege** [comment]
See: https://github.com/openhab/openhab-core/pull/3644#issuecomment-1587095260

> In file smarthome.js (BasicUI), line 1698 has to be fixed and comment at line 1683 has to be removed. Line 1659 has to be checked too (I am not sure of the behaviour of parseInt) .

Changes in 1698 and 1683 done, no need to change 1659 as parseInt drops anything after the number.

**Comment by mherwege** [comment]
One issue could still remain in line 1688 (`_t.reloadIconColor(ItemState)`). I could strip the unit there as well. But it makes me wonder about the behaviour with other widgets that carry a unit. Would the expectation be that the state conditions are defined without unit for slider widget and with unit for other widgets?

**Comment by mherwege** [comment]
@lolodomo For your review and comment.

**Comment by lolodomo** [comment]
No need to strip the unit when calling reloadIcon. 
First, it is not done for other widgets. 
Second, the icon server is doing the strip itself:
https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.ui.icon/src/main/java/org/openhab/core/ui/icon/AbstractResourceIconProvider.java#L71

**Review by lolodomo — APPROVED** [review]
LGTM, thank you

**Comment by mherwege** [comment]
@lolodomo I believe this PR does not depend on core https://github.com/openhab/openhab-core/pull/3644. It would be required to merge if https://github.com/openhab/openhab-core/pull/3644 gets merged, but doesn't break anything if merged before. It will only try to strip a (non-existing) unit in that case.

**Comment by lolodomo** [comment]
You're right.

**Pull request merged**
