### PR TITLE
Tabbed pages: Show config in code tab & Enable expressions for title and icon

### LINKED ISSUE #1276: Support Page config in Tabbed Pages
## The problem

Tabbed Pages cannot be configured as regular pages. They do not support the config property.

## Your suggestion

I'm a very new openhab beginner, so maybe this is not as easy as I imagine.

[Regular Pages](https://github.com/openhab/openhab-webui/blob/2b78c0910d97a13e53a604c8fc42198496d5bda5/bundles/org.openhab.ui/web/src/pages/settings/pages/layout/layout-edit.vue#L338) support to parsing of the config property.

[Tabbed Pages](https://github.com/openhab/openhab-webui/blob/0bcbd8c8ad81011b37a923f82235b25b3c913ea9/bundles/org.openhab.ui/web/src/pages/settings/pages/tabs/tabs-edit.vue#L152) only parse the tabs property.

Maybe it would be sufficient to enhance this model. (Edit: after some further trials: probably not)

## Your environment
I'm using the openHAB 3.2.0 Release Build.

### LINKED ISSUE #2103: [MainUI] Tabbed pages code tab in the UI does not show the config section
## The problem

Tabbed pages code tab in the UI does not show the config section. Therefore it's not possible to overwrite configurations.
See also: https://community.openhab.org/t/oh3-hide-navbar/115117/28

## Expected behavior

Config section should be shown in "Code" tab as for (mostly?) all configuration objects.

## Steps to reproduce

Create a tabbed page and go to the "Code" tab - you will not see the config section.

### LINKED ISSUE #2571: [mainui] Tabbed Pages do not support expressions in configuration options
So i was hoping to use an expression to customize the label in the tabbed page view, like `=items.Lights_All.state`, unfortunately this does not work as the tabbed page is not actually a component that uses the widget mixin that i think does the expression parsing.   Not sure how to fix this properly.   If someone could give a hint on the right way to support this, i could try and take a stab at fixing this.

 Besides labels supporting expressions, my end goal was to submit a PR that would also enable badging on the tabbed links (see screen shot) , but this is only useful if the configuration supports the jsep expression evaluation used in the widget-mixin. 

image

### LINKED ISSUE #2574: Sitemap editor has a lot of unused space
## The problem

Today I pulled the latest snapshot Docker image. The Sitemap editor wastes a lot of space:

grafik

I tried to reload without cache, but that didn't help.

## Steps to reproduce

1. Open Sitemap editor

## Your environment

```yaml
runtimeInfo:
  version: 4.2.0
  buildString: "Build #4075"
```

Firefox 125

### PR DESCRIPTION
**Pull request by florian-h05**
Makes the tabbed page config editable though the code tab: Resolves #1276. Resolves #2103.

Enables expression evaluation for tab title and icon: Resolves #2571.

### CODE REVIEW

**Comment by florian-h05** [comment]
Should I merge then?

**Comment by digitaldan** [comment]
Yes please!  I'll have a PR shortly with some badging for tabs too!

**Review by digitaldan — APPROVED** [review]
LGTM

**Comment by digitaldan** [comment]
Actually, i think should add the expression parser to 'tabs-edit.vue' as well,  so this works when editing?

**Comment by florian-h05** [comment]
Now that you mention it, I guess yes. I’ll have a look soon.

**Comment by florian-h05** [comment]
@digitaldan Done! I have added expression evaluation for the tabbed page editor. 
Please let me know when I should merge.

**Comment by digitaldan** [comment]
LGTM, and confirm this works nicely for me.  Merge away.

**Comment by florian-h05** [comment]
Now I'm looking forward to having badges :tada:

**Pull request merged**
