### PR TITLE
Adapt to core changes (addon.xml)

### PR DESCRIPTION
**Pull request by J-N-K**
Depends on #1452 
Depends on https://github.com/openhab/openhab-core/pull/3050

### CODE REVIEW

**Comment by J-N-K** [comment]
I didn't see an add-on for the iconset. Can it be installed separately?

**Comment by wborn** [comment]
The iconset is always installed to prevent issues, see https://github.com/openhab/openhab-distro/pull/1371.

**Comment by kaikreuzer** [comment]
@J-N-K Is there a special reason, why this PR is still marked as "WIP" in the title?
As a heads-up: I'd plan to finish my review on https://github.com/openhab/openhab-core/pull/3050 tomorrow and would then like to merge it - in consequence, we will have to merge the PRs in the other repos as well.

**Comment by J-N-K** [comment]
To be honest: I can't remember. I'll check tomorrow. After the core changes are approved I need a day or two to finalize the addons-PR since new addons were added since I created it. I just want to prevent double-work there in case something needs to be changed.

**Comment by J-N-K** [comment]
I fixed some minor issues, ready now from my side

**Comment by kaikreuzer** [comment]
Is the file `binding-config.vue` still required?

**Comment by J-N-K** [comment]
No, I removed it.

**Review by kaikreuzer — APPROVED** [review]

**Pull request merged**
