### PR TITLE
Removed HomeBuilder from the repo

### PR DESCRIPTION
**Pull request by kaikreuzer**
I am open to discuss this, but I think with the new UI there isn't really any need or use for the home builder ui anymore.

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by ghys** [comment]
Not disagreeing, but we could salvage a few things from it, like the existing i18n, or the code that translates a model into items definitions.

**Comment by kaikreuzer** [comment]
The code is still on the 2.5.x branch, so I think we can pick anything we'd like at any time - but no need to continue shipping it with the 3.0 distro.

**Comment by kaikreuzer** [comment]
@ghys Would you want to merge this one?

**Review by ghys — APPROVED** [review]
Yes - I was hoping for @kubawolanin's opinion, but I think it makes sense to remove unmaintained UIs (with no active code owners).

As said above the functionality would be eventually integrated in a different form, but hopefully reusing as much work as possible, in the main UI - like a "model bootstrapper".

I planned to consider it only after #394 in case there were a need for a localization infrastructure first. I doubt it will be ready for 3.0 though. But no need to include a deprecated UI in the distro even at the cost of temporarily losing this functionality, it would only add to the confusion.

**Pull request merged**
