### PR TITLE
Initial Blockly updates

### PR DESCRIPTION
**Pull request by bigbasec**
Blockly updates to cover some of what is here : https://github.com/openhab/openhab-webui/issues/810

This is a work in progress, and not complete by any means.

### CODE REVIEW

**Comment by ghys** [comment]
Looking very good already! 🚀

**Comment by bigbasec** [comment]
Thanks.   Things I'd like to be able to handle but not sure how we can do that yet are : 
- Map variables - To do this you'd need to create a list of name/value pairs, though I don't see a great way to do that yet.   
- Variables that can be used in multiple rules(global), though I don't know if that's possible

Things I still need to work on : 
- The popup for selecting audio sinks(I suck @ f7, this is hacked up version of the model popup if someone wants to help here that would be great)  It works, but I'm sure it's not pretty.  
- Create a popup for selecting a script(for call script)
- Create a popup for selecting a rule(for run rule)
- Adjust the Item popup to allow selecting multiple items(needed for maps and such)
- Implement now() a little better and build out date/time selection
- Finish up ephemeris
- Fully implement setCheck on some of the blocks to keep people from trying to do silly things
- Finish up some of the yet to be completed calls
- Documentation, if anyone wants to help with that.

**Comment by ghys** [comment]
> The popup for selecting audio sinks

For this one at least, maybe a popup is a little overkill here, and a simple [dynamic dropdown](https://developers.google.com/blockly/guides/create-custom-blocks/fields/built-in-fields/dropdown#dynamic_dropdowns) would suffice. People only have a handful of sinks anyway.

**Comment by bigbasec** [comment]
Yea, I was actually looking to have a common one that would handle all the different types of popups that would be required here.   And since there was already one for the model(based on a treeview, which I thought was overkill) I modified it.   

From a UI/UX standpoint I thought that having all sorts of different popups for things would be weird.   Plus, with f7 I have no idea what I'm doing, so that doesn't help much, haha

**Comment by bigbasec** [comment]
> > The popup for selecting audio sinks
> 
> For this one at least, maybe a popup is a little overkill here, and a simple [dynamic dropdown](https://developers.google.com/blockly/guides/create-custom-blocks/fields/built-in-fields/dropdown#dynamic_dropdowns) would suffice. People only have a handful of sinks anyway.

I thought about this some more, and just really for a learning experience I'm going to go with a dynamic dropdown.   I have 22 sinks here, though I'm sure that's more than the normal.  I'll leave the code for the popup for now, though I think having both options there would benefit.   

Any way we could poke someone to see if we could get an example for some of the unknown issues above?   Sorry, don't know all the players here.   It would be great to have an example of a variable being able to be used across multiple rules.   

Also, I'm thinking I should be using the model popup for selecting multiple items as it's already there and coded to handle that.   You ok with that?   I'm still trying to come up with a good way to handle that stuff in blockly but having that out of the way should be a step forward.   

At this point I think I could create about 95% of my rules with what is here.   (and I have just about 110 individual rules)

**Comment by ghys** [comment]
@bigbasec in case you missed it, I have rebased your changes based on the recent code and cleaned up what was necessary, so I could test your new blocks.

Overall the way they're organized looks good, as an abundance of caution I'd still like to try them all, because I'd want to be sure they work properly. In any case feel free to pull the latest changes and resume working on it if you feel like doing so.

**Comment by elrusso184** [comment]
Thank you @bigbasec for takeing care about the enhancement of blockly. 
Is there a chance to get it into openhab regular updates. I can imagine it would be really appreciated by the community. As far as I have seen, it will be a big step forward and make more use out of the blockly possibility. There are a lot of people in the community, which are able to code such good stuff, or the others like I’am, able to read the code but lacking the possibility to write it ☹, although I can code in c++; vba or industrial pls controllers. I know everybody is spending there free time in this projects, so again thanks. The code looks nearly finished so it might be some last effort to complete what has to be completed and merge it into the next update.

**Comment by stefan-hoehn** [comment]
@bigbasec 
"The code looks nearly finished " -> Is this the final state of your implementation and should this be merged?
Do you mind providing a summary of the functionality that you have or you intended to implement?
(the reason behind that is that I intend to extend Blockly even further)

**Comment by ghys** [comment]
Most of the code of this PR has been included in #1179 and merged (with proper credit/sign-off lines), so I think this one can be closed now.

**Pull request closed without merging**
