### PR TITLE
[BasicUI] Add preview color to Colorpicker widget

### PR DESCRIPTION
**Pull request by lolodomo**
Also clenup class ColorpickerRenderer

### CODE REVIEW

**Comment by lolodomo** [comment]
The new rendering of the widget:

image

image

This is the same circle as in the Colortemperaturepicker widget.

**Comment by kaikreuzer** [comment]
Why would we need the palette button here at all? It would feel more natural to me that I click on the colored circle if I want to change the color...

**Comment by lolodomo** [comment]
I was not sure but it was also what I was thinking ;)
Note that we should keep something consistent with the new Colortemperaturepicker widget.

Do you think I should just keep the new circle or rather keep the rectangle button but with the current color inside?

**Comment by kaikreuzer** [comment]
> Note that we should keep something consistent with the new Colortemperaturepicker widget.

Agreed. Having a look at it, I would actually say the same there: The picker button is redundant if the user could simply click on the colored circle.

> Do you think I should just keep the new circle or rather keep only the rectangle button but with the current color inside and no icon ?

I don't have a strong opinion. The circle already "invites" the user to click on it, but we could also stick to the rectagular look of the buttons - this might be the more consistent option.

**Comment by lolodomo** [comment]
Kai, it is changed:

image

image

**Review by kaikreuzer — APPROVED** [review]
Looks nice, I like it!
Thanks. 😄

**Comment by felixschndr** [comment]
This looks very nice, thank you very much @lolodomo! Maybe we can built something like this for the other clients, looking at the android app @mueller-ma ? That's be great

**Comment by mueller-ma** [comment]
I'm pretty sure that there was a preview like this when I merged @maniac103 PR that implements this new widget.

**Comment by maniac103** [comment]
Yes, the Android app does it like that already (displaying the color preview instead of the palette), with one tweak: if the light is off (brightness = 0) or the state is unknown, the palette is shown instead of the preview because a black preview looks somewhat ugly.

**Pull request merged**
