### PR TITLE
Fix color picker not displayed correctly

### LINKED ISSUE #2134: Color Widget lacks default module setting
When creating an item that has color state which leads to the default of a oh_colorpicker_card the widget is created in a wrong way

image

The root cause is the missing module setting

image

The setting should therefore as follows by default

```
value: ""
config:
  modules:
    - wheel
```

as such 
image

which then reveals a working color widget:

image

### PR DESCRIPTION
**Pull request by florian-h05**
Fixes #2134.
Regression from #1989.

### CODE REVIEW

**Comment by Mark-VG** [comment]
Hi.
Any chance of a jar for this to try before merge. Hoping it fixes the issue I am seeing.

**Comment by florian-h05** [comment]
Sure: https://we.tl/t-safSYPMgG8.

**Comment by Mark-VG** [comment]
> Sure: https://we.tl/t-safSYPMgG8.

Thank you.

Same instructions as firvtge other one?

Deploy it to your addons folder, and log into the Karaf console:

bundle:list org.openhab.ui 

Stop the milestone bundle, restart the other one.

bundle:stop ID and bundle:restart ID.

**Comment by florian-h05** [comment]
Exactly.
You can also stop the milestone bundle before dropping the JAR into the addons folder.

**Comment by Mark-VG** [comment]
Thank you so much. Seems to have fixed my issue too :-) Also the reload doe snot happen any more when setting the "H".

image

**Comment by florian-h05** [comment]
Self-merging this small PR to finally fix the broken color picker. 

Please note that the added `width: 100%` is already applied to the color picker‘s div, it is just missing for the wrapping div.

**Pull request merged**
