### PR TITLE
charts - generalize evaluating expressions for charts

### PR DESCRIPTION
**Pull request by crnjan**
This is a re-take from https://github.com/openhab/openhab-webui/pull/1638 where I managed to mess up my git repo, sorry for double work and inconvenience :(

PR is based on https://github.com/openhab/openhab-webui/pull/1419. Also contains fixes from https://github.com/openhab/openhab-webui/pull/1634.

fixes https://github.com/openhab/openhab-webui/issues/1418
fixes https://github.com/openhab/openhab-webui/issues/1295
fixes https://github.com/openhab/openhab-webui/issues/1102
fixes https://github.com/openhab/openhab-webui/issues/1072

Went through cases reported in above issues and seems to work now. Also, as far as I tested (so far) locally with my setup seems to work - but probably don't have all use-cases setup so probably missed something - therefore would be much appreciated if any volunteer tries it out too, thank you!

### CODE REVIEW

**Comment by ghys** [comment]
LGTM but since:

> Also contains fixes from https://github.com/openhab/openhab-webui/pull/1634.

I'll merge after the problems reported there are solved to avoid regressions with the default rrd4j service.

**Comment by cweitkamp** [comment]
The regression in RRD4J will be solved by https://github.com/openhab/openhab-addons/pull/14238 (see https://github.com/openhab/openhab-webui/pull/1634#issuecomment-1398257809).

**Comment by crnjan** [comment]
> LGTM but since:
> 
> > Also contains fixes from #1634.

Decided to include those changes too, otherwise there would be a conflict, thx for checking.

**Review by ghys — APPROVED** [review]
Since https://github.com/openhab/openhab-addons/pull/14238 is merged (haven't had the opportunity to check as I'm not running 4.0-SNAPSHOT in production where I have plenty of data to test, I'll trust it's looking good now).

Nice list of fixed issues here btw ;)

fixes https://github.com/openhab/openhab-webui/issues/1418
fixes https://github.com/openhab/openhab-webui/issues/1295
fixes https://github.com/openhab/openhab-webui/issues/1102
fixes https://github.com/openhab/openhab-webui/issues/1072
fixes https://github.com/openhab/openhab-webui/issues/912

**Comment by crnjan** [comment]
Using rrd4j (as default provider) and requesting i.e.
```
http://<ip>/rest/persistence/items/gBasement_BoilerRoom_HP_RAD_InOperation_HP?starttime=2022-12-31T23%3A00%3A00.000Z&endtime=2023-01-31T22%3A59%3A59.999Z&boundary=true 
```
will return 
```
{
"cause1":"java.lang.OutOfMemoryError: Java heap space",
"servlet":"cxf-servlet",
"cause0":"org.apache.cxf.interceptor.Fault: Java heap space",
"message":"org.apache.cxf.interceptor.Fault: Java heap space",
"url":"/rest/persistence/items/gBasement_BoilerRoom_HP_RAD_InOperation_HP",
"status":"500"
}
```
 and requesting the same without the `boundary` parameter will return datapoints ...

Maybe @cweitkamp?

Not sure if I should rather open a new issue, please let me know.

**Pull request merged**
