### PR TITLE
[BasicUI] Add a new header line for image, chart and video elements.

### LINKED ISSUE #1367: [Sitemap] Missing chart labels
*@Boby71 commented on Jan 9, 2021, 4:14 PM UTC:*

## The problem

When using a chart in a sitemap (no matter if created in the UI or .sitemap file), the title won't be displayed anymore:
UI:
[image](https://user-images.githubusercontent.com/22266373/104099928-42dc2980-529d-11eb-9bb0-12416db92d7d.png)

Code:

```
    Group label="Corona Statistik AT" {
        Text item=CoronaStatisticsAT_NewCases label="Neue Fälle"
        Text item=CoronaStatisticsAT_NewDeaths label="Neue Tote"
        Text item=CoronaStatisticsAT_Updated label="Daten vom [%1$td.%1$tm.%1$tY, %1$tH:%1$tm]"
        Chart icon="chart" item=CoronaStatisticsAT_NewCases refresh=60000 service="rrd4j" period="W" label="Neue Fälle"
    }

```

Result: Chart is being displayed, but without given title:
[image](https://user-images.githubusercontent.com/22266373/104100873-8a62b580-529d-11eb-995d-8da74f66123b.png)

## Expected behavior

When label= is being used, the label should be displayed as well

## Steps to reproduce

1.  Create a chart with a lable
2.  Check page in basicUI

## Your environment

```
runtimeInfo:
  version: 3.1.0
  buildString: "Build openhab/openhab-core#2127"
locale: de_AT
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+88-CA
  osName: Linux
  osVersion: 5.4.83-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 84129568
  totalMemory: 194772992
bindings:
  - amazonechocontrol
  - coronastats
  - daikin
  - denonmarantz
  - enigma2
  - exec
  - harmonyhub
  - http
  - ipcamera
  - mqtt
  - netatmo
  - network
  - ntp
  - systeminfo
  - unifi
  - wled
  - worxlandroid
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de
    languages:
      - de
      - de-DE
      - en
      - en-US
      - en-AU
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/87.0.4280.141 Safari/537.36
timestamp: 2021-01-09T16:11:12.238Z

```

## Browser console

[image](https://user-images.githubusercontent.com/22266373/104102099-e9c0c580-529d-11eb-92f5-f79c365c23e9.png)

## Browser network traffic

[image](https://user-images.githubusercontent.com/22266373/104102421-06f59400-529e-11eb-8bc3-affcaa917b6c.png)

## Additional information

*This issue was moved by [ghys](https://github.com/ghys) from [openhab/openhab-webui#781](https://github.com/openhab/openhab-webui/issues/781).*

### LINKED ISSUE #1939: [Basic UI] Change settings for loaded Charts
In openHAB-Android for Chart items, once loaded, I can select in the user interface to show or hide the legend, or alter the default duration for the displayed data - to one, four, eight, twelve hours, one, two, three days.

Please add an option in Basic UI for charts, which permit the user to change the duration for the displayed data (1 hour, 4h, 8h, 12h and so on), and to toggle the “legend”

### PR DESCRIPTION
**Pull request by lolodomo**
Header line for video element contains icon and label.

Header line for image element contains icon, label and a button to switch between no upscale and upscale of the image. Header line for chart element contains icon, label and 4 buttons:
 - one button to show or hide the legend
 - one button to change the time range
 - one button to switch between no upscale and upscale of the chart
 - one button to refresh the chart

Fix handling of iconcolor and labelcolor parameters for mapview and webview elements.

For image and chart elements, the header line is always present so that user has an access to its buttons.
For video, mapview and webview elements, if the label is empty, the header line is hidden.

For chart and image elements, there is now no upscale applied by default (tablet/phone devices) but a button allows upscaling.

Closes #1939
Fixes #1367
Also related to #1930

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
Considering the following sitemap:
```
sitemap test8 label="Tests"
{
	Frame {
		Switch item=TestCommand label="Color icon []" icon="colorpicker" mappings=[10="red", 11="green", 12="Other"]
		Switch item=TestCommand2 label="Color label []" icon="colorpicker" mappings=[10="blue", 11="orange", 12="Other"]
		Switch item=TestSwitch label="Show widgets []" mappings=[OFF="Without label", ON="With label"]
		Input item=TestLocation inputHint="text" icon="none"
	}
	Frame label="Chart" {
		Chart item=TestNumber period=W legend=true refresh=60000 label="Chart example with a very long label" labelcolor=[TestCommand2==11="orange",TestCommand2==10="blue"] icon="material::show_chart" iconcolor=[TestCommand==11="green",TestCommand==10="red"] visibility=[TestSwitch==ON]
		Chart item=TestNumber period=W legend=true refresh=60000 label="" visibility=[TestSwitch==OFF]
	}
	Frame label="Image" {
		Image url="https://www.openhab.org/openhab-logo-square.png" label="Image example with a very long label for the header" labelcolor=[TestCommand2==11="orange",TestCommand2==10="blue"] icon="material::favorite" iconcolor=[TestCommand==11="green",TestCommand==10="red"] visibility=[TestSwitch==ON]
		Image url="https://www.openhab.org/openhab-logo-square.png" visibility=[TestSwitch==OFF]
	}
	Frame label="Map" {
		Mapview item=TestLocation label="Map view example with a very long label for the header" labelcolor=[TestCommand2==11="orange",TestCommand2==10="blue"] icon="material::home" iconcolor=[TestCommand==11="green",TestCommand==10="red"] visibility=[TestSwitch==ON]
		Mapview item=TestLocation label="" visibility=[TestSwitch==OFF]
	}
	Frame label="WEB" {
		Webview url="https://www.openhab.org/" height=10 label="WEB view example with a very long label for the header" labelcolor=[TestCommand2==11="orange",TestCommand2==10="blue"] icon="material::home" iconcolor=[TestCommand==11="green",TestCommand==10="red"] visibility=[TestSwitch==ON]
		Webview url="https://www.openhab.org/" height=10 visibility=[TestSwitch==OFF]
	}
	Frame label="Video" {
		Video url="http://techslides.com/demos/sample-videos/small.mp4" label="Video example with a very long label for the header" labelcolor=[TestCommand2==11="orange",TestCommand2==10="blue"] icon="material::home" iconcolor=[TestCommand==11="green",TestCommand==10="red"] visibility=[TestSwitch==ON]
		Video url="http://techslides.com/demos/sample-videos/small.mp4" visibility=[TestSwitch==OFF]
	}
}
```

First the result when there is no label or an empty label for a widget:
image
image
image

And now with a label defined:
image
image
image

After removing the legend, changing time range to 1 day and upscaling the chart::
image

After upscaling the image:
image

**Comment by lolodomo** [comment]
Another example to show when they are in the same frame:
```
sitemap test7 label="Tests header line"
{
	Frame {
		Input item=TestLocation inputHint="text" icon="none"
		Chart item=TestNumber period=4h refresh=60000 label="Chart for TestNumber" icon="chart"
		Mapview item=TestLocation label="Map view example with a very long label for the header" icon="material::home"
	}
}
```
image

**Comment by lolodomo** [comment]
> My intention was to use icon in all buttons but some material icons I would like to use are missing. I will update a second step when all material icons are accessible.

Let's wait for the merge of #2016 so that I can include the icons I would like for the chart header line.

**Comment by mueller-ma** [comment]
It feels a bit strange to me that one has to add a label to a chart to get the new buttons. Maybe show the header for charts always?

**Comment by lolodomo** [comment]
> It feels a bit strange to me that one has to add a label to a chart to get the new buttons. Maybe show the header for charts always?

Yes, you're right. Same for image. I will change that.

**Comment by lolodomo** [comment]
I have updated all the screenshots.
The PR is now ready for a review & merge.

**Comment by lolodomo** [comment]
I discovered that the update of label/icon color is broken for the colorpicker with this PR. Put again this PR in WIP.

**Comment by lolodomo** [comment]
> I discovered that the update of label/icon color is broken for the colorpicker with this PR. Put again this PR in WIP.

It was just a mismatch between undefined and null in JavaScript.
The PR is ready again.

**Review by kaikreuzer — APPROVED** [review]
That's a great enhancement, thank you!

**Comment by lolodomo** [comment]
Thank you for the review Kai.

**Pull request merged**
