### PR TITLE
Adding Control-S save feature to item edit

### PR DESCRIPTION
**Pull request by bigbasec**
Just adding the Cntl-S save feature to item edit so it's more in line with the rest of the GUI.

### CODE REVIEW

**Review by bigbasec — COMMENTED** [review]
I must have botched the PR and committed local changes that aren't required.   bundles/org.openhab.ui/web/src/pages/settings/items/item-edit.vue is the only file that would be changed here.   I can resubmit if needed.

**Comment by ghys** [comment]
Yes, please make sure not to include files outside the scope of the PR. You can revert them with the suggestions here: https://stackoverflow.com/questions/215718/how-can-i-reset-or-revert-a-file-to-a-specific-revision

**Comment by bigbasec** [comment]
> Yes, please make sure not to include files outside the scope of the PR. You can revert them with the suggestions here: https://stackoverflow.com/questions/215718/how-can-i-reset-or-revert-a-file-to-a-specific-revision

Thank you.   All fixed up now.

**Review by ghys — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
