### PR TITLE
[basicui] Remove Roboto font as unused by the app

### LINKED ISSUE #1273: OH 3.2 - 404 error for fonts and icon/number
## The problem
I get some 404 errors in Chrome Console in basicUI
image

(basicUI load fine I just saw this errors in console)

## Expected behavior
No 404 errors in console ;-)

## Steps to reproduce
Start Developer Tool (F12) and reload your basicUI

## Your environment

```
root@openhab:~# openhab-cli info

Version:     3.2.0 (Build)

User:        openhab (Active Process 5900)
User Groups: openhab tty dialout audio

Directories: Folder Name      | Path                        | User:Group
             -----------      | ----                        | ----------
             OPENHAB_HOME     | /usr/share/openhab          | openhab:openhab
             OPENHAB_RUNTIME  | /usr/share/openhab/runtime  | openhab:openhab
             OPENHAB_USERDATA | /var/lib/openhab            | openhab:openhab
             OPENHAB_CONF     | /etc/openhab                | openhab:openhab
             OPENHAB_LOGDIR   | /var/log/openhab            | openhab:openhab
```

I'm not an expert but is this the data for webui?
```
jar tf /var/lib/openhab/tmp/kar/openhab-addons-3.2.0/org/openhab/ui/bundles/org.openhab.ui.habpanel/3.2.0/org.openhab.ui.habpanel-3.2.0.jar |grep Roboto
web/fonts/roboto/Roboto-Regular.woff2
web/fonts/roboto/Roboto-Regular.eot
web/fonts/roboto/Roboto-Regular.ttf
web/fonts/roboto/Roboto-Regular.svg
web/fonts/roboto/Roboto-Regular.woff
```
Then we have to add "/roboto" to roboto.css.
But I don't have an idea for 404 on numbers.

### PR DESCRIPTION
**Pull request by lolodomo**
Fix #1273

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@kaikreuzer : can you please review ? It is related to our discussion in #1533

**Review by kaikreuzer — APPROVED** [review]
Thank you.

**Comment by dilyanpalauzov** [comment]
When I call
```console
$ git grep -i roboto[^k]

bundles/org.openhab.ui.basic/NOTICE:Roboto Font Face 2.01289
bundles/org.openhab.ui.basic/package-lock.json:        "roboto-fontface": "^0.10.0"
bundles/org.openhab.ui.basic/package-lock.json:    "node_modules/roboto-fontface": {
bundles/org.openhab.ui.basic/package-lock.json:      "resolved": "https://registry.npmjs.org/roboto-fontface/-/roboto-fontface-0.10.0.t>
bundles/org.openhab.ui.basic/package-lock.json:    "roboto-fontface": {
bundles/org.openhab.ui.basic/package-lock.json:      "resolved": "https://registry.npmjs.org/roboto-fontface/-/roboto-fontface-0.10.0.t>
bundles/org.openhab.ui.basic/package.json:    "roboto-fontface": "^0.10.0"
bundles/org.openhab.ui.basic/src/main/resources/web/mdl/material.min.css:@charset "UTF-8";html{color:rgba(0,0,0,.87)}::-moz-selection{b>
bundles/org.openhab.ui.basic/src/main/resources/web/mdl/material.min.css.map:{"version":3,"sources":["styleguide.css","styleguide.scss">
bundles/org.openhab.ui.habot/NOTICE:Roboto Font Face 2.01289
bundles/org.openhab.ui.habot/web/quasar.conf.js:      ctx.theme.mat ? 'roboto-font' : null,
bundles/org.openhab.ui.habpanel/NOTICE:Roboto Font Face 2.01289
bundles/org.openhab.ui.habpanel/web/app/widgets/clock/clock.scss:    font-family: Roboto;
bundles/org.openhab.ui.habpanel/web/app/widgets/timeline/timeline.widget.js:                    var textWidth = getTextWidth(label, "no>
```
and much more references for habpanel.

Provided that Roboto Fonts are not used by org.openhab.ui.basic, and probably also by habot, can all the references there be removed, unless their presence is reasonable? (I do not know if it is reasonable to have the above mentions of `roboto` still in the code).

**Comment by lolodomo** [comment]
Regarding the NOTICE file, that is correct, I forgot to remove reference to Roboto font in that file.

Regarding package-lock.json and package.json files, I am not very familiar with these files and I have always ignore them !!! The problem is that the file in Git and the generated file (package-lock.json) after building BasicUI appear fully different, certainly due to a different encoding used. I thought until now that package-lock.json was a generated file and not a source file ! Is it a source file ?
I agree with you that roboto is present in these 2 files.
I will try to understand what are exactly these files. If someone wants to explain to me, he is welcome.

**Comment by dilyanpalauzov** [comment]
package.json tells the JavaScript package managers (npm, yarn …) which modules are required, without referencing indirect requirements.

When npm install these modules, it creates package-lock.json including the versions of all installed - direct and indirect - dependencies.  If yarn1 were used as package manager, it would have created yarn.lock instead.

Whether or not to include package-lock.json in the version management, is biased, there are different opinions.

In any case calling `npm uninstall roboto-fontface` should remove `roboto-fontface` from both package.json and package-lock.json.

**Comment by florian-h05** [comment]
@lolodomo 
What @dilyanpalauzov wrote is correct, a simple `npm rm roboto-fontface` should remove it from both files.

FYI: You should not mess with `package-lock.json` manually, but IMO it has to be included in Git to ensure that everyone has the exact same environment (i.e. package & dependency versions installed). 
If you don’t have a package-lock, npm install will install all dependencies defined in the `package.json` using a version matching the semver regex in that file. 

If you don’t have your package-lock in git this happens:
- package.json defined `somepackage` as dependency with version string `^1.2.6` (there are other options available, but I think that is the default)
- `npm install` will then install the latest version matching that version specification, e.g. `1.2.8`, and save that to your local package-lock
- Some time later your npm project is build. Without a package-lock, the build server will use the latest version matching the specification, e.g. `1.10.5`. This is not the version you were testing and developing your project with — may cause problems (breaking changes should only happen with major version number changes if the package follows semver, and npm won’t install any other new major than your `^1.2.6` package.json defines)

**Comment by lolodomo** [comment]
Thank you a lot for the explanations.

Unfortunately, the suggested command does not work:
```
$ ls
'BasicUI Setup.launch'   NOTICE      doc/          gulpfile.js   node_modules/   package-lock.json   pom.xml   target/
 CONTRIBUTING.md         README.md   eslint.json   node/         npm_cache/      package.json        src/      web-src/

$ npm uninstall roboto-fontface
npm WARN org.openhab.ui.basic@3.0.0 No repository field.
npm WARN org.openhab.ui.basic@3.0.0 No license field.

$ grep oboto *.json
package-lock.json:        "roboto-fontface": "^0.10.0"
package-lock.json:    "node_modules/roboto-fontface": {
package-lock.json:      "resolved": "https://registry.npmjs.org/roboto-fontface/-/roboto-fontface-0.10.0.tgz",
package-lock.json:    "roboto-fontface": {
package-lock.json:      "resolved": "https://registry.npmjs.org/roboto-fontface/-/roboto-fontface-0.10.0.tgz",
package.json:    "roboto-fontface": "^0.10.0"
```

**Comment by florian-h05** [comment]
`npm uninstall roboto-fontface` works for me -- the grep does not return anything.

**Comment by lolodomo** [comment]
> `npm uninstall roboto-fontface` works for me -- the grep does not return anything.

Then can I ask you to submit a PR for what I forgot ?

**Comment by florian-h05** [comment]
Done: #1719.

**Comment by lolodomo** [comment]
This PR addressed BasicUI not HABot.

**Pull request merged**
