### PR TITLE
Fix startlevel parameter casing

### PR DESCRIPTION
**Pull request by ghys**
Signed-off-by: Yannick Schaus <github@schaus.net>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Did you see https://github.com/openhab/openhab-core/pull/1923/files#diff-a6a3c1453732714bbb77a8d6d87afcb0de30787cb082f93dc71ebb7310a3e580R14-R35?

Do you actually need to duplicate the information in the UI? If so, it should imho be aligned with what we have in the core description (texts as well as only levels >40).

**Comment by ghys** [comment]
No - but I did it before you added the options... let me see if I can replace it quickly with the sheet for the module.

**Comment by ghys** [comment]
Okay, that's the last one 💪

**Comment by kaikreuzer** [comment]
Awesome, you used every minute before the RC1 merge stop ;-)

**Pull request merged**
