### PR TITLE
Improved sitemap handling in MainUI

### PR DESCRIPTION
**Pull request by mherwege**
Signed-off-by: Mark Herwege [mark.herwege@telenet.be](mailto:mark.herwege@telenet.be)

Closes [#1538](https://github.com/openhab/openhab-webui/issues/1538)
Closes [#748](https://github.com/openhab/openhab-webui/issues/748)
Closes [862](https://github.com/openhab/openhab-webui/issues/862)

This PR improves sitemap handling for strings with blanks and special characters.
It also fixes attributes with value 0.

### CODE REVIEW

**Comment by ghys** [comment]
@mherwege thanks for the fixes!

Since this code is becoming quite complex and there's been a few gotchas I figured it was as good a time as any to finally introduce some unit tests. I added 3 suites to test _dslUtil.js_ (render a sitemap definition from a component), _sitemap-code.vue_ (parse a sitemap definition into a component with Nearley), and _sitemap-edit.vue_ (your validation routine).

Can you please pull (rebase), `npm install` the missing dependencies, and check that Jest (the test framework, https://jestjs.io) works correctly. You have a number of options:
- `npm run test:unit:watch` (it will automatically re-run relevant tests as you save)

- `npx majestic` (install & run Majestic, https://github.com/Raathigesh/majestic)
  
  image

- another IDE option like the Jest extension for VS Code (which also lets you debug with breakpoints etc.)

  image

The test suites that use https://v1.test-utils.vuejs.org to mount Vue components can take up to 30 seconds or so to run the first time, afterwards they will run faster (less than 10 seconds).

If it works for you it would be great if you could improve those and come up with more things to test covering edge cases in this area (mappings, color & visibility, placement of quotes, etc.)! 🙂

**Comment by mherwege** [comment]
Cool! I got it working with the JEST extension in VSCode. The tests all pass nicely. I will try to create more tests over the next few days.

**Comment by mherwege** [comment]
@ghys I added a series of tests for you to review.
I did have to make a slight change, creating beforeEach and afterEach methods, to avoid the individual tests to impact each other. Probably important to note for others that try to set up tests. I hope I have done that right (it is a complete discovery for me).
Can we get these fixes in 3.4?

**Comment by ghys** [comment]
Excellent, many thanks! Nice to see some test coverage for this!

> I did have to make a slight change, creating beforeEach and afterEach methods, to avoid the individual tests to impact each other.

Jest runs test suites in parallel by default but within one the individual tests will be run sequentially in order.
So it's up to you if you want to keep and reuse the wrapper, if you're sure previous state won't have an impact, or create a new one to start with a clean state (which is somewhat costly thus slower):

image

**Review by ghys — APPROVED** [review]

**Pull request merged**
