### PR TITLE
Add a dirty indicator on the title bar

### PR DESCRIPTION
**Pull request by jimtng**
image

### CODE REVIEW

**Review by florian-h05 — APPROVED** [review]
LGTM, thanks for this nice addition!

FYI you forgot chart and tab edit, I have added the indicator there as well.

**Comment by florian-h05** [comment]
I think this should be added to the docs, but I don't know where its best to put it.
@rkoshak Do you have an idea?

**Comment by rkoshak** [comment]
Does this only apply to rules or things, items, and  transformations too?

If only rules I think the best place is under MainUI -> Settings -> Rules.

If all of these, a sentence probably needs to be added to each of these pages under MainUI -> Settings or a new section added to MainUI -> Settings to explain it.

**Comment by florian-h05** [comment]
It applies to all of these. 
I guess let’s then put it into Main UI -> Settings.

**Comment by florian-h05** [comment]
See https://github.com/openhab/openhab-docs/pull/2345 for documentation.

**Pull request merged**
