### PR TITLE
Add Control-S to service settings page

### PR DESCRIPTION
**Pull request by bigbasec**
Very simply adds the control-S to the page to make it more in line with some of the other pages.

### CODE REVIEW

**Comment by ghys** [comment]
Looks like there's something wrong, you should rebase!

**Comment by bigbasec** [comment]
> Looks like there's something wrong, you should rebase!

Should be ok now.   Thanks!

**Comment by ghys** [comment]
I'm sorry... but I still see changes that have nothing to do with the PR ;)
Only the last commit should be included!
Do something like:
```
git fetch origin
git reset --hard origin/main
git cherry-pick 46a6e1a
```

**Comment by bigbasec** [comment]
> I'm sorry... but I still see changes that have nothing to do with the PR ;)
> Only the last commit should be included!
> Do something like:
> 
> ```
> git fetch origin
> git reset --hard origin/main
> git cherry-pick 46a6e1a
> ```

Git hates me.   No idea what that did, but it seems like it made things worse.  Close this PR and I'll submit another one for this change.

**Comment by bigbasec** [comment]
https://github.com/openhab/openhab-webui/pull/867

**Pull request closed without merging**
