### PR TITLE
`oh-knob`: Change dottedPath prop to text

### PR DESCRIPTION
**Pull request by stefan-hoehn**
property needs to be text to be able to add the css stroke-dasharray style

### CODE REVIEW

**Review by florian-h05 — APPROVED** [review]

**Comment by hmerk** [comment]
@stefan-hoehn  Sorry to bother you but still can‘t figure out how to use the dotted path.
can you give me an example please…

**Comment by stefan-hoehn** [comment]
Sure.

Use "10 1 10 5" and you get

image

Use just "5" and you get

image

or "1 10" and you get

image

Does that help?

**Comment by hmerk** [comment]
No, does not work. Can you please post the complete yaml of your widget…

**Comment by stefan-hoehn** [comment]
`  - component: oh-block
    config: {}
    slots:
      default:
        - component: oh-grid-row
          config: {}
          slots:
            default:
              - component: oh-grid-col
                config: {}
                slots:
                  default:
                    - component: oh-knob-card
                      config:
                        useSliderControl: true
                        item: slider1
                        dottedPath: 5`

I am not sure if I have the refactored version of @florian-h05 already installed. Florian can you check this as well?

**Comment by florian-h05** [comment]
I've just checked this on my system (I am on a SNAPSHOT from last weekend, so my refactoring is included) and it works. The dottedPath property is saved as text on my system.

**Comment by hmerk** [comment]
This my config on SNAPSHOT 3382, updated today and it is not working on my iPad or iPhone: 

config:
  label: Overview
blocks:
  - component: oh-block
    config: {}
    slots:
      default:
        - component: oh-grid-row
          config: {}
          slots:
            default:
              - component: oh-grid-col
                config: {}
                slots:
                  default:
                    - component: oh-label-card
                      config:
                        footer: Morgen
                        item: OneCallAPIweatherandforecast_ForecastTomorrow_Sunrise
                        title: Sonnenaufgang
  - component: oh-block
    config: {}
    slots:
      default:
        - component: oh-grid-row
          config: {}
          slots:
            default:
              - component: oh-grid-col
                config: {}
                slots:
                  default:
                    - component: widget:winux_lightcard
                      config:
                        itemname: Testgerät
  - component: oh-block
    config: {}
    slots:
      default:
        - component: oh-grid-row
          config: {}
          slots:
            default:
              - component: oh-grid-col
                config: {}
                slots:
                  default:
                    - component: oh-knob-card
                      config:
                        item: ShellyTRVOffice_targetTemp
                        min: 15
                        max: 30
                        step: 1
                        releaseOnly: true
                        responsive: true
                        lineCap: round
                        dottedPath: 10 1 10 5
                        handleShape: round
                        size: 100
masonry: null
grid: null
canvas: null

**Comment by hmerk** [comment]
ok, it is working if I remove most of the config params, will readd them one by one to see which one breaks the dottedPath…

**Comment by hmerk** [comment]
it is the „ lineCap: round“ config breaking the dottedPath

**Comment by stefan-hoehn** [comment]
Figuring out what the root cause is was kind of tricky. It actually goes down to how the Circle is drawn. It uses an svg and a simplified version looks as follows

```
<svg viewBox="0 0 1000 200">
  <line x1="10" x2="990" y1="100" y2="100" stroke-width="4" stroke='black'
    stroke-dasharray="19" stroke-linecap="round"/>
  <path  fill="transparent"
    d="M 36.79092927350955 142.45333323392336 A 75 75 0 1 1 133.20907072649047 142.45333323392333"
    stroke-dasharray="19"
    style="stroke: rgb(4, 238, 238);" stroke-linecap="square" stroke-width="20">    
  </path>  
</svg>
```

Note that I the circle is drawn by the PATH element - I added a LINE element. 
It seems that **stroke-dasharray** and **stroke-linecap** go well together in a LINE element but don't seem to work in a PATH element. 

Copy the above code into a file and open it in a browser and the dotted-lines disappear in the path element, though they stay in the line element. Now remove the stroke-linecap in the PATH and they come back. I haven't found any indication if this is a bug or part of the SVG specification.

To put it in a nutshell: It seems stroke--dasharry and strokelinecap cannot be used together.

**Comment by hmerk** [comment]
Thanks for looking into it @stefan-hoehn.
It is not that important, just should be added to the docs, so nobody else will face the same issue.

**Comment by florian-h05** [comment]
@hmerk 
The docs for this param should be changed there:
https://github.com/openhab/openhab-webui/blob/cb0436bdca523f3bcb745a056a4277a8091b179b/bundles/org.openhab.ui/web/src/assets/definitions/widgets/system/knob.js#L36

After this, the docs need to be regenerated as described here: https://github.com/openhab/openhab-webui/blob/main/bundles/org.openhab.ui/CONTRIBUTING.md#documentation--resources.

I can review and merge a PR.

**Pull request merged**
