### PR TITLE
Blockly Editor: combine renderer selection and show item label icons

### PR DESCRIPTION
**Pull request by jimtng**
The current icons are too crowded for mobile devices. This PR combines the renderer choice and the show labels into one icon.

Before
image

After
image

### CODE REVIEW

**Comment by jimtng** [comment]
The second commit capitalizes the renderer name. I think it looks nicer

image

**Comment by florian-h05** [comment]
For mobile phones, this looks really good!
I however wonder if the options however shouldn’t stay separated on big enough screens for faster access.

**Comment by jimtng** [comment]
> I however wonder if the options however shouldn’t stay separated on big enough screens for faster access.

I agree. Just need to add more code. I'll add that tomorrow.

**Comment by jimtng** [comment]
It wasn't too hard, so I've made the changes.

On desktop it now looks like this (with an icon instead of the name)
image

**Review by ghys — APPROVED** [review]
It does look good, thank you!

**Pull request merged**
