### PR TITLE
[BasicUI] Implement new sitemap element Colortemperaturepicker

### PR DESCRIPTION
**Pull request by lolodomo**
Related to openhab/openhab-core#3891

### CODE REVIEW

**Comment by lolodomo** [comment]
Here is the rendering of the new widget:

image

When clicking on the button, the following pop-up is displayed:

image

**Comment by mueller-ma** [comment]
I'd prefer to have a preview of the state as actual color and as Kelvin, as I (and probably many other people) don't know how 4500 K look like. Suggestion:

382481287-49ab7a5d-ed81-4611-9901-c056b156c15e

**Comment by lolodomo** [comment]
> I'd prefer to have a preview of the state as actual color and as Kelvin, as I (and probably many other people) don't know how 4500 K look like. Suggestion:

Very good idea, I will do that.
I will also keep the value.

**Comment by lolodomo** [comment]
Conversion from Kelvin to RGB is not done in frontend. Backend is providing 21 RGB values to frontend covering the min/max range.
When the page is first opened, I can set the proper color as preview but when item state is updated, I can only use one of the 21 colours, the most approaching.
Of course, I can also increase this number if values.

The idea of this "preview" color could also be applied to the Colorpicker widget.

**Comment by andrewfg** [comment]
> The idea of this "preview" color could also be applied to the Colorpicker widget.

Good idea!

**Comment by andrewfg** [comment]
> when item state is updated, I can only use one of the 21 colours, the most approaching.

I guess there are two sub- cases..

1. when the state is updated from the picker itself
2. when the state is updated by notification from OH core

**Comment by lolodomo** [comment]
When the color is updated from the picker itself, a command is sent to the item. The widget is updated when it receives a feedback state from the item.

**Comment by lolodomo** [comment]
This is now ready for review.

Here is the rendering of the widget:

image

**Review by kaikreuzer — APPROVED** [review]

**Comment by mueller-ma** [comment]
@lolodomo The "ok" button in the popup suggests that the value is updated when the button is pressed. But it seems that it's updated as soon as the slider is changed. Maybe rename the button to "close"?

**Comment by lolodomo** [comment]
Yes, same behaviour as for the color picker. I agree that "Close" would be more appropriate in both pop-ups.

**Pull request merged**
