### PR TITLE
Add oh-context component

### LINKED ISSUE #2148: Widget functions and constants
There has been an interesting discussion on the forums about [how best to reduce the repetition of long expressions and improve readability and maintainability of complex widgets yaml](https://community.openhab.org/t/substitutions-in-widgets/150303).

That discussion has led me to propose the addition of a new widget component: a component that just adds to the widget context.  Like the `oh-repeater` , this widget would not, itself, be rendered but would inject evaluated objects into the context available to its child components.

Initially, I see this component as giving the widget creator the capability of using both functions and constants in widget expressions.  Here are some usage examples:

I have a widget which uses multiple numbers that I want rounded to the nearest 0.25. For every location in the widget where I want one of these values I can write out the expression:
```
text: =Math.round(Number.parseFloat(@@'ThisNumberItem') * 4) / 4
```
But with a context component that provided functions, I could define this once:
```
- component: oh-context
  config:
    functions:
      near25: =(i) => Math.round(Number.parseFloat(@@i) * 4) / 4
  slots:
    default:
      - component: f7-card
        config:
          title: =func.near25('ThisNumberItem')
...
```

I think constants could have the potential to be even more useful. First, because there are many more common situations where they could be used and second because they can themselves be objects.

Many complex widgets are built around the idea that the items involved have a naming structure that is some base item + an additional identifier. These are often then set in the props of a widget and used something like this:
```
textColor: =(@@(props.item + props.mode) == 'HEAT')?('rgb(255,67,0)'):('rgb(37,37,255)')
```
Constants, evaluated only at widget mounting, would allow for these constructions to be much more readable:
```
- component: oh-context
  config:
    constants:
      iMode: =props.item + props.mode
  slots:
    default:
      - component: f7-card
        config:
          textColor: =(@@(const.iMode) == 'HEAT')?('rgb(255,67,0)'):('rgb(37,37,255)')
```

In the UI docs, there a brief example of how to use objects in the widget expressions to select among several options.  Although it is shorter and more clear than the nested ternary statements, it can still get long and awkward:
```
textColor: =({'heat':'orange','cool':'blue','auto':'green','off':'white'})[@@hvacModeItem] || 'red'
```
With the ability to define a constant object this cleans up very nicely:
```
- component: oh-context
  config:
    constants:
      backColor:
        heat: orange
        cool: blue
        auto: green
        off: white
  slots:
    default:
      - component: f7-card
        config:
          textColor: =const.backColor[@@hvacModeItem] || 'red'
```

Is this worth pursuing further?

Edit:
It is worth noting, as I point out in the thread linked above, that by "misusing" an `oh-repeater` this capability is already mostly available.  The addition of a dedicated component for it would just formalize this and allow for it to be optimized.

### LINKED ISSUE #2437: Widget variables not accessible to custom sub-widgets
## The problem

In a custom widget, variables can be manipulated using actions.  Those variables can be used in components in the widget.

However in a custom sub-widget, the variables are not accessible.  Any attempt to change a variable in the custom sub-widget is not reflected in the variable in the parent widget.  Similarly, variables such as loop.name[index] or loop.name_source are not available in the custom sub-widget

## Expected behavior

It would be expected / desirable to have full access to the variables in the parent widget in the scope of the custom sub-widget.  If an oh-toggle, for example, were to be replaced with a custom toggle, it would be expected that the custom toggle would be able to manipulate a parent widget variable in the same way the oh-toggle can.  Values can be passed into the sub-widget using props but the sub-widget should be able to manipulate the variable in the parent's scope in the same way that an oh-component can.

If possible it would be desirable to be able to pass variables to sub-widgets either by value or by reference rather than have to update the code of the sub-widget to match the name of the parent widget variable.  That would make a library of sub-widgets more practical to use.

## Steps to reproduce

1. Create a parent widget that has components modifying various variables 
2. Create an accordion list using an itemsInGroup sourcetype
3. Within the list use a custom widget that is intended to modify the variables in the parent widget

Neither the parent widget's variables nor the loop.name_source variable of the list are available in the custom widget.  Any attempt to manipulate the variable seems only to manipulate a local copy and does not affect the variable in the parent widget.

## Your environment

```yaml
runtimeInfo:
  version: 4.1.1
  buildString: Release Build
locale: en-GB
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.9
  javaVendor: Raspbian
  osName: Linux
  osVersion: 6.1.21-v8+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 167726040
  totalMemory: 382373888
  uptime: 2336371
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-enocean
  - binding-homematic
  - binding-hue
  - binding-samsungtv
  - binding-squeezebox
  - binding-zwave
  - misc-hueemulation
  - misc-openhabcloud
  - persistence-rrd4j
  - transformation-map
  - ui-basic
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: en-GB
    languages:
      - en-GB
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1280
    height: 1024
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0
timestamp: 2024-03-01T12:41:06.234Z

```

## Browser console

```txt

```

### PR DESCRIPTION
**Pull request by JustinGeorgi**
Closes #2437, Closes #2148

This PR adds a new component, the oh-context.  Similar to the repeater, this component is not rendered, but injects information into the widget at it's tree location.

The component allows for that addition of three things:
* functions - using the arrow function syntax, named functions can be declared and reused in all subsequent expressions
* constants - constants can be defined as either single values, arrays, or objects
* variables - variables can be defined with default values.  These variables are local in scope to the oh-context and it's descendants and take precedence over other variables of the same name from higher contexts (including general component variable usage.
  * Variables are not divided into global vs local explicitly.  But a oh-context used as the root component of a widget will have its variables in the context of all the other components on that widget and thus they essentially have a global context within that widget.
  * In contrast to the basic widget variables, oh-context variables do have bi-directional passage between a main widget and a sub widget.

Here is are widgets that I have been using to test all these different capabilities:

Main widget:
```yaml
uid: oh_context_demo
tags: []
props: {}
timestamp: Apr 13, 2024, 10:44:43 AM
component: oh-context
config:
  constants:
    fruitColor:
      apple: red
      banana: =(dayjs().hour() < 6)?'green':((dayjs().hour() < 14)?'yellow':'black')
      orange: orange
      blueberry: blue
  functions:
    nextFruit: >
      =(fr) =>
        (fr)
        ? (['apple','banana','orange','blueberry'])[(['blueberry','apple','banana','orange']).indexOf(fr)]
        : ('apple')
    a2o: =(str) => (str || 'no fruit').replaceAll('a','o')
  variables:
    currentFruit: apple
slots:
  default:
    - component: f7-card
      config:
        content: =`Global fruit is ${fn.a2o(vars.currentFruit)}`
        textColor: =const.fruitColor[vars.currentFruit] || 'deeppurple'
        title: Fn, Const, and Scoped Variables
      slots:
        default:
          - component: oh-context
            config:
              functions:
                a2o: =(str) => (str || 'no fruit').replaceAll('a','0')
              variables:
                currentFruit: orange
            slots:
              default:
                - component: f7-row
                  config:
                    style:
                      justify-content: space-around
                  slots:
                    default:
                      - component: oh-button
                        config:
                          action: variable
                          actionVariable: currentFruit
                          actionVariableValue: =fn.nextFruit(vars.currentFruit)
                          text: =`Local fruit is ${fn.a2o(vars.currentFruit)}`
                      - component: oh-button
                        config:
                          text: =`Clear local fruit`
                          clearVariable: currentFruit
                - component: f7-row
                  config:
                    style:
                      justify-content: center
                  slots:
                    default:
                      - component: Label
                        config:
                          text: Input local fruit
                      - component: oh-input
                        config:
                          type: text
                          variable: currentFruit
                          placeholder: Please select a fruit
                          outline: true
                          style:
                            margin-left: 18px
                            color: var(--f7-text-color)
    - component: oh-input-card
      config:
        title: Input global fruit
        type: text
        variable: currentFruit
        placeholder: Please select a fruit
    - component: oh-context
      config:
        constants:
          fruitColor:
            apple: green
            banana: black
            orange: orange
            blueberry: pink
      slots:
        default:
          - component: f7-card
            config:
              content: =`Global fruit is ${fn.a2o(vars.currentFruit)}`
              textColor: =const.fruitColor[vars.currentFruit] || 'deeppurple'
              title: Fn, Const, and Scoped Variables
            slots:
              default:
                - component: f7-row
                  config:
                    style:
                      justify-content: space-around
                  slots:
                    default:
                      - component: f7-row
                        config:
                          style:
                            justify-content: space-around
                        slots:
                          default:
                            - component: oh-button
                              config:
                                action: variable
                                actionVariable: currentFruit
                                actionVariableValue: =fn.nextFruit(vars.currentFruit)
                                text: =`Global fruit is ${fn.a2o(vars.currentFruit)}`
                            - component: oh-button
                              config:
                                text: =`Clear global fruit`
                                clearVariable: currentFruit
                            - component: oh-button
                              config:
                                action: variable
                                actionVariable: widgetFruit
                                actionVariableValue: =fn.nextFruit(vars.widgetFruit || 'apple')
                                text: =`Global widget fruit is ${fn.a2o(vars.widgetFruit || 'apple')}`
    - component: widget:oh_context_widget
    - component: oh-list-card
      config:
        title: Variables
      slots:
        default:
          - component: oh-toggle-item
            config:
              title: Toggle
              variable: togVar
          - component: oh-slider-item
            config:
              title: Slider
              variable: slideVar
          - component: oh-stepper-item
            config:
              title: Stepper
              variable: stepVar
    - component: oh-context
      config:
        variables:
          togVar: true
          slideVar: 10
          stepVar: 10
      slots:
        default:
          - component: oh-list-card
            config:
              title: Local Variables
            slots:
              default:
                - component: oh-toggle-item
                  config:
                    title: Toggle
                    variable: togVar
                - component: oh-slider-item
                  config:
                    title: Slider
                    variable: slideVar
                - component: oh-stepper-item
                  config:
                    title: Stepper
                    variable: stepVar
```
image

Sub widget included in the main widget:
```yaml
uid: oh_context_widget
tags: []
props:
  parameters: []
  parameterGroups: []
timestamp: Apr 13, 2024, 9:20:55 AM
component: f7-card
config:
  content: =`Global fruit is ${fn.a2o(vars.currentFruit)} but global widget fruit
    is ${fn.a2o(vars.widgetFruit || 'apple')}`
  textColor: =const.fruitColor[vars.widgetFruit || 'apple']
  title: Fn, Const, and Scoped Variables in Widgets
slots:
  default:
    - component: f7-row
      config:
        style:
          justify-content: space-around
      slots:
        default:
          - component: oh-button
            config:
              action: variable
              actionVariable: currentFruit
              actionVariableValue: =fn.nextFruit(vars.currentFruit)
              text: =`Global fruit is ${fn.a2o(vars.currentFruit)}`
          - component: oh-button
            config:
              action: variable
              actionVariable: widgetFruit
              actionVariableValue: =fn.nextFruit(vars.widgetFruit || 'apple')
              text: =`Global widget fruit is ${fn.a2o(vars.widgetFruit || 'apple')}`
          - component: oh-context
            config:
              variables:
                widgetFruit: blueberry
            slots:
              default:
                - component: oh-button
                  config:
                    action: variable
                    actionVariable: widgetFruit
                    actionVariableValue: =fn.nextFruit(vars.widgetFruit)
                    text: =`Local widget fruit is ${fn.a2o(vars.widgetFruit)}`
```

I've done some pretty extensive testing, but this has grown into a fairly large addition, so any and all additional testing is appreciated.  There's no telling what I've missed.

### CODE REVIEW

**Review by florian-h05 — APPROVED** [review]
LGTM, thanks!
Very nice addition.

It took me a bit to figure out the scoping of the vars, so I added JSDoc to the `getVariableScope` method:

```js
    /**
     * Get the oh-context variables scope for a given variable key.
     *
     * If no variable with the given key is found in the given scope, the parent context/scope is checked, and so on.
     * If the variable is not found in any scope, <code>null</code> is returned.
     *
     * oh-context variables are local in scope to the oh-context and it's children and take precedence over other variables
     * of the same name from higher contexts/scopes, including normal variables.
     * Changes to oh-context variables done by children are propagated to the parent, which is not the case with normal variables.
     *
     * @param {object} varObj the object containing the variables for each context/scope
     * @param {string} scopeObj the key of the given variable context/scope
     * @param {string} key the key of the variable
     * @returns {string|null} the key of the variable context/scope to be used
     */
```
Please let me know it that doc is correct @JustinGeorgi.

I also did several minor code improvements, I will soon rebase and resolve the conflicts.

**Comment by florian-h05** [comment]
@JustinGeorgi As far as I have tested with your demo widgets, nothing got broken by the rebasing, even though the conflict was a bit tricky.

Please have a final look/do a final test and let me know when I should merge.

**Review by florian-h05 — APPROVED** [review]

**Comment by JustinGeorgi** [comment]
Thanks, the additions look pretty good to me.

I don't know if it's worth being more precise on the last line of the JSDoc because the normal variable system for propagating variable values to parents is actually different for components and widgets (components do, widgets do not).  So technically,
```
* Changes to oh-context variables done by children are propagated to the parent, which is not the case with normal variables.
```
is a little mis-leading about the normal variables, but I personally don't think it's a big concern because it is true that both work with the oh-context.

> Please have a final look/do a final test and let me know when I should merge.

Checks out with all the tests I've run.  As far as I'm concerned it's ready to merge.

**Comment by florian-h05** [comment]
Thanks for the feedback.
So the following should be better?

> * Changes to oh-context variables done by children are always propagated to the parent, which is not the case with normal variables used inside widgets.

**Comment by JustinGeorgi** [comment]
> So the following should be better?
> 
> > Changes to oh-context variables done by children are always propagated to the parent, which is not the case with normal variables used inside widgets.

Yeah, that's great.

**Comment by florian-h05** [comment]
Can you please update the docs?

**Comment by JustinGeorgi** [comment]
> Can you please update the docs?

Of course.  I'll probably have time in the next week or so.

**Comment by SimonB27P** [comment]
This is excellent news!  Thank-you for all the hard work on this.  This will greatly simplify the widgets I have been working on recently.

Can you tell me - how can I test this?

**Comment by SimonB27P** [comment]
Thanks Florian

Your example widget above looks pretty self-explanantory.  I noticed the docs are not updated yet and I presume it's not in the current stable distribution but I was wondering whether it is in the 4.2 M3 milestone?

Thanks again for the work on this.  It promises to be awesome.  I've got some widgets to re-write having spent a lot of time scratching my head and working around the lack of declared variables with defaults or passing variables into custom sub-widgets.  The functions willbe useful too.

**Comment by florian-h05** [comment]
> Your example widget above looks pretty self-explanantory.

FYI this PR is @JustinGeorgi ‘s work, not mine. I am the one who reviewed and merged, but not who wrote it.

> I noticed the docs are not updated yet. 

Once Justin created a PR to update the docs, they will be at https://next.openhab.org/docs. https://www.openhab.org/docs holds the stable docs, next always the latest docs from the current state of the repo.

> I was wondering whether it is in the 4.2 M3 milestone?

No, if it was, the release notes would mention it, and as M3 was released two weeks ago and this PR was merged yesterday, it obviously cannot be in the milestone 😉
FYI you can click on the commit hash above where it says „florian-h05 merged commit … into main“, where you’ll get to the commit page. After the commit message you’ll see information about the branch (in that case „main“) and see if any tags are „active“ for that commit. If something is in a release or a milestone, it will have the according tag.

**Comment by JustinGeorgi** [comment]
> Can you please update the docs?

https://github.com/openhab/openhab-docs/pull/2313

**Pull request merged**
