### PR TITLE
Ignore Eclipse project specific settings

### LINKED ISSUE #48: Build on CI broken
@wborn / @openhab/webui-maintainers the build on Jenkins is broken since today, something wrong with the SAT definition. I did not build it locally to validate the error yet.

```
18:02:20 Started by an SCM change
18:02:20 Started by an SCM change
18:02:20 [EnvInject] - Loading node environment variables.
18:02:20 Building in workspace /var/jenkins_home/workspace/openHAB-WebUI
18:02:20 No credentials specified
18:02:20  > git rev-parse --is-inside-work-tree # timeout=10
18:02:20 Fetching changes from the remote Git repository
18:02:20  > git config remote.origin.url https://github.com/openhab/openhab-webui # timeout=10
18:02:20 Fetching upstream changes from https://github.com/openhab/openhab-webui
18:02:20  > git --version # timeout=10
18:02:20  > git fetch --tags --progress https://github.com/openhab/openhab-webui +refs/heads/*:refs/remotes/origin/*
18:02:22  > git rev-parse origin/master^{commit} # timeout=10
18:02:22 Checking out Revision 2878a59ceae55daba1e4c4ba9fd4c84f917c0d45 (origin/master)
18:02:22  > git config core.sparsecheckout # timeout=10
18:02:22  > git checkout -f 2878a59ceae55daba1e4c4ba9fd4c84f917c0d45
18:02:22 Commit message: "Fix Java 11 build (#41)"
18:02:22  > git rev-list --no-walk 249e33b2f88356650db66d85a5aba243fe6176f8 # timeout=10
18:02:22 Cleaning workspace
18:02:22  > git rev-parse --verify HEAD # timeout=10
18:02:22 Resetting working tree
18:02:22  > git reset --hard # timeout=10
18:02:23  > git clean -fdx # timeout=10
18:03:15 Jenkins Artifactory Plugin version: 2.16.2
18:03:16 Parsing POMs
18:03:19 ERROR: Failed to parse POMs
18:03:19 org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
18:03:19 [ERROR] 'build.plugins.plugin.version' for org.openhab.tools.sat:sat-plugin must be a valid version but is '${sat.version}'. @ org.openhab.ui:org.openhab.ui.reactor:2.5.0-SNAPSHOT, /var/jenkins_home/workspace/openHAB-WebUI/pom.xml, line 522, column 24
18:03:19 [ERROR] 'build.plugins.plugin.version' for org.openhab.tools.sat:sat-plugin must be a valid version but is '${sat.version}'. @ org.openhab.ui:org.openhab.ui.reactor:2.5.0-SNAPSHOT, /var/jenkins_home/workspace/openHAB-WebUI/pom.xml, line 522, column 24
18:03:19 [ERROR] 'build.plugins.plugin.version' for org.openhab.tools.sat:sat-plugin must be a valid version but is '${sat.version}'. @ org.openhab.ui:org.openhab.ui.reactor:2.5.0-SNAPSHOT, /var/jenkins_home/workspace/openHAB-WebUI/pom.xml, line 522, column 24
18:03:19 [ERROR] 'build.plugins.plugin.version' for org.openhab.tools.sat:sat-plugin must be a valid version but is '${sat.version}'. @ org.openhab.ui:org.openhab.ui.reactor:2.5.0-SNAPSHOT, /var/jenkins_home/workspace/openHAB-WebUI/pom.xml, line 522, column 24
18:03:19 [ERROR] 'build.plugins.plugin.version' for org.openhab.tools.sat:sat-plugin must be a valid version but is '${sat.version}'. @ org.openhab.ui:org.openhab.ui.reactor:2.5.0-SNAPSHOT, /var/jenkins_home/workspace/openHAB-WebUI/pom.xml, line 522, column 24
18:03:19 [ERROR] 'build.plugins.plugin.version' for org.openhab.tools.sat:sat-plugin must be a valid version but is '${sat.version}'. @ org.openhab.ui:org.openhab.ui.reactor:2.5.0-SNAPSHOT, /var/jenkins_home/workspace/openHAB-WebUI/pom.xml, line 522, column 24
18:03:19 [ERROR] 'build.plugins.plugin.version' for org.openhab.tools.sat:sat-plugin must be a valid version but is '${sat.version}'. @ org.openhab.ui:org.openhab.ui.reactor:2.5.0-SNAPSHOT, /var/jenkins_home/workspace/openHAB-WebUI/pom.xml, line 522, column 24
18:03:19 [ERROR] 'build.plugins.plugin.version' for org.openhab.tools.sat:sat-plugin must be a valid version but is '${sat.version}'. @ org.openhab.ui:org.openhab.ui.reactor:2.5.0-SNAPSHOT, /var/jenkins_home/workspace/openHAB-WebUI/pom.xml, line 522, column 24
18:03:19 [ERROR] 'build.plugins.plugin.version' for org.openhab.tools.sat:sat-plugin must be a valid version but is '${sat.version}'. @ org.openhab.ui:org.openhab.ui.reactor:2.5.0-SNAPSHOT, /var/jenkins_home/workspace/openHAB-WebUI/pom.xml, line 522, column 24
18:03:19 [ERROR] 'build.plugins.plugin.version' for org.openhab.tools.sat:sat-plugin must be a valid version but is '${sat.version}'. @ org.openhab.ui:org.openhab.ui.reactor:2.5.0-SNAPSHOT, /var/jenkins_home/workspace/openHAB-WebUI/pom.xml, line 522, column 24
18:03:19 [ERROR] 'build.plugins.plugin.version' for org.openhab.tools.sat:sat-plugin must be a valid version but is '${sat.version}'. @ org.openhab.ui:org.openhab.ui.reactor:2.5.0-SNAPSHOT, /var/jenkins_home/workspace/openHAB-WebUI/pom.xml, line 522, column 24
18:03:19 [ERROR] 'build.plugins.plugin.version' for org.openhab.tools.sat:sat-plugin must be a valid version but is '${sat.version}'. @ org.openhab.ui:org.openhab.ui.reactor:2.5.0-SNAPSHOT, /var/jenkins_home/workspace/openHAB-WebUI/pom.xml, line 522, column 24
18:03:19 [ERROR] 'build.plugins.plugin.version' for org.openhab.tools.sat:sat-plugin must be a valid version but is '${sat.version}'. @ org.openhab.ui:org.openhab.ui.reactor:2.5.0-SNAPSHOT, /var/jenkins_home/workspace/openHAB-WebUI/pom.xml, line 522, column 24
18:03:19 [ERROR] 'build.plugins.plugin.version' for org.openhab.tools.sat:sat-plugin must be a valid version but is '${sat.version}'. @ org.openhab.ui:org.openhab.ui.reactor:2.5.0-SNAPSHOT, /var/jenkins_home/workspace/openHAB-WebUI/pom.xml, line 522, column 24
18:03:19 
18:03:19 	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:364)
18:03:19 	at org.jfrog.build.extractor.maven.ArtifactoryProjectBuilder.build(ArtifactoryProjectBuilder.java:31)
18:03:19 	at hudson.maven.MavenEmbedder.buildProjects(MavenEmbedder.java:361)
18:03:19 	at hudson.maven.MavenEmbedder.readProjects(MavenEmbedder.java:331)
18:03:19 	at hudson.maven.MavenModuleSetBuild$PomParser.invoke(MavenModuleSetBuild.java:1328)
18:03:19 	at hudson.maven.MavenModuleSetBuild$PomParser.invoke(MavenModuleSetBuild.java:1125)
18:03:19 	at hudson.FilePath.act(FilePath.java:1074)
18:03:19 	at hudson.FilePath.act(FilePath.java:1057)
18:03:19 	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.parsePoms(MavenModuleSetBuild.java:986)
18:03:19 	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:691)
18:03:19 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
18:03:19 	at hudson.model.Run.execute(Run.java:1816)
18:03:19 	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
18:03:19 	at hudson.model.ResourceController.execute(ResourceController.java:97)
18:03:19 	at hudson.model.Executor.run(Executor.java:429)
18:03:19 [openHAB-WebUI] $ /bin/sh -xe /tmp/jenkins3955556582398135702.sh
18:03:19 + cd /var/jenkins_home/workspace/openHAB-WebUI
18:03:19 + chmod 744 repo/target/publish-bintray.sh
18:03:19 chmod: cannot access 'repo/target/publish-bintray.sh': No such file or directory
18:03:19 Build step 'Execute shell' marked build as failure
18:03:19 [ANALYSIS-COLLECTOR] Computing warning deltas based on reference build #28
18:03:19 Archiving artifacts
18:03:20 Finished: FAILURE

### PR DESCRIPTION
**Pull request by wborn**
Adds an ignore for the Eclipse project specific settings and adds missing .project files so you don't end up with lots of new/untracked files after importing these projects.

### CODE REVIEW

**Comment by maggu2810** [comment]
I wonder why Travis CI does not report its status. The commits are three days old.

**Comment by maggu2810** [comment]
@kaikreuzer On openhab-core you told me you don't like an Eclipse project for the base reactor. To be more detailed: An Eclipse project that contains other projects as subdirectory and that content is also part of the specific project.
Have you changed your mind?

**Comment by wborn** [comment]
Should we add an ignore instead for such projects if the project files should not be committed to the repo?

It's quite annoying if you mass import projects and end up with untracked files. I'm fine with such projects and maybe some contributors also like them. Usually I just close them. Sometimes it's easy to be able to edit a POM from Eclipse and then I open them again. :-)

**Comment by maggu2810** [comment]
I add the reactor projects all the time. :wink: 

I edit POMs inside the Eclipse IDE, but I also have to change the XML formatting for indentation to use two spaces instead of tabs.
I miss special formatting rules for `pom`s.

Another approach that perhaps is acceptable for Kai is to add the reactor projects but filter the subprojects in Eclipse.
The automatic (experimental) filtering Eclipse provides does not work, so it needs to be added manually once (I assume).

**Comment by kaikreuzer** [comment]
> Have you changed your mind?

No not really, I only misread the "added missing .project" part and didn't notice in the code that this was not about bundles, but about reactor folders.

My issue with the reactor projects is that they slow down the IDE as it has to manage many more files and especially that every file appears multiple times in the workspace, what makes resource lookups tedious etc. I think we should really aim for a workspace where you find every file only exactly once.

If there's a way to filter the subprojects from a folder, this would be ideal - then I am fully ok with having the reactor projects in the IDE as well.

**Comment by wborn** [comment]
> If there's a way to filter the subprojects from a folder

There's the "Hide folders of physically nested modules" m2e setting which should do just that:

m2e

**Comment by maggu2810** [comment]
That is the feature that does not work for me (at least all the time I tried it).

> The automatic (experimental) filtering Eclipse provides does not work, so it needs to be added manually once (I assume).

**Comment by wborn** [comment]
Did you also try removing/importing your projects after enabling it?

**Comment by maggu2810** [comment]
No... I will give it a try...

**Comment by kaikreuzer** [comment]
Trying to trigger Travis...

**Comment by kaikreuzer** [comment]
> No... I will give it a try...

I have tried it out: On my Mac, it doesn't work for me :-(
I have this menu option only in the global preferences - @wborn is your screenshot from the folder-specific settings?

**Comment by wborn** [comment]
The screenshot shows the global preferences. As you see in the screenshot it only shows the pom for the highlighted project. For me these changes are only applied when reimporting the project after enabling "Hide folders of physically nested modules".

**Comment by kaikreuzer** [comment]
That's exactly what I did, but it didn't help :-(.
@maggu2810 Did you have a chance to test it meanwhile?

**Comment by maggu2810** [comment]
It does not work for me.

* I enabled the option.
* I removed all projects.
* I imported the webui projects
* The reactor contains the bundles directory, its subdirectories and their content.

```
Version: 2019-06 M2 (4.12.0M2)
Build id: 20190509-1623
```

**Comment by wborn** [comment]
If it doesn't work for you I'll remove the .project files from this PR and only update the ignores in this PR.

**Comment by kaikreuzer** [comment]
Nonetheless, I'd be interested in what the difference between our setups might be...
@wborn You're on Linux, I suppose? Is Eclipse the same version as @maggu2810's?

**Comment by wborn** [comment]
Since I last tested this (Apr 14) I've upgraded my Ubuntu from 16.04.5 to 18.04.2 and Eclipse from 2018-12 to 2019-03. 

With my current setup I see the nested modules being hidden except for `org.openhab.ui.reactor.bundles`:

experimental

So I guess that's why they call this "experimental". :wink:

**Comment by wborn** [comment]
After I also removed **all** Web UI projects from Eclipse and cleaned the Eclipse files from the repo clone (`git clean -dfx`) the nested modules are also hidden from `org.openhab.ui.reactor.bundles`:

**Comment by kaikreuzer** [comment]
Removed everything from the workspace, cleaned all repos - still seeing all nested projects :-(
Indeed seems to be "experimental"...

**Comment by wborn** [comment]
Thanks for checking again! We'd better not use this feature if it isn't reliable. :disappointed:

**Pull request merged**
