### PR TITLE
[WIP][basicui] Block the UI when implicit user role is disabled

### PR DESCRIPTION
**Pull request by lolodomo**
Related to #1542

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
Here is the result:
image

The used page is the same as when listing the sitemaps.

**Comment by lolodomo** [comment]
Here is a jar for testing **with a OH 3.4 server**:
[org.openhab.ui.basic-3.4.1-SNAPSHOT.zip](https://github.com/openhab/openhab-webui/files/10366907/org.openhab.ui.basic-3.4.1-SNAPSHOT.zip)

**Comment by wborn** [comment]
Maybe you can use one servlet filter instead of adding the logic to each servlet?

**Comment by lolodomo** [comment]
> Maybe you can use one servlet filter instead of adding the logic to each servlet?

Can you please point an example (to help me understanding what you are talking about) ?

**Comment by lolodomo** [comment]
You mean javax.servlet.Filter ?
This could be added to the parent class and so be global for the 3 servlets.

**Comment by wborn** [comment]
I had a look at the code and it seems that the you can also create a Component that implements the `Handler` interface which will then be used for checking security constraints, see: [OpenHABHttpContext.handleSecurity](
https://github.com/openhab/openhab-core/blob/8d64ecfd8db99844d79a776fef37cbe527c1f0c6/bundles/org.openhab.core.io.http/src/main/java/org/openhab/core/io/http/internal/OpenHABHttpContext.java#L54). 

You can have a look at the [AuthenticationHandler](https://github.com/openhab/openhab-core/blob/8d64ecfd8db99844d79a776fef37cbe527c1f0c6/bundles/org.openhab.core.io.http.auth/src/main/java/org/openhab/core/io/http/auth/internal/AuthenticationHandler.java#L48) implementation.
It might also be an idea to make the [AuthenticationHandler.isSecured](https://github.com/openhab/openhab-core/blob/8d64ecfd8db99844d79a776fef37cbe527c1f0c6/bundles/org.openhab.core.io.http.auth/src/main/java/org/openhab/core/io/http/auth/internal/AuthenticationHandler.java#L134-L141) check more extensible so the same handler can be used for securing add-on Servlets. :slightly_smiling_face: 

If there wasn't any infrastructure in place already there are some Http Whiteboard annotations that can be used for creating filters, see [Registering Servlet Filters](https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.http.whiteboard.html#d0e121055). 

The `BaseServlet` will be removed with #1600 so I wouldn't add anything to that class.

**Comment by lolodomo** [comment]
> I had a look at the code and it seems that the you can also create a Component that implements the `Handler` interface which will then be used for checking security constraints, see: [OpenHABHttpContext.handleSecurity](https://github.com/openhab/openhab-core/blob/8d64ecfd8db99844d79a776fef37cbe527c1f0c6/bundles/org.openhab.core.io.http/src/main/java/org/openhab/core/io/http/internal/OpenHABHttpContext.java#L54).
> 
> You can have a look at the [AuthenticationHandler](https://github.com/openhab/openhab-core/blob/8d64ecfd8db99844d79a776fef37cbe527c1f0c6/bundles/org.openhab.core.io.http.auth/src/main/java/org/openhab/core/io/http/auth/internal/AuthenticationHandler.java#L48) implementation. It might also be an idea to make the [AuthenticationHandler.isSecured](https://github.com/openhab/openhab-core/blob/8d64ecfd8db99844d79a776fef37cbe527c1f0c6/bundles/org.openhab.core.io.http.auth/src/main/java/org/openhab/core/io/http/auth/internal/AuthenticationHandler.java#L134-L141) check more extensible so the same handler can be used for securing add-on Servlets. 🙂

Looks like a good approach ;)
I will try it.

**Comment by lolodomo** [comment]
I created a Handler service, I see that it is properly started. Unfortunately the "handle" method is not called when my servlet is invoked.

**Comment by lolodomo** [comment]
Ok, I was able to make it work by setting a higher priority to my new handler.
I really believe there is a bug in `AuthenticationHandler` because it does not call `context.execute(request, response)` when no exception is thrown. This is necessary to trigger the next handler.

**Comment by lolodomo** [comment]
@wborn : for my curiosity, can you explain in what case the AuthenticateHandler has a real usage ? Because in practice, at least with the default settings, this handler is doing nothing because the parameter org.openhab.auth:enabled is not set to true. To be verified but I believe this setting is even not defined at all and is apparently not exposed in MainUI. I have the strange feeling it is something not used by default.

By the way, I was finally able to block Basic UI just by implementing a specific `handler`. I will push my changes tomorrow.

I also checked what are the servlets in core framework. I identified 3:

- /audio
- /icon
- /chart

These servlets are by default not protected by any authentication. This is probably not critical but good to know. Something similar to what I did for the Basic UI servlets could certainly be applied.

**Comment by lolodomo** [comment]
Here is the new version implementing a new HTTP request handler.
Note that the 2 new classes have to be moved to the core framework. I will prepare a PR.
So this is still in progress.

**Comment by ghys** [comment]
> These servlets are by default not protected by any authentication. This is probably not critical but good to know. Something similar to what I did for the Basic UI servlets could certainly be applied.

Beware that requiring authorization for /icon might break the icons because the authorization header is not currently added to the image requests, in oh-icon widgets and related, like it is for API requests.

**Comment by lolodomo** [comment]
> Beware that requiring authorization for /icon might break the icons because the authorization header is not currently added to the image requests, in oh-icon widgets and related, like it is for API requests.

I had clearly in mind that such change could impact other UI.

**Comment by lolodomo** [comment]
As there is in parallel work to add authentication to Basic UI, I am stopping my work which will become useless.

**Pull request closed without merging**
