### PR TITLE
Update RelativeCI agent action

### PR DESCRIPTION
**Pull request by vio**
Hi! I noticed that you are still using the RelativeCI CLI agent with the inline API key. 

This PR replaces the CLI with the action agent running on workflow_run event and in the context of the default branch (secrets are not leaked to forks). To get a new API key, go to your organization settings 'API keys' page and generate a new one.

More resources:
- Example pull request from a forked repo: [Pull Request](https://github.com/relative-ci/openhab-webui/pull/2), [GitHub Actions](https://github.com/relative-ci/openhab-webui/actions/workflows/relative-ci.yml), [RelativeCI Job](https://app.relative-ci.com/projects/wDdf9e7l57l5Gn2wlV8Y/jobs/4-HZEwzCXmUeiL1LSvqGDa)
- [RelativeCI agent action setup guide](https://relative-ci.com/documentation/setup/agent/github-action/#workflow_run-event)
- [Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)

Feel free to reach out if you have any questions,
Vio

### CODE REVIEW

**Comment by ghys** [comment]
Thanks @vio for reaching out!
I created the new API key and deleted the old one (which was named "default"), and updated the GitHub secret.
Always nice to not leak credentials :)

I'm ready to merge it but would you please comment with a sign-off line (or amend the commit message, but just commenting is fine as I will include it in the final commit) like one from https://www.openhab.org/docs/developer/contributing.html#sign-your-work so I will set the DCO to pass.

**Comment by vio** [comment]
Hi @ghys, thank you for updating the API keys!I rebased, updated the commit message, and signed the commits. 

Let me know if you have any questions ;)

**Comment by florian-h05** [comment]
@ghys Could it be that the RelativeCI bot needs to get re-configured? This PR is missing the comment from the CI bot about changed web pack stats ...

**Comment by vio** [comment]
@florian-h05 the workflow_run workflow runs only in the context of the base branch. It must be merged first to run and send the webpack stats.

> To do this in a secure manner, the untrusted code must be handled via the pull_request trigger so that it is isolated in an unprivileged environment. The workflow processing the PR should then store any results like code coverage or failed/passed tests in artifacts and exit. The following workflow then starts on workflow_run where it is granted write permission to the target repository and access to repository secrets, so that it can download the artifacts and make any necessary modifications to the repository or interact with third party services that require repository secrets (e.g. API tokens).

https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

**Comment by florian-h05** [comment]
@vio Thanks for the info, then let's merge this!

**Review by florian-h05 — APPROVED** [review]

**Comment by florian-h05** [comment]
FYI the RelativeCI bot comments properly, see https://github.com/openhab/openhab-webui/pull/2094#issuecomment-1736014938.

@vio Thank you very much for fixing that API key leak!

**Comment by vio** [comment]
No problem, glad I could help! Feel free to reach out if you have any questions or if you need any help ;)

**Pull request merged**
